// ============================================================================
// basic.js — Tier 1 ground enemies: chasers, walkers, swarmers, brutes.
// These form the bulk of early waves and the cannon-fodder of later ones.
// ============================================================================

import { EnemyRegistry } from '../EnemyRegistry.js';
import { StatusType, DamageType } from '../../ecs/components/Combat.js';

EnemyRegistry.registerMany([
  {
    id: 'drone',
    name: 'Drone',
    behavior: 'chaser',
    shape: 'drone', color: 0xff3df0, accent: 0x29e7ff, scale: 1, orientYaw: false,
    health: 22, speed: 4.2, contactDamage: 8, radius: 0.45, height: 0.9,
    flying: true, hoverHeight: 2.2,
    xp: 1, currency: { min: 1, max: 2 }, weight: 10, tier: 0, unlockWave: 0,
    tags: ['ground', 'chaser'], detectRange: 50,
    glowPulse: { base: 1, amplitude: 0.5, speed: 3 },
    description: 'A floating recon drone. Slow but relentless.',
  },
  {
    id: 'runner',
    name: 'Runner',
    behavior: 'fastChaser',
    shape: 'shard', color: 0x29e7ff, accent: 0xffffff, scale: 0.9, orientYaw: true,
    health: 16, speed: 7.6, contactDamage: 6, radius: 0.4, height: 1.0,
    xp: 1, currency: { min: 1, max: 2 }, weight: 8, tier: 1, unlockWave: 1,
    tags: ['ground', 'fast'], detectRange: 55,
    description: 'Fast, weaving, fragile. Closes distance quickly.',
  },
  {
    id: 'walker',
    name: 'Walker',
    behavior: 'chaser',
    shape: 'walker', color: 0x8a5bff, accent: 0xff3df0, scale: 1, orientYaw: true,
    health: 45, speed: 3.4, contactDamage: 11, radius: 0.5, height: 1.3,
    armor: 2, xp: 2, currency: { min: 1, max: 3 }, weight: 7, tier: 1, unlockWave: 2,
    tags: ['ground', 'chaser'], detectRange: 45,
    description: 'A quadrupedal assault unit. Armored and persistent.',
  },
  {
    id: 'spider',
    name: 'Stalker',
    behavior: 'fastChaser',
    shape: 'spider', color: 0x66ff88, accent: 0x222222, scale: 1, orientYaw: true,
    health: 28, speed: 6.8, contactDamage: 9, radius: 0.5, height: 0.9,
    contactStatus: { chance: 0.25, type: StatusType.Slow, power: 1 },
    xp: 2, currency: { min: 1, max: 3 }, weight: 6, tier: 2, unlockWave: 4,
    tags: ['ground', 'fast', 'status'], detectRange: 50,
    description: 'A venomous arachnid that slows on hit.',
  },
  {
    id: 'swarmling',
    name: 'Swarmling',
    behavior: 'swarm',
    shape: 'swarm', color: 0xffaa44, accent: 0xffffff, scale: 0.7, orientYaw: false,
    health: 8, speed: 8.5, contactDamage: 4, radius: 0.3, height: 0.6,
    xp: 1, currency: { min: 0, max: 1, chance: 0.5 }, weight: 12, tier: 0, unlockWave: 0,
    tags: ['ground', 'swarm', 'fast'], detectRange: 40,
    description: 'Tiny, frantic, and everywhere. Strength in numbers.',
  },
  {
    id: 'brute',
    name: 'Brute',
    behavior: 'brute',
    shape: 'humanoid', color: 0xff5544, accent: 0xffaa44, scale: 1.3, orientYaw: true,
    health: 90, speed: 3.0, contactDamage: 16, radius: 0.7, height: 1.8,
    armor: 4, xp: 4, currency: { min: 2, max: 5 }, weight: 5, tier: 2, unlockWave: 5,
    tags: ['ground', 'heavy', 'slam'], detectRange: 40,
    description: 'A towering brawler that ground-pounds when close.',
  },
  {
    id: 'bomber',
    name: 'Bomber',
    behavior: 'bomber',
    shape: 'orb', color: 0xff6622, accent: 0xffe066, scale: 1, orientYaw: false,
    health: 26, speed: 5.4, contactDamage: 28, radius: 0.5, height: 1.0,
    flying: true, hoverHeight: 1.8,
    xp: 3, currency: { min: 1, max: 3 }, weight: 5, tier: 2, unlockWave: 6,
    tags: ['flying', 'suicide', 'explosive'], detectRange: 45,
    description: 'Detonates on proximity. Shoot it before it reaches you.',
  },
  {
    id: 'splitter',
    name: 'Splitter',
    behavior: 'splitter',
    shape: 'blob', color: 0x66ddff, accent: 0xffffff, scale: 1.2, orientYaw: false,
    health: 50, speed: 4.0, contactDamage: 10, radius: 0.6, height: 1.2,
    xp: 3, currency: { min: 1, max: 3 }, weight: 4, tier: 2, unlockWave: 7,
    tags: ['ground', 'split'], detectRange: 45,
    splitInto: { id: 'swarmling', count: 3 },
    description: 'Splits into swarmlings when destroyed.',
    onDeath: 'split',
  },
  {
    id: 'blob',
    name: 'Amoeboid',
    behavior: 'chaser',
    shape: 'blob', color: 0xaa66ff, accent: 0xff66aa, scale: 1.1, orientYaw: false,
    health: 60, speed: 3.6, contactDamage: 12, radius: 0.6, height: 1.1,
    armor: 2, regen: 4, xp: 3, currency: { min: 1, max: 3 }, weight: 4, tier: 2, unlockWave: 8,
    tags: ['ground', 'regen'], detectRange: 40,
    glowPulse: { base: 0.8, amplitude: 0.4, speed: 4 },
    description: 'Regenerates rapidly. Burst it down.',
  },
  {
    id: 'ghost',
    name: 'Wraith',
    behavior: 'dodger',
    shape: 'ghost', color: 0x88aaff, accent: 0xffffff, scale: 1, orientYaw: false,
    health: 34, speed: 5.0, contactDamage: 10, radius: 0.5, height: 1.3,
    flying: true, hoverHeight: 1.6,
    xp: 3, currency: { min: 1, max: 3 }, weight: 4, tier: 3, unlockWave: 9,
    tags: ['flying', 'evasive'], detectRange: 50,
    resistances: { kinetic: 0.3 },
    description: 'Phases and dodges. Resists kinetic damage.',
  },
  {
    id: 'charger',
    name: 'Charger',
    behavior: 'charger',
    shape: 'walker', color: 0xffcc33, accent: 0xff3344, scale: 1.1, orientYaw: true,
    health: 55, speed: 3.8, contactDamage: 18, radius: 0.55, height: 1.3,
    armor: 3, xp: 4, currency: { min: 2, max: 4 }, weight: 4, tier: 3, unlockWave: 10,
    tags: ['ground', 'charger'], detectRange: 50,
    description: 'Telegraphs, then charges at high speed. Sidestep it.',
  },
  {
    id: 'cube',
    name: 'Polyhedron',
    behavior: 'chaser',
    shape: 'cube', color: 0x4fffd0, accent: 0xffffff, scale: 1, orientYaw: false,
    health: 40, speed: 4.5, contactDamage: 10, radius: 0.5, height: 0.9,
    xp: 2, currency: { min: 1, max: 3 }, weight: 5, tier: 2, unlockWave: 6,
    tags: ['ground', 'chaser'], detectRange: 45,
    description: 'A spinning geometric horror.',
  },
]);
