// ============================================================================
// flying2.js — Additional flying enemies: more drones, bombers, casters.
// ============================================================================

import { EnemyRegistry } from '../EnemyRegistry.js';
import { StatusType, DamageType } from '../../ecs/components/Combat.js';

EnemyRegistry.registerMany([
  { id: 'seekerDrone', name: 'Seeker Drone', behavior: 'orbiter', shape: 'drone', color: 0xff3df0, accent: 0x29e7ff, scale: 0.9, orientYaw: false,
    health: 24, speed: 5.4, contactDamage: 6, radius: 0.4, height: 0.8, flying: true, hoverHeight: 2.8, xp: 2, currency: { min: 1, max: 3 }, weight: 5, tier: 2, unlockWave: 5,
    tags: ['flying', 'ranged'], detectRange: 50,
    attack: { type: 'ranged', damage: 7, range: 22, cooldown: 1.3, preferredRange: 8, projectile: { speed: 32, color: 0xff3df0, shape: 'orb', scale: 0.8, radius: 0.18, lifetime: 4 } },
    description: 'A pursuit drone that orbits and snipes.' },
  { id: 'bomberDrone', name: 'Bomb Drone', behavior: 'kamikaze', shape: 'orb', color: 0xff3344, accent: 0xffe066, scale: 0.9, orientYaw: false,
    health: 18, speed: 8.5, contactDamage: 22, radius: 0.4, height: 0.9, flying: true, hoverHeight: 2.4, xp: 3, currency: { min: 1, max: 2 }, weight: 4, tier: 3, unlockWave: 8,
    tags: ['flying', 'suicide', 'explosive'], detectRange: 50, description: 'A diving bomb drone. Splash on impact.' },
  { id: 'caster', name: 'Caster', behavior: 'shooter', shape: 'drone', color: 0xb266ff, accent: 0xff3df0, scale: 1.1, orientYaw: false,
    health: 44, speed: 2.8, contactDamage: 6, radius: 0.5, height: 1.1, flying: true, hoverHeight: 4.5, xp: 4, currency: { min: 2, max: 4 }, weight: 3, tier: 3, unlockWave: 9,
    tags: ['flying', 'ranged'], detectRange: 60,
    attack: { type: 'ranged', damage: 11, range: 40, cooldown: 1.6, preferredRange: 20, projectile: { speed: 34, color: 0xb266ff, shape: 'shard', scale: 1.1, radius: 0.22, lifetime: 5 } },
    description: 'A high-altitude caster lobbing heavy shards.' },
  { id: 'swarmFly', name: 'Gnat', behavior: 'swarm', shape: 'swarm', color: 0xffaa44, accent: 0xffffff, scale: 0.5, orientYaw: false,
    health: 6, speed: 9, contactDamage: 3, radius: 0.25, height: 0.5, flying: true, hoverHeight: 1.8, xp: 1, currency: { min: 0, max: 1, chance: 0.4 }, weight: 10, tier: 1, unlockWave: 3,
    tags: ['flying', 'swarm', 'fast'], detectRange: 40, description: 'A cloud of gnats. Negligible alone, deadly in numbers.' },
  { id: 'voidRay', name: 'Void Ray', behavior: 'strafer', shape: 'orb', color: 0x8a5bff, accent: 0xff3df0, scale: 1.2, orientYaw: false,
    health: 55, speed: 4.6, contactDamage: 10, radius: 0.6, height: 1.0, flying: true, hoverHeight: 3.4, xp: 5, currency: { min: 2, max: 4 }, weight: 3, tier: 4, unlockWave: 12,
    tags: ['flying', 'ranged', 'elite'], detectRange: 55,
    attack: { type: 'ranged', damage: 12, range: 32, cooldown: 1.0, preferredRange: 14, projectile: { speed: 40, color: 0x8a5bff, shape: 'shard', scale: 1, radius: 0.2, lifetime: 4 } },
    glowPulse: { base: 1, amplitude: 0.7, speed: 2 }, description: 'A void ray that strafes with rapid shard fire.', eliteHealthMult: 1.6 },
  { id: 'mortar', name: 'Mortar', behavior: 'turret', shape: 'orb', color: 0xffb347, accent: 0xff3df0, scale: 1.2, orientYaw: false,
    health: 60, speed: 0.6, contactDamage: 6, radius: 0.6, height: 1.0, flying: true, hoverHeight: 6, xp: 5, currency: { min: 2, max: 4 }, weight: 2, tier: 4, unlockWave: 13,
    tags: ['flying', 'ranged', 'aoe'], detectRange: 60,
    attack: { type: 'ranged', damage: 16, range: 45, cooldown: 2.2, preferredRange: 20, projectile: { speed: 22, gravity: 1.0, color: 0xffb347, shape: 'chunky', scale: 1.3, radius: 0.26, lifetime: 4 } },
    description: 'A high-altitude mortar lobbing arcing explosives.' },
  { id: 'spectre', name: 'Spectre', behavior: 'dodger', shape: 'ghost', color: 0x88ffcc, accent: 0xffffff, scale: 1, orientYaw: false,
    health: 30, speed: 6, contactDamage: 9, radius: 0.5, height: 1.2, flying: true, hoverHeight: 2.2, xp: 4, currency: { min: 1, max: 3 }, weight: 3, tier: 3, unlockWave: 11,
    tags: ['flying', 'evasive', 'ranged'], detectRange: 55, resistances: { kinetic: 0.4 },
    attack: { type: 'ranged', damage: 8, range: 24, cooldown: 1.5, preferredRange: 14, projectile: { speed: 38, color: 0x88ffcc, shape: 'orb', scale: 0.8, radius: 0.2, lifetime: 4 } },
    description: 'A phasing spectre that dodges and resists kinetic rounds.' },
  { id: 'reaper', name: 'Reaper', behavior: 'fastChaser', shape: 'shard', color: 0xff3df0, accent: 0x8a5bff, scale: 1, orientYaw: true,
    health: 40, speed: 8.5, contactDamage: 14, radius: 0.45, height: 1.2, flying: true, hoverHeight: 2.0, xp: 5, currency: { min: 2, max: 4 }, weight: 3, tier: 4, unlockWave: 14,
    tags: ['flying', 'fast', 'elite'], detectRange: 55, description: 'A diving reaper that closes terrifyingly fast.', eliteHealthMult: 1.5 },
  { id: 'artillery', name: 'Artillery Eye', behavior: 'turret', shape: 'orb', color: 0xff5544, accent: 0xffe066, scale: 1.3, orientYaw: false,
    health: 80, speed: 0.4, contactDamage: 6, radius: 0.7, height: 1.2, flying: true, hoverHeight: 7, xp: 7, currency: { min: 3, max: 6 }, weight: 2, tier: 4, unlockWave: 15,
    tags: ['flying', 'ranged', 'aoe', 'elite'], detectRange: 65,
    attack: { type: 'ranged', damage: 22, range: 55, cooldown: 2.4, preferredRange: 25, projectile: { speed: 26, gravity: 1.2, color: 0xff5544, shape: 'chunky', scale: 1.5, radius: 0.3, lifetime: 5 } },
    glowPulse: { base: 1, amplitude: 0.6, speed: 1.5 }, description: 'A hovering artillery eye raining heavy mortars.', eliteHealthMult: 1.7 },
  { id: 'phoenix', name: 'Phoenix', behavior: 'shooter', shape: 'drone', color: 0xff7733, accent: 0xffe066, scale: 1.3, orientYaw: false,
    health: 70, speed: 4.0, contactDamage: 12, radius: 0.6, height: 1.1, flying: true, hoverHeight: 3.6, xp: 7, currency: { min: 3, max: 6 }, weight: 2, tier: 4, unlockWave: 16,
    tags: ['flying', 'ranged', 'status', 'elite'], detectRange: 60,
    attack: { type: 'ranged', damage: 12, range: 36, cooldown: 1.3, preferredRange: 16, projectile: { speed: 30, color: 0xff7733, shape: 'orb', scale: 1.2, radius: 0.28, lifetime: 4 } },
    contactStatus: { chance: 0.3, type: StatusType.Burn, power: 1 }, glowPulse: { base: 1.2, amplitude: 0.6, speed: 2 },
    description: 'A fiery phoenix that rains burning bolts.', eliteHealthMult: 1.6 },
]);
