// ============================================================================
// ranged.js — Tier 2/3 ranged enemies that pressure the player from distance.
// ============================================================================

import { EnemyRegistry } from '../EnemyRegistry.js';
import { StatusType, DamageType } from '../../ecs/components/Combat.js';

EnemyRegistry.registerMany([
  {
    id: 'shooter',
    name: 'Gunner',
    behavior: 'shooter',
    shape: 'humanoid', color: 0xff5a8a, accent: 0x29e7ff, scale: 1, orientYaw: true,
    health: 30, speed: 3.0, contactDamage: 8, radius: 0.5, height: 1.4,
    xp: 2, currency: { min: 1, max: 3 }, weight: 7, tier: 2, unlockWave: 3,
    tags: ['ground', 'ranged'], detectRange: 55,
    attack: { type: 'ranged', damage: 8, range: 30, cooldown: 1.6, preferredRange: 10,
      projectile: { speed: 30, color: 0xff5a8a, shape: 'orb', scale: 1, radius: 0.22, lifetime: 4 } },
    description: 'Keeps its distance and lobs energy bolts.',
  },
  {
    id: 'shotgunner',
    name: 'Scattergunner',
    behavior: 'shotgunner',
    shape: 'humanoid', color: 0xffaa44, accent: 0xff5522, scale: 1, orientYaw: true,
    health: 36, speed: 2.8, contactDamage: 8, radius: 0.5, height: 1.4,
    armor: 1, xp: 3, currency: { min: 1, max: 3 }, weight: 5, tier: 2, unlockWave: 6,
    tags: ['ground', 'ranged', 'spread'], detectRange: 50,
    attack: { type: 'ranged', damage: 5, range: 16, cooldown: 2.2, preferredRange: 8,
      projectile: { speed: 26, color: 0xffaa44, shape: 'orb', scale: 0.9, radius: 0.2, lifetime: 3 } },
    description: 'Fires a spread of pellets up close.',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    behavior: 'sniper',
    shape: 'humanoid', color: 0xff3df0, accent: 0xffffff, scale: 1, orientYaw: true,
    health: 28, speed: 2.2, contactDamage: 6, radius: 0.5, height: 1.5,
    xp: 4, currency: { min: 2, max: 4 }, weight: 3, tier: 3, unlockWave: 8,
    tags: ['ground', 'ranged', 'precision'], detectRange: 60,
    attack: { type: 'ranged', damage: 18, range: 50, cooldown: 3.0, preferredRange: 24,
      projectile: { speed: 60, color: 0xff3df0, shape: 'shard', scale: 1.1, radius: 0.18, lifetime: 4 } },
    description: 'Fires a fast, leading shot from long range. Stay mobile.',
  },
  {
    id: 'strafer',
    name: 'Strafer',
    behavior: 'strafer',
    shape: 'drone', color: 0x29e7ff, accent: 0xffffff, scale: 1, orientYaw: false,
    health: 26, speed: 5.0, contactDamage: 6, radius: 0.45, height: 0.9,
    flying: true, hoverHeight: 3.0,
    xp: 3, currency: { min: 1, max: 3 }, weight: 5, tier: 3, unlockWave: 7,
    tags: ['flying', 'ranged'], detectRange: 55,
    attack: { type: 'ranged', damage: 7, range: 26, cooldown: 1.3, preferredRange: 12,
      projectile: { speed: 34, color: 0x29e7ff, shape: 'orb', scale: 0.8, radius: 0.18, lifetime: 4 } },
    description: 'Circles you at mid-range, peppering shots.',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    behavior: 'sentry',
    shape: 'orb', color: 0x29e7ff, accent: 0xff3df0, scale: 1, orientYaw: false,
    health: 40, speed: 1.0, contactDamage: 6, radius: 0.5, height: 1.0,
    flying: true, hoverHeight: 2.5,
    xp: 3, currency: { min: 1, max: 3 }, weight: 4, tier: 3, unlockWave: 9,
    tags: ['flying', 'ranged', 'burst'], detectRange: 55,
    attack: { type: 'ranged', damage: 6, range: 30, cooldown: 2.4, preferredRange: 16,
      projectile: { speed: 38, color: 0x29e7ff, shape: 'orb', scale: 0.8, radius: 0.18, lifetime: 4 } },
    description: 'Stationary turret that fires triple bursts.',
  },
  {
    id: 'dodger',
    name: 'Phantom',
    behavior: 'dodger',
    shape: 'ghost', color: 0xff66cc, accent: 0xffffff, scale: 1, orientYaw: false,
    health: 32, speed: 5.0, contactDamage: 8, radius: 0.5, height: 1.2,
    flying: true, hoverHeight: 2.0,
    xp: 4, currency: { min: 1, max: 3 }, weight: 4, tier: 3, unlockWave: 10,
    tags: ['flying', 'ranged', 'evasive'], detectRange: 50,
    attack: { type: 'ranged', damage: 7, range: 22, cooldown: 1.6, preferredRange: 14,
      projectile: { speed: 36, color: 0xff3df0, shape: 'orb', scale: 0.8, radius: 0.18, lifetime: 4 } },
    description: 'Erratic dashes make it hard to track.',
  },
  {
    id: 'turret',
    name: 'Bunker',
    behavior: 'turret',
    shape: 'tank', color: 0x5577aa, accent: 0xff3df0, scale: 0.9, orientYaw: true,
    health: 70, speed: 0.5, contactDamage: 6, radius: 0.7, height: 1.2,
    armor: 6, xp: 4, currency: { min: 2, max: 4 }, weight: 3, tier: 3, unlockWave: 11,
    tags: ['ground', 'ranged', 'armored'], detectRange: 50,
    attack: { type: 'ranged', damage: 8, range: 30, cooldown: 1.1, preferredRange: 20,
      projectile: { speed: 32, color: 0xff3df0, shape: 'orb', scale: 1, radius: 0.22, lifetime: 4 } },
    description: 'A heavily armored emplacement. Flank or burst it.',
  },
  {
    id: 'orbiter',
    name: 'Orbiter',
    behavior: 'orbiter',
    shape: 'drone', color: 0x66ffaa, accent: 0xffffff, scale: 0.9, orientYaw: false,
    health: 24, speed: 5.0, contactDamage: 6, radius: 0.4, height: 0.8,
    flying: true, hoverHeight: 2.6,
    xp: 3, currency: { min: 1, max: 3 }, weight: 4, tier: 3, unlockWave: 10,
    tags: ['flying', 'ranged'], detectRange: 50,
    attack: { type: 'ranged', damage: 6, range: 24, cooldown: 1.4, preferredRange: 7,
      projectile: { speed: 30, color: 0x29e7ff, shape: 'orb', scale: 0.8, radius: 0.18, lifetime: 4 } },
    description: 'Orbits the player firing inward. Hard to shake.',
  },
  {
    id: 'cryomancer',
    name: 'Cryomancer',
    behavior: 'shooter',
    shape: 'humanoid', color: 0x9fe7ff, accent: 0xffffff, scale: 1, orientYaw: true,
    health: 38, speed: 3.0, contactDamage: 8, radius: 0.5, height: 1.4,
    xp: 4, currency: { min: 1, max: 3 }, weight: 3, tier: 3, unlockWave: 12,
    tags: ['ground', 'ranged', 'status'], detectRange: 55,
    attack: { type: 'ranged', damage: 7, range: 28, cooldown: 1.8, preferredRange: 12,
      projectile: { speed: 28, color: 0x9fe7ff, shape: 'orb', scale: 1, radius: 0.24, lifetime: 4 } },
    contactStatus: { chance: 0.4, type: StatusType.Slow, power: 1 },
    description: 'Frost bolts that chill and slow on hit.',
  },
  {
    id: 'pyromancer',
    name: 'Pyromancer',
    behavior: 'shooter',
    shape: 'humanoid', color: 0xff6633, accent: 0xffe066, scale: 1, orientYaw: true,
    health: 38, speed: 3.0, contactDamage: 8, radius: 0.5, height: 1.4,
    xp: 4, currency: { min: 1, max: 3 }, weight: 3, tier: 3, unlockWave: 12,
    tags: ['ground', 'ranged', 'status'], detectRange: 55,
    attack: { type: 'ranged', damage: 6, range: 26, cooldown: 1.5, preferredRange: 12,
      projectile: { speed: 26, color: 0xff6633, shape: 'orb', scale: 1, radius: 0.24, lifetime: 4 } },
    contactStatus: { chance: 0.4, type: StatusType.Burn, power: 1 },
    description: 'Hurls fire that ignites on hit.',
  },
]);
