// ============================================================================
// special.js — Support & elite-tier enemies: healers, shielders, summoners,
// tanks, and exotic threats that demand target prioritization.
// ============================================================================

import { EnemyRegistry } from '../EnemyRegistry.js';
import { StatusType, DamageType } from '../../ecs/components/Combat.js';

EnemyRegistry.registerMany([
  {
    id: 'healer',
    name: 'Mender',
    behavior: 'healer',
    shape: 'humanoid', color: 0x4fd07a, accent: 0xffffff, scale: 1, orientYaw: true,
    health: 40, speed: 3.0, contactDamage: 6, radius: 0.5, height: 1.4,
    xp: 5, currency: { min: 2, max: 4 }, weight: 2, tier: 3, unlockWave: 11,
    tags: ['ground', 'support'], detectRange: 50,
    description: 'Heals nearby allies. Kill it first.',
  },
  {
    id: 'shielder',
    name: 'Bulwark',
    behavior: 'shielder',
    shape: 'humanoid', color: 0x4aa3ff, accent: 0xffffff, scale: 1.1, orientYaw: true,
    health: 50, speed: 3.0, contactDamage: 8, radius: 0.55, height: 1.5,
    armor: 2, xp: 5, currency: { min: 2, max: 4 }, weight: 2, tier: 3, unlockWave: 12,
    tags: ['ground', 'support'], detectRange: 45,
    description: 'Grants armor to nearby enemies. Strip its protection.',
  },
  {
    id: 'summoner',
    name: 'Conjurer',
    behavior: 'summoner',
    shape: 'humanoid', color: 0xb266ff, accent: 0xff3df0, scale: 1.1, orientYaw: true,
    health: 60, speed: 2.6, contactDamage: 8, radius: 0.55, height: 1.5,
    xp: 6, currency: { min: 2, max: 5 }, weight: 2, tier: 4, unlockWave: 13,
    tags: ['ground', 'support', 'summoner'], detectRange: 50,
    description: 'Spawns swarmlings. Never leave it alive.',
  },
  {
    id: 'swarmLord',
    name: 'Hive Lord',
    behavior: 'swarmLord',
    shape: 'blob', color: 0xff66aa, accent: 0xffe066, scale: 1.6, orientYaw: false,
    health: 140, speed: 3.0, contactDamage: 14, radius: 0.9, height: 1.6,
    armor: 3, xp: 10, currency: { min: 4, max: 8 }, weight: 1, tier: 4, unlockWave: 14,
    tags: ['ground', 'support', 'summoner', 'elite'], detectRange: 55,
    description: 'A pulsing hive that drowns you in swarmlings and spread fire.',
    eliteHealthMult: 2.2,
  },
  {
    id: 'kamikaze',
    name: 'Martyr',
    behavior: 'kamikaze',
    shape: 'shard', color: 0xff3344, accent: 0xffe066, scale: 1, orientYaw: true,
    health: 20, speed: 9.0, contactDamage: 18, radius: 0.4, height: 1.0,
    xp: 3, currency: { min: 1, max: 2 }, weight: 3, tier: 3, unlockWave: 10,
    tags: ['ground', 'fast', 'suicide'], detectRange: 50,
    description: 'Sprints at you and explodes. One tap is enough.',
  },
  {
    id: 'tank',
    name: 'Juggernaut',
    behavior: 'tank',
    shape: 'tank', color: 0x8a5bff, accent: 0xff3df0, scale: 1.4, orientYaw: true,
    health: 220, speed: 2.2, contactDamage: 15, radius: 0.9, height: 1.6,
    armor: 10, shield: 60, xp: 12, currency: { min: 5, max: 10 }, weight: 1, tier: 4, unlockWave: 15,
    tags: ['ground', 'heavy', 'slam', 'armored'], detectRange: 40,
    description: 'A walking fortress with shields and a shockwave slam.',
  },
  {
    id: 'crystalShard',
    name: 'Crystal Sentinel',
    behavior: 'strafer',
    shape: 'crystal', color: 0x4fffd0, accent: 0xffffff, scale: 1.1, orientYaw: false,
    health: 50, speed: 4.4, contactDamage: 10, radius: 0.5, height: 1.2,
    armor: 4, xp: 5, currency: { min: 2, max: 4 }, weight: 3, tier: 4, unlockWave: 14,
    tags: ['ground', 'ranged', 'armored'], detectRange: 50,
    resistances: { energy: 0.4 },
    attack: { type: 'ranged', damage: 8, range: 24, cooldown: 1.5, preferredRange: 10,
      projectile: { speed: 34, color: 0x4fffd0, shape: 'shard', scale: 1, radius: 0.2, lifetime: 4 } },
    glowPulse: { base: 1, amplitude: 0.6, speed: 2 },
    description: 'Crystalline and energy-resistant. Strafes while shooting.',
  },
  {
    id: 'voidEye',
    name: 'Void Eye',
    behavior: 'orbiter',
    shape: 'orb', color: 0x8a5bff, accent: 0xff3df0, scale: 1.3, orientYaw: false,
    health: 80, speed: 4.0, contactDamage: 12, radius: 0.7, height: 1.2,
    xp: 7, currency: { min: 3, max: 6 }, weight: 2, tier: 4, unlockWave: 16,
    tags: ['flying', 'ranged', 'elite'], detectRange: 55,
    attack: { type: 'ranged', damage: 10, range: 30, cooldown: 1.2, preferredRange: 8,
      projectile: { speed: 32, color: 0x8a5bff, shape: 'orb', scale: 1.2, radius: 0.3, lifetime: 4 } },
    glowPulse: { base: 1, amplitude: 0.7, speed: 1.5 },
    description: 'A looming eye that orbits and barrages you.',
    eliteHealthMult: 1.8,
  },
  {
    id: 'mirror',
    name: 'Mirage',
    behavior: 'dodger',
    shape: 'ghost', color: 0xffffff, accent: 0x29e7ff, scale: 1, orientYaw: false,
    health: 36, speed: 6.0, contactDamage: 10, radius: 0.5, height: 1.3,
    flying: true, hoverHeight: 2.2,
    xp: 5, currency: { min: 2, max: 4 }, weight: 2, tier: 4, unlockWave: 15,
    tags: ['flying', 'evasive', 'ranged'], detectRange: 55,
    resistances: { kinetic: 0.5, energy: 0.2 },
    attack: { type: 'ranged', damage: 9, range: 24, cooldown: 1.4, preferredRange: 14,
      projectile: { speed: 40, color: 0xffffff, shape: 'orb', scale: 0.9, radius: 0.2, lifetime: 4 } },
    description: 'A reflective phantom that halves kinetic damage.',
  },
  {
    id: 'overseer',
    name: 'Overseer',
    behavior: 'shooter',
    shape: 'drone', color: 0xffb347, accent: 0xff3df0, scale: 1.2, orientYaw: false,
    health: 70, speed: 3.5, contactDamage: 10, radius: 0.6, height: 1.1,
    flying: true, hoverHeight: 4.0,
    xp: 7, currency: { min: 3, max: 6 }, weight: 2, tier: 4, unlockWave: 16,
    tags: ['flying', 'ranged', 'support'], detectRange: 60,
    attack: { type: 'ranged', damage: 9, range: 36, cooldown: 1.4, preferredRange: 18,
      projectile: { speed: 34, color: 0xffb347, shape: 'orb', scale: 1.1, radius: 0.26, lifetime: 5 } },
    description: 'High-altitude spotter firing long-range bolts.',
  },
  {
    id: 'leaper',
    name: 'Leaper',
    behavior: 'charger',
    shape: 'spider', color: 0xff66ff, accent: 0x222222, scale: 1.1, orientYaw: true,
    health: 48, speed: 5.0, contactDamage: 14, radius: 0.5, height: 0.9,
    xp: 4, currency: { min: 2, max: 4 }, weight: 3, tier: 3, unlockWave: 11,
    tags: ['ground', 'fast', 'charger'], detectRange: 50,
    description: 'A pouncing arachnid that closes gaps in bursts.',
  },
]);
