import { clamp, formatNumber } from '../core/math.js';

export class GameUI {
  constructor() {
    const q=id=>document.getElementById(id); this.title=q('title-screen');this.hud=q('hud');this.worldHud=q('world-hud');this.combatHud=q('combat-hud');this.upgradeScreen=q('upgrade-screen');this.pauseScreen=q('pause-screen');this.gameoverScreen=q('gameover-screen');this.upgradeCards=q('upgrade-cards');this.toast=q('toast');this.feed=q('event-feed');this.damageFlash=q('damage-flash');this.miniMap=q('mini-map');this.ctx=this.miniMap.getContext('2d');
    this.refs={directiveState:q('directive-state'),directiveText:q('directive-text'),missionBar:q('mission-progress-bar'),score:q('score-value'),combo:q('combo-value'),wave:q('wave-value'),enemies:q('enemy-count'),healthBar:q('health-bar'),shieldBar:q('shield-bar'),xpBar:q('xp-bar'),health:q('health-value'),shield:q('shield-value'),xp:q('xp-value'),level:q('level-value'),finalScore:q('final-score'),finalWave:q('final-wave'),finalKills:q('final-kills'),finalCombo:q('final-combo'),upgradeLevel:q('upgrade-level'),reticleDistance:q('reticle-distance'),dash:q('dash-ability'),pulse:q('pulse-ability'),overdrive:q('overdrive-ability')};
    this.game=null;this.toastTimer=0;this.feedEntries=[];this.bind();
  }
  bind() { document.getElementById('deploy-button').addEventListener('click',()=>{this.game?.audio.start();this.game?.start();});document.getElementById('pause-button').addEventListener('click',()=>this.game?.togglePause());document.getElementById('resume-button').addEventListener('click',()=>this.game?.resume());document.getElementById('restart-button').addEventListener('click',()=>{this.game?.audio.start();this.game?.start();}); }
  attach(game) { this.game=game; }
  hideLoading() { setTimeout(()=>document.getElementById('loading').classList.add('done'),420); }
  setMission(active,text,progress=0) { this.refs.directiveState.textContent=active?'LIVE':'STANDBY';this.refs.directiveState.style.color=active?'var(--cyan)':'var(--gold)';this.refs.directiveText.textContent=text;this.refs.missionBar.style.width=`${clamp(progress,0,1)*100}%`; }
  showGame() { this.title.classList.add('hidden');this.hud.classList.remove('hidden');this.worldHud.classList.remove('hidden');this.combatHud.classList.remove('hidden');this.upgradeScreen.classList.add('hidden');this.pauseScreen.classList.add('hidden');this.gameoverScreen.classList.add('hidden'); }
  showTitle() { this.title.classList.remove('hidden');this.hud.classList.add('hidden');this.worldHud.classList.add('hidden');this.combatHud.classList.add('hidden');this.upgradeScreen.classList.add('hidden');this.pauseScreen.classList.add('hidden');this.gameoverScreen.classList.add('hidden'); }
  showPause() { this.pauseScreen.classList.remove('hidden'); }
  hidePause() { this.pauseScreen.classList.add('hidden'); }
  showUpgrade(upgrades,level,choose) { this.upgradeScreen.classList.remove('hidden');this.refs.upgradeLevel.textContent=`LEVEL ${String(level).padStart(2,'0')}`;this.upgradeCards.innerHTML=''; upgrades.forEach((u,index)=>{const card=document.createElement('button');card.className='upgrade-card';card.innerHTML=`<span class="number">0${index+1}</span><span class="tag">${u.tag}</span><div class="upgrade-icon">${u.icon}</div><h3>${u.name}</h3><p>${u.text}</p>`;card.addEventListener('click',()=>choose(index));this.upgradeCards.appendChild(card);}); this.upgradeCards.querySelector('.upgrade-card')?.focus(); }
  hideUpgrade() { this.upgradeScreen.classList.add('hidden'); }
  showGameover(game) { this.gameoverScreen.classList.remove('hidden');this.refs.finalScore.textContent=formatNumber(game.score);this.refs.finalWave.textContent=String(game.wave).padStart(2,'0');this.refs.finalKills.textContent=String(game.player.kills).padStart(3,'0');this.refs.finalCombo.textContent=`x${game.player.bestCombo.toFixed(1)}`; }
  update(game) {
    const p=game.player,s=this.refs; s.score.textContent=formatNumber(game.score);s.combo.textContent=`x${p.combo.toFixed(1)} COMBO`;s.combo.style.color=p.combo>3?'var(--pink)':'var(--gold)';s.wave.textContent=String(game.wave).padStart(2,'0');s.enemies.innerHTML=`HOSTILES <b>${game.aliveEnemies()}</b>`;s.healthBar.style.width=`${clamp(p.health/p.maxHealth,0,1)*100}%`;s.shieldBar.style.width=`${clamp(p.shield/p.maxShield,0,1)*100}%`;s.xpBar.style.width=`${clamp(p.xp/p.xpToNext,0,1)*100}%`;s.health.textContent=`${Math.ceil(p.health)} / ${p.maxHealth}`;s.shield.textContent=`${Math.ceil(p.shield)} / ${p.maxShield}`;s.xp.textContent=`${Math.floor(p.xp/p.xpToNext*100)}%`;s.level.textContent=String(p.level).padStart(2,'0');
    this.setAbility(s.dash,p.dashCooldownTimer,p.stats.dashCooldown);this.setAbility(s.pulse,p.pulseCooldown,p.stats.pulseCooldown);s.overdrive.classList.toggle('locked',p.ultimate<100);s.overdrive.classList.toggle('ready',p.ultimate>=100);s.overdrive.querySelector('i').style.width=`${clamp(p.ultimate/100,0,1)*100}%`;
    const node=game.activeNode;const nodeProgress=node?node.charge:0;this.setMission(game.state==='playing',game.directive,game.waveProgress(nodeProgress));const target=game.aimPoint;const d=Math.hypot(target[0]-p.position[0],target[2]-p.position[2]);s.reticleDistance.textContent=`${Math.floor(d)}M`;
    this.drawMap(game);if(this.toastTimer>0){this.toastTimer-=game.lastDt;if(this.toastTimer<=0)this.toast.classList.remove('show');}
  }
  setAbility(element,cooldown,total) { element.classList.toggle('ready',cooldown<=0);element.classList.toggle('cooldown',cooldown>0);element.querySelector('i').style.width=`${clamp(1-cooldown/total,0,1)*100}%`; }
  addFeed(message,tone='') { this.feedEntries.unshift({message,tone,age:0});this.feedEntries=this.feedEntries.slice(0,5);this.feed.innerHTML=this.feedEntries.map(entry=>`<div class="${entry.tone}">// ${entry.message}</div>`).join(''); }
  toastMessage(message) { this.toast.textContent=message;this.toast.classList.remove('show');void this.toast.offsetWidth;this.toast.classList.add('show');this.toastTimer=2.4; }
  flashDamage() { this.damageFlash.classList.remove('hit');void this.damageFlash.offsetWidth;this.damageFlash.classList.add('hit'); }
  drawMap(game) { const ctx=this.ctx,w=this.miniMap.width,h=this.miniMap.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(5,16,29,.7)';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(104,215,242,.12)';ctx.lineWidth=1;for(let i=1;i<5;i++){const a=i/5*w;ctx.beginPath();ctx.moveTo(a,0);ctx.lineTo(a,h);ctx.moveTo(0,a);ctx.lineTo(w,a);ctx.stroke();}ctx.strokeStyle='rgba(119,232,255,.3)';ctx.strokeRect(12,12,w-24,h-24);const map=(pos)=>[w/2+pos[0]/90*(w-24),h/2+pos[2]/90*(h-24)];for(const node of game.nodes){const [x,y]=map(node.position);ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle=node.completed?'#5fffb4':node.active?'#b084ff':'#456478';ctx.fill();if(node.active){ctx.strokeStyle='rgba(176,132,255,.65)';ctx.beginPath();ctx.arc(x,y,8+Math.sin(game.time*4)*2,0,Math.PI*2);ctx.stroke();}}for(const enemy of game.enemies){if(enemy.dead)continue;const [x,y]=map(enemy.position);ctx.fillStyle=enemy.profile.boss?'#ff5fa2':'#ff6688';ctx.fillRect(x-1.5,y-1.5,3,3);}const [px,py]=map(game.player.position);ctx.save();ctx.translate(px,py);ctx.rotate(game.player.rotation);ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(3.5,4);ctx.lineTo(-3.5,4);ctx.closePath();ctx.fillStyle='#c0f8ff';ctx.shadowBlur=8;ctx.shadowColor='#77e8ff';ctx.fill();ctx.restore(); }
}
