// ============================================================================
// items.js — Passive item definitions. Stat-based stackers and a handful of
// event-reactive items (onHit/onKill/onDamage). Items are bought in the shop
// or dropped rarely, and stack up to maxStacks.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

ItemRegistry.registerMany([
  { id: 'powerCore', name: 'Power Core', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 120, weight: 12,
    description: '+15% damage per stack', tags: ['offense'], icon: { shape: 'gem', color: 0xff5544 },
    stat: (s) => ({ damageMult: 1 + 0.15 * s }) },
  { id: 'ironPlate', name: 'Iron Plate', rarity: ItemRarity.Common, maxStacks: 5, price: 70, weight: 14,
    description: '+3 armor per stack', tags: ['defense'], icon: { shape: 'square', color: 0x9fb3d6 },
    stat: (s) => ({ armor: 3 * s }) },
  { id: 'vitalCrystal', name: 'Vital Crystal', rarity: ItemRarity.Common, maxStacks: 5, price: 80, weight: 14,
    description: '+20 max HP per stack', tags: ['defense'], icon: { shape: 'gem', color: 0x4fd07a },
    stat: (s) => ({ maxHP: 20 * s }) },
  { id: 'swiftBoots', name: 'Swift Boots', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 110, weight: 12,
    description: '+6% move speed per stack', tags: ['mobility'], icon: { shape: 'boot', color: 0x4fffd0 },
    stat: (s) => ({ moveMult: 1 + 0.06 * s }) },
  { id: 'luckyCharm', name: 'Lucky Charm', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 100, weight: 12,
    description: '+4% crit chance per stack', tags: ['offense'], icon: { shape: 'star', color: 0xffb347 },
    stat: (s) => ({ critChance: 0.04 * s }) },
  { id: 'vampFang', name: 'Vampiric Fang', rarity: ItemRarity.Rare, maxStacks: 4, price: 180, weight: 8,
    description: '+1.5% lifesteal per stack', tags: ['offense', 'sustain'], icon: { shape: 'drop', color: 0xff3df0 },
    stat: (s) => ({ lifesteal: 0.015 * s }) },
  { id: 'overclock', name: 'Overclock Chip', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 11,
    description: '+8% fire rate per stack', tags: ['offense'], icon: { shape: 'chip', color: 0x29e7ff },
    stat: (s) => ({ fireRateMult: 1 + 0.08 * s }) },
  { id: 'blastTip', name: 'Explosive Tip', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7,
    description: '+12% AoE per stack', tags: ['offense'], icon: { shape: 'blast', color: 0xff7733 },
    stat: (s) => ({ aoeMult: 1 + 0.12 * s }) },
  { id: 'pierceRound', name: 'Piercing Round', rarity: ItemRarity.Rare, maxStacks: 2, price: 220, weight: 6,
    description: '+1 pierce per stack', tags: ['offense'], icon: { shape: 'arrow', color: 0x4aa3ff },
    stat: (s) => ({ pierce: 1 * s }) },
  { id: 'greedCoin', name: 'Greed Coin', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 10,
    description: '+20% currency per stack', tags: ['economy'], icon: { shape: 'coin', color: 0xffb347 },
    stat: (s) => ({ currencyMult: 1 + 0.20 * s }) },
  { id: 'scholarLens', name: 'Scholar Lens', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 10,
    description: '+15% XP per stack', tags: ['economy'], icon: { shape: 'lens', color: 0x9fe7ff },
    stat: (s) => ({ xpMult: 1 + 0.15 * s }) },
  { id: 'thornsSpike', name: 'Thorns Spike', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 110, weight: 10,
    description: '+6 thorns damage per stack', tags: ['defense'], icon: { shape: 'cactus', color: 0x4fd07a },
    stat: (s) => ({ thorns: 6 * s }) },
  { id: 'regrowthSeed', name: 'Regrowth Seed', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10,
    description: '+1.2 HP/sec regen per stack', tags: ['sustain'], icon: { shape: 'leaf', color: 0x66ff88 },
    stat: (s) => ({ regen: 1.2 * s }) },
  { id: 'reflexModule', name: 'Reflex Module', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7,
    description: '-10% dash cooldown per stack', tags: ['mobility'], icon: { shape: 'wind', color: 0x9fe7ff },
    stat: (s) => ({ dashCDMult: 1 - 0.10 * s }) },
  { id: 'shieldBattery', name: 'Shield Battery', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10,
    description: '+18 shield per stack', tags: ['defense'], icon: { shape: 'shield', color: 0x29e7ff },
    stat: (s) => ({ shield: 18 * s }) },
  { id: 'resilientPlating', name: 'Resilient Plating', rarity: ItemRarity.Rare, maxStacks: 4, price: 210, weight: 7,
    description: '-4% damage taken per stack', tags: ['defense'], icon: { shape: 'shield', color: 0x4aa3ff },
    stat: (s) => ({ damageReduction: 0.04 * s }) },
  { id: 'velocityJet', name: 'Velocity Jet', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7,
    description: '+12% projectile speed per stack', tags: ['offense'], icon: { shape: 'arrow', color: 0xff66aa },
    stat: (s) => ({ projectileSpeedMult: 1 + 0.12 * s }) },
  { id: 'tightGrip', name: 'Tight Grip', rarity: ItemRarity.Rare, maxStacks: 3, price: 190, weight: 7,
    description: '-15% spread per stack', tags: ['offense'], icon: { shape: 'target', color: 0xffb347 },
    stat: (s) => ({ spreadMult: 1 - 0.15 * s }) },
  { id: 'speedLoader', name: 'Speed Loader', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 120, weight: 10,
    description: '-12% reload time per stack', tags: ['offense'], icon: { shape: 'clock', color: 0x9fe7ff },
    stat: (s) => ({ reloadMult: 1 - 0.12 * s }) },
  { id: 'extendedMag', name: 'Extended Mag', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 120, weight: 10,
    description: '+20% magazine size per stack', tags: ['offense'], icon: { shape: 'mag', color: 0xffaa44 },
    stat: (s) => ({ magMult: 1 + 0.20 * s }) },
  { id: 'statusAmplifier', name: 'Status Amplifier', rarity: ItemRarity.Epic, maxStacks: 3, price: 300, weight: 5,
    description: '+25% status power per stack', tags: ['offense', 'status'], icon: { shape: 'flame', color: 0xff6633 },
    stat: (s) => ({ statusPowerMult: 1 + 0.25 * s }) },
  { id: 'contagionVial', name: 'Contagion Vial', rarity: ItemRarity.Epic, maxStacks: 3, price: 300, weight: 5,
    description: '+20% status chance per stack', tags: ['offense', 'status'], icon: { shape: 'vial', color: 0x66ff88 },
    stat: (s) => ({ statusChanceMult: 1 + 0.20 * s }) },
  { id: 'longshotScope', name: 'Longshot Scope', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7,
    description: '+12% range per stack', tags: ['offense'], icon: { shape: 'scope', color: 0x29e7ff },
    stat: (s) => ({ rangeMult: 1 + 0.12 * s }) },
  { id: 'headhunterMark', name: 'Headhunter Mark', rarity: ItemRarity.Epic, maxStacks: 3, price: 320, weight: 5,
    description: '+0.35 headshot multiplier per stack', tags: ['offense', 'precision'], icon: { shape: 'target', color: 0xff3df0 },
    stat: (s) => ({ headshotMult: 0.35 * s }) },
  { id: 'armorPenBlade', name: 'Armor Pen Blade', rarity: ItemRarity.Epic, maxStacks: 3, price: 320, weight: 5,
    description: '+4 armor penetration per stack', tags: ['offense'], icon: { shape: 'blade', color: 0xb266ff },
    stat: (s) => ({ armorPen: 4 * s }) },
  // ---- Event-reactive items ----
  { id: 'phoenixFeather', name: 'Phoenix Feather', rarity: ItemRarity.Legendary, maxStacks: 1, price: 500, weight: 2,
    description: 'Cheat death once per wave: survive a lethal hit at 1 HP.', tags: ['defense', 'special'],
    icon: { shape: 'feather', color: 0xff7733 }, stat: () => ({}), onDamage: null },
  { id: 'berserkerMark', name: 'Berserker Mark', rarity: ItemRarity.Epic, maxStacks: 1, price: 350, weight: 5,
    description: '+40% damage while below 40% HP.', tags: ['offense', 'special'],
    icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), onUpdate: null },
  { id: 'giantkillerBlade', name: 'Giantkiller Blade', rarity: ItemRarity.Legendary, maxStacks: 1, price: 480, weight: 2,
    description: '+60% damage vs elites and bosses.', tags: ['offense', 'special'],
    icon: { shape: 'blade', color: 0xffb347 }, stat: () => ({}), onHit: null },
  { id: 'staticField', name: 'Static Field', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6,
    description: 'Hits have a 25% chance to shock (chain-ready).', tags: ['offense', 'status'],
    icon: { shape: 'bolt', color: 0x29e7ff }, stat: () => ({ statusChanceMult: 1 }), onHit: null },
  { id: 'infernoCore', name: 'Inferno Core', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6,
    description: 'Hits have a 25% chance to ignite (burn).', tags: ['offense', 'status'],
    icon: { shape: 'flame', color: 0xff6633 }, stat: () => ({}), onHit: null },
  { id: 'cryoLens', name: 'Cryo Lens', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6,
    description: 'Hits have a 25% chance to chill (slow).', tags: ['offense', 'status'],
    icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onHit: null },
  { id: 'chainReactor', name: 'Chain Reactor', rarity: ItemRarity.Epic, maxStacks: 1, price: 340, weight: 5,
    description: 'Kills have a 30% chance to chain lightning to nearby enemies.', tags: ['offense', 'special'],
    icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onKill: null },
  { id: 'vengefulSpirit', name: 'Vengeful Spirit', rarity: ItemRarity.Epic, maxStacks: 1, price: 330, weight: 5,
    description: 'Taking damage grants +30% damage for 3 seconds.', tags: ['offense', 'defense', 'special'],
    icon: { shape: 'ghost', color: 0xb266ff }, stat: () => ({}), onDamage: null },
  // ---- Cursed items (powerful with a downside) ----
  { id: 'glassCannonCore', name: 'Glass Cannon Core', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4,
    description: '+40% damage, but -25% max HP.', tags: ['offense', 'curse'],
    icon: { shape: 'cannon', color: 0xff3df0 }, stat: () => ({ damageMult: 1.4, maxHP: -25 }) },
  { id: 'cursedBlood', name: 'Cursed Blood', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4,
    description: '+60% damage, but you take +50% damage.', tags: ['offense', 'curse'],
    icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ damageMult: 1.6, damageReduction: -0.5 }) },
  { id: 'adrenalGland', name: 'Adrenal Gland', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4,
    description: '+25% fire rate, but -15% max HP.', tags: ['offense', 'curse'],
    icon: { shape: 'gland', color: 0xff3df0 }, stat: () => ({ fireRateMult: 1.25, maxHP: -15 }) },
  { id: 'heartOfGold', name: 'Heart of Gold', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4,
    description: '+100% currency, but -20% damage.', tags: ['economy', 'curse'],
    icon: { shape: 'heart', color: 0xffb347 }, stat: () => ({ currencyMult: 2, damageMult: 0.8 }) },
]);
