// ============================================================================
// items2.js — Additional passive items: more stackers, event-reactives,
// and curses. Broadens shop variety and build expression.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

ItemRegistry.registerMany([
  { id: 'titanPlating', name: 'Titan Plating', rarity: ItemRarity.Epic, maxStacks: 2, price: 360, weight: 5, tags: ['defense'],
    description: '+8 armor and +30 max HP per stack.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: (s) => ({ armor: 8 * s, maxHP: 30 * s }) },
  { id: 'emberCore', name: 'Ember Core', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense', 'status'],
    description: '+15% burn status power per stack.', icon: { shape: 'flame', color: 0xff6633 }, stat: (s) => ({ statusPowerMult: 1 + 0.15 * s }) },
  { id: 'frostCore', name: 'Frost Core', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense', 'status'],
    description: '+15% slow/freeze power per stack.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: (s) => ({ statusPowerMult: 1 + 0.15 * s }) },
  { id: 'voltCore', name: 'Volt Core', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense', 'status'],
    description: '+15% shock power per stack.', icon: { shape: 'bolt', color: 0xffe066 }, stat: (s) => ({ statusPowerMult: 1 + 0.15 * s }) },
  { id: 'executionersAx', name: "Executioner's Axe", rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: 'Kills below 40% HP deal +50% damage for 2s.', icon: { shape: 'axe', color: 0xff3df0 }, stat: () => ({}), onKill: null },
  { id: 'marauderMap', name: "Marauder's Map", rarity: ItemRarity.Legendary, maxStacks: 1, price: 500, weight: 2, tags: ['economy', 'special'],
    description: '+50% currency and reveals all pickups.', icon: { shape: 'map', color: 0xffb347 }, stat: () => ({ currencyMult: 1.5 }) },
  { id: 'aegisMatrix', name: 'Aegis Matrix', rarity: ItemRarity.Legendary, maxStacks: 1, price: 520, weight: 2, tags: ['defense', 'special'],
    description: 'Shields absorb 20% more and regen 100% faster.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 30 }) },
  { id: 'bloodPact', name: 'Blood Pact', rarity: ItemRarity.Epic, maxStacks: 1, price: 340, weight: 5, tags: ['offense', 'sustain', 'special'],
    description: '+30% damage and +5% lifesteal, but -1 HP per second.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ damageMult: 1.3, lifesteal: 0.05, regen: -1 }) },
  { id: 'chronoDial', name: 'Chrono Dial', rarity: ItemRarity.Legendary, maxStacks: 1, price: 540, weight: 2, tags: ['mobility', 'special'],
    description: '-20% dash cooldown and dashing slows nearby enemies.', icon: { shape: 'clock', color: 0x29e7ff }, stat: () => ({ dashCDMult: 0.8 }) },
  { id: 'pyromaniac', name: 'Pyromaniac', rarity: ItemRarity.Epic, maxStacks: 1, price: 360, weight: 5, tags: ['offense', 'status', 'special'],
    description: 'Burning enemies take +30% damage.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({}), onHit: null },
  { id: 'cryomancer', name: 'Cryomancer', rarity: ItemRarity.Epic, maxStacks: 1, price: 360, weight: 5, tags: ['offense', 'status', 'special'],
    description: 'Frozen enemies take +30% damage.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onHit: null },
  { id: 'conducter', name: 'Conductor', rarity: ItemRarity.Epic, maxStacks: 1, price: 360, weight: 5, tags: ['offense', 'status', 'special'],
    description: 'Shocked enemies take +30% damage.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onHit: null },
  { id: 'berserkerBelt', name: 'Berserker Belt', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: '+40% damage and +20% move speed below 30% HP.', icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), onUpdate: null },
  { id: 'luckyCoin', name: 'Lucky Coin', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10, tags: ['economy'],
    description: '+10% currency and +5% crit chance per stack.', icon: { shape: 'coin', color: 0xffb347 }, stat: (s) => ({ currencyMult: 1 + 0.1 * s, critChance: 0.05 * s }) },
  { id: 'twinShot', name: 'Twin Shot', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: 'Hits have a 20% chance to fire a second shot.', icon: { shape: 'arrow', color: 0x29e7ff }, stat: () => ({}), onHit: null },
  { id: 'phasing', name: 'Phasing', rarity: ItemRarity.Legendary, maxStacks: 1, price: 540, weight: 2, tags: ['mobility', 'special'],
    description: 'Dashing grants 1s of invulnerability.', icon: { shape: 'ghost', color: 0x8a5bff }, stat: () => ({}), onUpdate: null },
  { id: 'vampiricBlade', name: 'Vampiric Blade', rarity: ItemRarity.Epic, maxStacks: 1, price: 360, weight: 5, tags: ['offense', 'sustain', 'special'],
    description: 'Melee hits heal for 15% of damage.', icon: { shape: 'blade', color: 0xff3df0 }, stat: () => ({}), onHit: null },
  { id: 'munitionsBelt', name: 'Munitions Belt', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 10, tags: ['offense'],
    description: '+25% magazine and +10% reserve per stack.', icon: { shape: 'mag', color: 0xffaa44 }, stat: (s) => ({ magMult: 1 + 0.25 * s }) },
  { id: 'shockAbsorber', name: 'Shock Absorber', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['defense'],
    description: '-5% explosive damage taken per stack.', icon: { shape: 'shield', color: 0x9fb3d6 }, stat: () => ({ damageReduction: 0.0 }) },
  { id: 'quickdraw', name: 'Quickdraw', rarity: ItemRarity.Rare, maxStacks: 2, price: 200, weight: 7, tags: ['offense', 'mobility'],
    description: '+15% fire rate for 2s after swapping weapons.', icon: { shape: 'lightning', color: 0x29e7ff }, stat: () => ({}), onUpdate: null },
  { id: 'goliath', name: 'Goliath', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense', 'curse'],
    description: '+80 max HP and +5 armor, but -15% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 80, armor: 5, moveMult: 0.85 }) },
  { id: 'starved', name: 'Starved', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'],
    description: '+50% damage, but you cannot heal from pickups.', icon: { shape: 'skull', color: 0xff3df0 }, stat: () => ({ damageMult: 1.5 }) },
  { id: 'fragile', name: 'Fragile', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'],
    description: '+35% fire rate, but you take +40% damage.', icon: { shape: 'glass', color: 0xff3df0 }, stat: () => ({ fireRateMult: 1.35, damageReduction: -0.4 }) },
  { id: 'reckless', name: 'Reckless', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'],
    description: '+70% damage, but -40% max HP.', icon: { shape: 'fire', color: 0xff3df0 }, stat: () => ({ damageMult: 1.7, maxHP: -40 }) },
]);
