// ============================================================================
// items4.js — More items: tactical, defensive, and capstone passives.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

ItemRegistry.registerMany([
  { id: 'adaptive', name: 'Adaptive Plating', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense', 'special'],
    description: 'Take 20% less damage from the last damage type for 3s.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ damageReduction: 0.05 }) },
  { id: 'tempestCore', name: 'Tempest Core', rarity: ItemRarity.Legendary, maxStacks: 1, price: 560, weight: 2, tags: ['offense', 'status', 'special'],
    description: 'Shocked enemies chain lightning to 2 more foes.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusChanceMult: 1.3 }), onHit: null },
  { id: 'rooted', name: 'Rooted', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['defense', 'special'],
    description: 'While stationary, take 25% less damage and regen +2 HP/s.', icon: { shape: 'tree', color: 0x4fd07a }, stat: () => ({}), onUpdate: null },
  { id: 'hyperMag', name: 'Hyper Mag', rarity: ItemRarity.Epic, maxStacks: 2, price: 380, weight: 5, tags: ['offense'],
    description: '+35% magazine size per stack and -8% reload.', icon: { shape: 'mag', color: 0xffaa44 }, stat: (s) => ({ magMult: 1 + 0.35 * s, reloadMult: 1 - 0.08 * s }) },
  { id: 'piercer', name: 'Piercer', rarity: ItemRarity.Epic, maxStacks: 2, price: 380, weight: 5, tags: ['offense'],
    description: '+1 pierce and +5% damage per stack.', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: (s) => ({ pierce: s, damageMult: 1 + 0.05 * s }) },
  { id: 'soulHarvest', name: 'Soul Harvest', rarity: ItemRarity.Legendary, maxStacks: 1, price: 580, weight: 2, tags: ['sustain', 'offense', 'special'],
    description: 'Kills permanently grant +0.5% damage (caps at +50%).', icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), onKill: null },
  { id: 'overpenCore', name: 'Overpen Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: 'Pierced enemies take +20% damage from all sources.', icon: { shape: 'arrow', color: 0x29e7ff }, stat: () => ({ pierce: 1 }) },
  { id: 'emberHeart', name: 'Ember Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 580, weight: 2, tags: ['offense', 'status', 'sustain', 'special'],
    description: 'Burning enemies grant you +1 HP/s regen.', icon: { shape: 'heart', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.3 }), onUpdate: null },
  { id: 'frostHeart', name: 'Frost Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 580, weight: 2, tags: ['offense', 'status', 'defense', 'special'],
    description: 'Frozen enemies grant you +10% move speed.', icon: { shape: 'heart', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.3 }), onUpdate: null },
  { id: 'glassEye', name: 'Glass Eye', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'precision', 'special'],
    description: '+20% crit chance but -15% damage.', icon: { shape: 'eye', color: 0xff3df0 }, stat: () => ({ critChance: 0.2, damageMult: 0.85 }) },
  { id: 'munitions2', name: 'Bandolier', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'special'],
    description: 'Picking up ammo also refills 10% of all magazines.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), onUpdate: null },
  { id: 'combatStim', name: 'Combat Stim', rarity: ItemRarity.Rare, maxStacks: 2, price: 220, weight: 7, tags: ['offense', 'mobility'],
    description: '+10% fire rate and +5% move speed per stack.', icon: { shape: 'syringe', color: 0xff5544 }, stat: (s) => ({ fireRateMult: 1 + 0.1 * s, moveMult: 1 + 0.05 * s }) },
  { id: 'ironWill2', name: 'Iron Will', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense', 'special'],
    description: 'Below 25% HP, take 40% less damage and regen 4 HP/s.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({}), onUpdate: null },
  { id: 'keystone', name: 'Keystone', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'special'],
    description: 'Every 5th shot deals +200% damage.', icon: { shape: 'star', color: 0xffe066 }, stat: () => ({}), onUpdate: null },
  { id: 'resonance', name: 'Resonance', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'special'],
    description: 'Status effects on an enemy spread to nearby enemies on death.', icon: { shape: 'ring', color: 0x8a5bff }, stat: () => ({ statusPowerMult: 1.1 }), onKill: null },
  { id: 'twinSoul', name: 'Twin Soul', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['sustain', 'special'],
    description: 'Lifesteal is doubled and you start each wave with +20 HP.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({}), onUpdate: null },
  { id: 'overcharge2', name: 'Capacitor', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense'],
    description: '+6% damage and +4% fire rate per stack.', icon: { shape: 'coil', color: 0x29e7ff }, stat: (s) => ({ damageMult: 1 + 0.06 * s, fireRateMult: 1 + 0.04 * s }) },
  { id: 'goliath2', name: 'Monolith', rarity: ItemRarity.Legendary, maxStacks: 1, price: 560, weight: 2, tags: ['defense'],
    description: '+120 max HP, +8 armor, -20% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 120, armor: 8, moveMult: 0.8 }) },
  { id: 'swiftArrow', name: 'Swift Arrow', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense'],
    description: '+10% projectile speed and +5% range per stack.', icon: { shape: 'arrow', color: 0x4fffd0 }, stat: (s) => ({ projectileSpeedMult: 1 + 0.1 * s, rangeMult: 1 + 0.05 * s }) },
  { id: 'blastAmplifier', name: 'Blast Amplifier', rarity: ItemRarity.Epic, maxStacks: 2, price: 380, weight: 5, tags: ['offense', 'aoe'],
    description: '+25% AoE and +15% explosive damage per stack.', icon: { shape: 'blast', color: 0xff7733 }, stat: (s) => ({ aoeMult: 1 + 0.25 * s }) },
  { id: 'vitalSpark', name: 'Vital Spark', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['sustain'],
    description: 'Healing is 30% more effective and regen +2 HP/s.', icon: { shape: 'spark', color: 0x4fd07a }, stat: () => ({ regen: 2 }) },
  { id: 'marked', name: 'Marked for Death', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'],
    description: 'Marked enemies take +40% damage.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.1 }), onHit: null },
  { id: 'juggernaut2', name: 'Bulwark Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 420, weight: 4, tags: ['defense'],
    description: '+60 max HP, +5 armor, +20 shield.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ maxHP: 60, armor: 5, shield: 20 }) },
  { id: 'pyroClasm', name: 'Pyroclasm', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'status', 'curse'],
    description: '+80% burn power, but you take burn damage too.', icon: { shape: 'flame', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.8 }) },
  { id: 'gluttony', name: 'Gluttony', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['sustain', 'curse'],
    description: '+50% lifesteal, but -50% healing from pickups.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.5 }) },
  { id: 'reckless2', name: 'Reckless Aim', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'],
    description: '+60% crit damage, but -50% crit chance.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ critMult: 0.6, critChance: -0.5 }) },
]);
