// ============================================================================
// items8.js — A large batch of additional items: more stackers, event
// reactives, and themed sets to deepen shop variety further.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

const I = (def) => ItemRegistry.register(def);

// Common themed stackers
I({ id: 'brassKnuckle', name: 'Brass Knuckle', rarity: ItemRarity.Common, maxStacks: 4, price: 70, weight: 12, tags: ['offense', 'melee'], description: '+8% melee damage per stack', icon: { shape: 'fist', color: 0xffaa44 }, stat: (s) => ({ damageMult: 1 + 0.08 * s }) });
I({ id: 'runningShoe', name: 'Running Shoe', rarity: ItemRarity.Common, maxStacks: 5, price: 70, weight: 12, tags: ['mobility'], description: '+4% move speed per stack', icon: { shape: 'boot', color: 0x4fffd0 }, stat: (s) => ({ moveMult: 1 + 0.04 * s }) });
I({ id: 'luckyRabbit', name: 'Lucky Rabbit', rarity: ItemRarity.Common, maxStacks: 4, price: 80, weight: 10, tags: ['offense', 'precision'], description: '+3% crit chance per stack', icon: { shape: 'star', color: 0xffb347 }, stat: (s) => ({ critChance: 0.03 * s }) });
I({ id: 'bandage', name: 'Bandage', rarity: ItemRarity.Common, maxStacks: 5, price: 70, weight: 12, tags: ['sustain'], description: '+0.5 HP/s regen per stack', icon: { shape: 'cross', color: 0x4fd07a }, stat: (s) => ({ regen: 0.5 * s }) });
I({ id: 'battery', name: 'Battery', rarity: ItemRarity.Common, maxStacks: 5, price: 70, weight: 12, tags: ['defense'], description: '+10 shield per stack', icon: { shape: 'cell', color: 0x29e7ff }, stat: (s) => ({ shield: 10 * s }) });
I({ id: 'wrench', name: 'Wrench', rarity: ItemRarity.Common, maxStacks: 4, price: 70, weight: 12, tags: ['offense'], description: '-5% reload per stack', icon: { shape: 'wrench', color: 0x9fb3d6 }, stat: (s) => ({ reloadMult: 1 - 0.05 * s }) });
I({ id: 'scope2', name: 'Scope', rarity: ItemRarity.Common, maxStacks: 4, price: 70, weight: 12, tags: ['offense', 'precision'], description: '-5% spread per stack', icon: { shape: 'lens', color: 0x9fe7ff }, stat: (s) => ({ spreadMult: 1 - 0.05 * s }) });
I({ id: 'extendedMag2', name: 'Extended Mag', rarity: ItemRarity.Common, maxStacks: 4, price: 70, weight: 12, tags: ['offense'], description: '+10% magazine per stack', icon: { shape: 'mag', color: 0xffaa44 }, stat: (s) => ({ magMult: 1 + 0.1 * s }) });

// Uncommon themed stackers
I({ id: 'combatBoot', name: 'Combat Boot', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 110, weight: 11, tags: ['mobility'], description: '+7% move speed per stack', icon: { shape: 'boot', color: 0x4fffd0 }, stat: (s) => ({ moveMult: 1 + 0.07 * s }) });
I({ id: 'luckyCoin2', name: 'Lucky Coin', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10, tags: ['economy', 'offense'], description: '+10% currency and +3% crit per stack', icon: { shape: 'coin', color: 0xffb347 }, stat: (s) => ({ currencyMult: 1 + 0.1 * s, critChance: 0.03 * s }) });
I({ id: 'ironPlate2', name: 'Iron Plate', rarity: ItemRarity.Uncommon, maxStacks: 5, price: 110, weight: 11, tags: ['defense'], description: '+3 armor per stack', icon: { shape: 'square', color: 0x9fb3d6 }, stat: (s) => ({ armor: 3 * s }) });
I({ id: 'vitalCrystal2', name: 'Vital Crystal', rarity: ItemRarity.Uncommon, maxStacks: 5, price: 110, weight: 11, tags: ['defense'], description: '+18 max HP per stack', icon: { shape: 'gem', color: 0x4fd07a }, stat: (s) => ({ maxHP: 18 * s }) });
I({ id: 'swiftBoot2', name: 'Swift Boot', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 110, weight: 11, tags: ['mobility'], description: '+6% move speed per stack', icon: { shape: 'boot', color: 0x4fffd0 }, stat: (s) => ({ moveMult: 1 + 0.06 * s }) });
I({ id: 'overclock2', name: 'Overclock Chip', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10, tags: ['offense'], description: '+8% fire rate per stack', icon: { shape: 'chip', color: 0x29e7ff }, stat: (s) => ({ fireRateMult: 1 + 0.08 * s }) });
I({ id: 'blastTip2', name: 'Explosive Tip', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['offense', 'aoe'], description: '+10% AoE per stack', icon: { shape: 'blast', color: 0xff7733 }, stat: (s) => ({ aoeMult: 1 + 0.1 * s }) });
I({ id: 'pierceRound2', name: 'Piercing Round', rarity: ItemRarity.Uncommon, maxStacks: 2, price: 140, weight: 8, tags: ['offense'], description: '+1 pierce per stack', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: (s) => ({ pierce: s }) });
I({ id: 'greedCoin2', name: 'Greed Coin', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['economy'], description: '+18% currency per stack', icon: { shape: 'coin', color: 0xffb347 }, stat: (s) => ({ currencyMult: 1 + 0.18 * s }) });
I({ id: 'scholarLens2', name: 'Scholar Lens', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['economy'], description: '+15% XP per stack', icon: { shape: 'lens', color: 0x9fe7ff }, stat: (s) => ({ xpMult: 1 + 0.15 * s }) });
I({ id: 'thornsSpike2', name: 'Thorns Spike', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 110, weight: 10, tags: ['defense'], description: '+5 thorns per stack', icon: { shape: 'cactus', color: 0x4fd07a }, stat: (s) => ({ thorns: 5 * s }) });
I({ id: 'regrowthSeed2', name: 'Regrowth Seed', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10, tags: ['sustain'], description: '+1 HP/s regen per stack', icon: { shape: 'leaf', color: 0x66ff88 }, stat: (s) => ({ regen: 1 * s }) });
I({ id: 'reflexModule2', name: 'Reflex Module', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 140, weight: 8, tags: ['mobility'], description: '-8% dash cooldown per stack', icon: { shape: 'wind', color: 0x9fe7ff }, stat: (s) => ({ dashCDMult: 1 - 0.08 * s }) });
I({ id: 'shieldBattery2', name: 'Shield Battery', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 120, weight: 10, tags: ['defense'], description: '+16 shield per stack', icon: { shape: 'shield', color: 0x29e7ff }, stat: (s) => ({ shield: 16 * s }) });
I({ id: 'resilientPlating2', name: 'Resilient Plating', rarity: ItemRarity.Uncommon, maxStacks: 4, price: 140, weight: 8, tags: ['defense'], description: '-4% damage taken per stack', icon: { shape: 'shield', color: 0x4aa3ff }, stat: (s) => ({ damageReduction: 0.04 * s }) });
I({ id: 'velocityJet2', name: 'Velocity Jet', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['offense'], description: '+10% projectile speed per stack', icon: { shape: 'arrow', color: 0xff66aa }, stat: (s) => ({ projectileSpeedMult: 1 + 0.1 * s }) });
I({ id: 'tightGrip2', name: 'Tight Grip', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['offense'], description: '-12% spread per stack', icon: { shape: 'target', color: 0xffb347 }, stat: (s) => ({ spreadMult: 1 - 0.12 * s }) });
I({ id: 'speedLoader2', name: 'Speed Loader', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 120, weight: 10, tags: ['offense'], description: '-10% reload per stack', icon: { shape: 'clock', color: 0x9fe7ff }, stat: (s) => ({ reloadMult: 1 - 0.1 * s }) });
I({ id: 'extendedMag3', name: 'Extended Mag', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 120, weight: 10, tags: ['offense'], description: '+18% magazine per stack', icon: { shape: 'mag', color: 0xffaa44 }, stat: (s) => ({ magMult: 1 + 0.18 * s }) });
I({ id: 'statusAmplifier2', name: 'Status Amplifier', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 140, weight: 8, tags: ['offense', 'status'], description: '+15% status power per stack', icon: { shape: 'flame', color: 0xff6633 }, stat: (s) => ({ statusPowerMult: 1 + 0.15 * s }) });
I({ id: 'contagionVial2', name: 'Contagion Vial', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 140, weight: 8, tags: ['offense', 'status'], description: '+15% status chance per stack', icon: { shape: 'vial', color: 0x66ff88 }, stat: (s) => ({ statusChanceMult: 1 + 0.15 * s }) });
I({ id: 'longshotScope2', name: 'Longshot Scope', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 130, weight: 9, tags: ['offense'], description: '+10% range per stack', icon: { shape: 'scope', color: 0x29e7ff }, stat: (s) => ({ rangeMult: 1 + 0.1 * s }) });
I({ id: 'headhunterMark2', name: 'Headhunter Mark', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 150, weight: 7, tags: ['offense', 'precision'], description: '+0.25 headshot mult per stack', icon: { shape: 'target', color: 0xff3df0 }, stat: (s) => ({ headshotMult: 0.25 * s }) });
I({ id: 'armorPenBlade2', name: 'Armor Pen Blade', rarity: ItemRarity.Uncommon, maxStacks: 3, price: 150, weight: 7, tags: ['offense'], description: '+3 armor pen per stack', icon: { shape: 'blade', color: 0xb266ff }, stat: (s) => ({ armorPen: 3 * s }) });

// Rare event reactives
I({ id: 'afterburn', name: 'Afterburn', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'mobility', 'special'], description: 'Dashing leaves a fire trail that burns enemies.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({}), onUpdate: null });
I({ id: 'frostTrail', name: 'Frost Trail', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['control', 'mobility', 'special'], description: 'Dashing leaves a frost trail that slows enemies.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onUpdate: null });
I({ id: 'shockTrail', name: 'Shock Trail', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'mobility', 'special'], description: 'Dashing leaves a shock trail that stuns enemies.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onUpdate: null });
I({ id: 'ammoFactory', name: 'Ammo Factory', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'special'], description: 'Regenerate 2% ammo per second.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), onUpdate: null });
I({ id: 'shieldRegen2', name: 'Shield Recalibrator', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['defense', 'special'], description: 'Shields regen 100% faster.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({}) });
I({ id: 'overheal', name: 'Overheal', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['sustain', 'special'], description: 'Healing above max HP converts to shield (50% efficiency).', icon: { shape: 'heart', color: 0x4fd07a }, stat: () => ({}) });
I({ id: 'pierce2', name: 'Piercing Shot', rarity: ItemRarity.Rare, maxStacks: 2, price: 220, weight: 7, tags: ['offense'], description: '+1 pierce per stack', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: (s) => ({ pierce: s }) });
I({ id: 'ricochet2', name: 'Ricochet Rounds', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'special'], description: 'Hits ricochet to +1 nearby enemy.', icon: { shape: 'arrow', color: 0xffe066 }, stat: () => ({}), onHit: null });

// Epic themed
I({ id: 'emberCore2', name: 'Ember Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Burning enemies grant +10% damage to you.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({}), onUpdate: null });
I({ id: 'frostCore2', name: 'Frost Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Frozen enemies grant +10% move speed to you.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onUpdate: null });
I({ id: 'voltCore2', name: 'Volt Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Shocked enemies grant +10% fire rate to you.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onUpdate: null });
I({ id: 'killHeal', name: 'Kill Heal', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['sustain', 'special'], description: 'Kills heal 2% HP.', icon: { shape: 'drop', color: 0x4fd07a }, stat: () => ({}), onKill: null });
I({ id: 'killSpeed', name: 'Kill Speed', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['mobility', 'special'], description: 'Kills grant +15% move speed for 3s (stacks).', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({}), onKill: null });
I({ id: 'killDamage', name: 'Kill Damage', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: 'Kills grant +10% damage for 3s (stacks).', icon: { shape: 'skull', color: 0xff5544 }, stat: () => ({}), onKill: null });
I({ id: 'killAmmo', name: 'Kill Ammo', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: 'Kills have 20% chance to refill 5% ammo.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), onKill: null });
I({ id: 'killShield', name: 'Kill Shield', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['defense', 'special'], description: 'Kills grant +5 shield.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({}), onKill: null });

// Legendary capstones
I({ id: 'infinityEdge2', name: 'Infinity Edge', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'precision'], description: '+30% crit damage; crits deal +50% to elites/bosses.', icon: { shape: 'blade', color: 0xff3df0 }, stat: () => ({ critMult: 0.3 }) });
I({ id: 'voidHeart', name: 'Void Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 620, weight: 2, tags: ['offense', 'sustain', 'special'], description: '+30% energy damage; lifesteal +5%; dash i-frames +0.2s.', icon: { shape: 'heart', color: 0x8a5bff }, stat: () => ({ lifesteal: 0.05 }) });
I({ id: 'stormHeart', name: 'Storm Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'status', 'special'], description: 'All hits shock; +50% shock power; chains to 2.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), onHit: null });
I({ id: 'infernoHeart', name: 'Inferno Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'status', 'special'], description: 'All hits burn; +50% burn power; burning foes take +30% damage.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), onHit: null });
I({ id: 'absoluteHeart', name: 'Absolute Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'status', 'control', 'special'], description: 'All hits freeze; +50% freeze power; frozen foes take +30% damage.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), onHit: null });

// Curses
I({ id: 'cursedBlade2', name: 'Cursed Blade', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+80% damage, but you take +60% damage.', icon: { shape: 'blade', color: 0xff3df0 }, stat: () => ({ damageMult: 1.8, damageReduction: -0.6 }) });
I({ id: 'fever2', name: 'Fever', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+60% fire rate, but -2 HP/s.', icon: { shape: 'flame', color: 0xff3df0 }, stat: () => ({ fireRateMult: 1.6, regen: -2 }) });
I({ id: 'tunnel2', name: 'Tunnel Vision', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'precision', 'curse'], description: '+40% crit chance, but -40% damage.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ critChance: 0.4, damageMult: 0.6 }) });
I({ id: 'bloodlustCurse2', name: 'Blood Curse', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['sustain', 'curse'], description: '+50% lifesteal, but max HP set to 40.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.5, maxHP: -60 }) });
I({ id: 'glassCannonCore2', name: 'Glass Cannon Core', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+40% damage, but -25% max HP.', icon: { shape: 'cannon', color: 0xff3df0 }, stat: () => ({ damageMult: 1.4, maxHP: -25 }) });
I({ id: 'cursedBlood2', name: 'Cursed Blood', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+60% damage, but you take +50% damage.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ damageMult: 1.6, damageReduction: -0.5 }) });
