// ============================================================================
// items6.js — Rare & epic event-reactive items and more stackers, expanding
// the high-end shop pool and build-defining options.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

const I = (def) => ItemRegistry.register(def);

// ---- Rare stackers ----
I({ id: 'precisionLens', name: 'Precision Lens', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7, tags: ['offense', 'precision'], description: '+8% crit chance per stack', icon: { shape: 'lens', color: 0x9fe7ff }, stat: (s) => ({ critChance: 0.08 * s }) });
I({ id: 'lethalEdge', name: 'Lethal Edge', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['offense', 'precision'], description: '+0.4 crit mult per stack', icon: { shape: 'blade', color: 0xff3df0 }, stat: (s) => ({ critMult: 0.4 * s }) });
I({ id: 'kineticBoost', name: 'Kinetic Boost', rarity: ItemRarity.Rare, maxStacks: 3, price: 200, weight: 7, tags: ['offense'], description: '+12% knockback per stack', icon: { shape: 'fist', color: 0xffaa44 }, stat: (s) => ({ knockbackMult: 1 + 0.12 * s }) });
I({ id: 'flowCapacitor', name: 'Flow Capacitor', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['offense'], description: '+12% projectile speed per stack', icon: { shape: 'arrow', color: 0x4fffd0 }, stat: (s) => ({ projectileSpeedMult: 1 + 0.12 * s }) });
I({ id: 'broadside', name: 'Broadside', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['offense'], description: '+14% AoE per stack', icon: { shape: 'blast', color: 0xff7733 }, stat: (s) => ({ aoeMult: 1 + 0.14 * s }) });
I({ id: 'sharpshooter', name: 'Sharpshooter', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 6, tags: ['offense', 'precision'], description: '+0.3 headshot mult per stack', icon: { shape: 'target', color: 0xff3df0 }, stat: (s) => ({ headshotMult: 0.3 * s }) });
I({ id: 'breacher', name: 'Breacher', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 6, tags: ['offense'], description: '+4 armor pen per stack', icon: { shape: 'arrow', color: 0xb266ff }, stat: (s) => ({ armorPen: 4 * s }) });
I({ id: 'surestep', name: 'Sure Step', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['mobility'], description: '-7% dash cooldown per stack', icon: { shape: 'wind', color: 0x9fe7ff }, stat: (s) => ({ dashCDMult: 1 - 0.07 * s }) });
I({ id: 'sturdy', name: 'Sturdy', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 6, tags: ['defense'], description: '-5% damage taken per stack', icon: { shape: 'shield', color: 0x4aa3ff }, stat: (s) => ({ damageReduction: 0.05 * s }) });
I({ id: 'ample', name: 'Ample', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['offense'], description: '+18% magazine per stack', icon: { shape: 'mag', color: 0xffaa44 }, stat: (s) => ({ magMult: 1 + 0.18 * s }) });
I({ id: 'quickHands', name: 'Quick Hands', rarity: ItemRarity.Rare, maxStacks: 3, price: 210, weight: 7, tags: ['offense'], description: '-10% reload per stack', icon: { shape: 'clock', color: 0x9fe7ff }, stat: (s) => ({ reloadMult: 1 - 0.1 * s }) });
I({ id: 'plagueVial', name: 'Plague Vial', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 6, tags: ['offense', 'status'], description: '+18% poison power per stack', icon: { shape: 'vial', color: 0x66ff88 }, stat: (s) => ({ statusPowerMult: 1 + 0.18 * s }) });
I({ id: 'hemorrhage', name: 'Hemorrhage', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 6, tags: ['offense', 'status'], description: '+18% bleed power per stack', icon: { shape: 'drop', color: 0xff3df0 }, stat: (s) => ({ statusPowerMult: 1 + 0.18 * s }) });

// ---- Epic event-reactives ----
I({ id: 'echoChamber2', name: 'Echo Chamber', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: 'Every 4th shot fires twice.', icon: { shape: 'ring', color: 0x8a5bff }, stat: () => ({}), onUpdate: null });
I({ id: 'overkill', name: 'Overkill', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: 'Overkill damage spreads to nearby enemies.', icon: { shape: 'blast', color: 0xff5544 }, stat: () => ({}), onKill: null });
I({ id: 'secondChance', name: 'Second Chance', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense', 'special'], description: 'Revive once per wave at 30% HP.', icon: { shape: 'feather', color: 0xff7733 }, stat: () => ({}), onDamage: null });
I({ id: 'bloodPact2', name: 'Blood Pact', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'sustain', 'special'], description: '+40% damage and +6% lifesteal, but -1.5 HP/s.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ damageMult: 1.4, lifesteal: 0.06, regen: -1.5 }) });
I({ id: 'frenzy', name: 'Frenzy', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: 'Kills grant +15% fire rate for 3s (stacks).', icon: { shape: 'lightning', color: 0xff5544 }, stat: () => ({}), onKill: null });
I({ id: 'momentumCore2', name: 'Momentum Core', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['mobility', 'offense', 'special'], description: '+25% damage while moving and +15% move speed.', icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({ moveMult: 1.15 }), onUpdate: null });
I({ id: 'lastBreath2', name: 'Last Breath', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'defense', 'special'], description: 'Below 20% HP: +80% fire rate and +40% damage.', icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), onUpdate: null });
I({ id: 'resonance2', name: 'Resonance', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'status', 'special'], description: 'Status effects spread to nearby enemies on death.', icon: { shape: 'ring', color: 0x8a5bff }, stat: () => ({ statusPowerMult: 1.1 }), onKill: null });
I({ id: 'soulHarvest2', name: 'Soul Harvest', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'special'], description: 'Kills grant +0.4% damage permanently (caps +40%).', icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), onKill: null });
I({ id: 'twinSoul2', name: 'Twin Soul', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['sustain', 'special'], description: 'Lifesteal doubled; start each wave +25 HP.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({}), onUpdate: null });
I({ id: 'shatter2', name: 'Shatter', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Frozen enemies shatter for bonus damage on death.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onKill: null });
I({ id: 'conduction', name: 'Conduction', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Shocked enemies chain to 1 more enemy.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onHit: null });
I({ id: 'keystone2', name: 'Keystone', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['offense', 'special'], description: 'Every 5th shot deals +150% damage.', icon: { shape: 'star', color: 0xffe066 }, stat: () => ({}), onUpdate: null });
I({ id: 'marked2', name: 'Marked', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'status', 'special'], description: 'Marked enemies take +40% damage.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({}), onHit: null });
I({ id: 'vitalSpark2', name: 'Vital Spark', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['sustain'], description: 'Healing 30% more effective; +2 HP/s regen.', icon: { shape: 'spark', color: 0x4fd07a }, stat: () => ({ regen: 2 }) });
I({ id: 'aegisMatrix2', name: 'Aegis Matrix', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense', 'special'], description: 'Every 6s, gain a 40-point shield burst.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 20 }), onUpdate: null });
I({ id: 'berserkerBelt2', name: 'Berserker Belt', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'], description: '+40% damage and +20% move speed below 35% HP.', icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), onUpdate: null });

// ---- Legendary capstones ----
I({ id: 'apexCore', name: 'Apex Core', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'precision'], description: '+25% crit chance and +1.0 crit mult.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critChance: 0.25, critMult: 1.0 }) });
I({ id: 'titanHeart', name: 'Titan Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['defense'], description: '+150 max HP, +8 armor, +50 shield.', icon: { shape: 'heart', color: 0x4aa3ff }, stat: () => ({ maxHP: 150, armor: 8, shield: 50 }) });
I({ id: 'stormCore', name: 'Storm Core', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'status', 'special'], description: 'All hits shock; +50% shock power; chains to 2.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), onHit: null });
I({ id: 'phoenixHeart', name: 'Phoenix Heart', rarity: ItemRarity.Legendary, maxStacks: 1, price: 620, weight: 2, tags: ['defense', 'sustain', 'special'], description: 'On lethal hit, explode for 200 dmg and revive once per wave at 50%.', icon: { shape: 'feather', color: 0xff7733 }, stat: () => ({}), onDamage: null });
I({ id: 'infinityEdge', name: 'Infinity Edge', rarity: ItemRarity.Legendary, maxStacks: 1, price: 600, weight: 2, tags: ['offense', 'precision'], description: '+30% crit damage and crits deal +50% to elites/bosses.', icon: { shape: 'blade', color: 0xff3df0 }, stat: () => ({ critMult: 0.3 }), apply: null });

// ---- More curses ----
I({ id: 'cursedBlade', name: 'Cursed Blade', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+80% damage, but you take +60% damage.', icon: { shape: 'blade', color: 0xff3df0 }, stat: () => ({ damageMult: 1.8, damageReduction: -0.6 }) });
I({ id: 'fever', name: 'Fever', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'], description: '+60% fire rate, but -2 HP/s.', icon: { shape: 'flame', color: 0xff3df0 }, stat: () => ({ fireRateMult: 1.6, regen: -2 }) });
I({ id: 'tunnel', name: 'Tunnel Vision', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'precision', 'curse'], description: '+40% crit chance, but -40% damage.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ critChance: 0.4, damageMult: 0.6 }) });
I({ id: 'bloodlustCurse', name: 'Blood Curse', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'sustain', 'curse'], description: '+50% lifesteal, but max HP set to 40.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.5, maxHP: -60 }) });
