// ============================================================================
// items3.js — More items: utility, synergy, and build-capstone passives.
// ============================================================================

import { ItemRegistry } from '../ItemRegistry.js';
import { ItemRarity } from '../ItemRarity.js';

ItemRegistry.registerMany([
  { id: 'berserkerOrb', name: 'Berserker Orb', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: '+50% damage below 35% HP.', icon: { shape: 'orb', color: 0xff5544 }, stat: () => ({}), onUpdate: null },
  { id: 'aegisPlating', name: 'Aegis Plating', rarity: ItemRarity.Legendary, maxStacks: 1, price: 540, weight: 2, tags: ['defense', 'special'],
    description: 'Every 8s, gain a 40-point shield burst.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 20 }), onUpdate: null },
  { id: 'huntersMark', name: "Hunter's Mark", rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'precision', 'special'],
    description: 'The nearest enemy takes +30% damage.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({}), onUpdate: null },
  { id: 'momentumCore', name: 'Momentum Core', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['mobility', 'offense', 'special'],
    description: '+20% damage while moving.', icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({}), onUpdate: null },
  { id: 'stillness', name: 'Stillness', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'precision', 'special'],
    description: '+25% damage and +10% crit chance while stationary.', icon: { shape: 'target', color: 0x4fd07a }, stat: () => ({}), onUpdate: null },
  { id: 'leechCircuit', name: 'Leech Circuit', rarity: ItemRarity.Epic, maxStacks: 1, price: 360, weight: 5, tags: ['sustain', 'special'],
    description: 'Kills restore 3% HP.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({}), onKill: null },
  { id: 'chainLight', name: 'Chain Light', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: 'Hits chain to +1 nearby enemy for 60% damage.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({}), onHit: null },
  { id: 'expansion', name: 'Expansion', rarity: ItemRarity.Epic, maxStacks: 2, price: 360, weight: 5, tags: ['offense', 'aoe'],
    description: '+20% AoE per stack and explosions leave fire.', icon: { shape: 'blast', color: 0xff7733 }, stat: (s) => ({ aoeMult: 1 + 0.2 * s }) },
  { id: 'coreTuner', name: 'Core Tuner', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense'],
    description: '+10% damage and +5% fire rate per stack.', icon: { shape: 'chip', color: 0x29e7ff }, stat: (s) => ({ damageMult: 1 + 0.1 * s, fireRateMult: 1 + 0.05 * s }) },
  { id: 'giantBelt', name: 'Giant Belt', rarity: ItemRarity.Epic, maxStacks: 1, price: 400, weight: 4, tags: ['defense'],
    description: '+100 max HP and +5% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 100, moveMult: 1.05 }) },
  { id: 'swiftStrikes', name: 'Swift Strikes', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['offense'],
    description: '+8% fire rate and -5% spread per stack.', icon: { shape: 'lightning', color: 0x29e7ff }, stat: (s) => ({ fireRateMult: 1 + 0.08 * s, spreadMult: 1 - 0.05 * s }) },
  { id: 'criticalMass', name: 'Critical Mass', rarity: ItemRarity.Legendary, maxStacks: 1, price: 560, weight: 2, tags: ['offense', 'precision'],
    description: '+15% crit chance; crits deal +50% and chain.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critChance: 0.15, critMult: 0.5 }) },
  { id: 'infernalPact', name: 'Infernal Pact', rarity: ItemRarity.Legendary, maxStacks: 1, price: 560, weight: 2, tags: ['offense', 'status', 'special'],
    description: 'All hits burn; +40% burn power.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.5 }), onHit: null },
  { id: 'absolute', name: 'Absolute Zero', rarity: ItemRarity.Legendary, maxStacks: 1, price: 560, weight: 2, tags: ['offense', 'status', 'special'],
    description: 'All hits freeze; +40% freeze power.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.5 }), onHit: null },
  { id: 'overcharge', name: 'Overcharge Coil', rarity: ItemRarity.Epic, maxStacks: 2, price: 360, weight: 5, tags: ['offense', 'energy'],
    description: '+18% energy damage per stack.', icon: { shape: 'coil', color: 0xff3df0 }, stat: (s) => ({ damageMult: 1 + 0.18 * s }) },
  { id: 'munitionsCache', name: 'Munitions Cache', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['offense', 'special'],
    description: 'Kills have a 20% chance to drop ammo.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), onKill: null },
  { id: 'phoenixAsh', name: 'Phoenix Ash', rarity: ItemRarity.Legendary, maxStacks: 1, price: 580, weight: 2, tags: ['defense', 'sustain', 'special'],
    description: 'On lethal hit, explode and revive once per wave at 50% HP.', icon: { shape: 'feather', color: 0xff7733 }, stat: () => ({}), onDamage: null },
  { id: 'titanium', name: 'Titanium Frame', rarity: ItemRarity.Rare, maxStacks: 3, price: 220, weight: 7, tags: ['defense'],
    description: '+4 armor per stack.', icon: { shape: 'square', color: 0x9fb3d6 }, stat: (s) => ({ armor: 4 * s }) },
  { id: 'adrenalGland2', name: 'Adrenal Gland', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['mobility', 'offense', 'special'],
    description: 'Kills grant +15% move speed for 3s (stacks).', icon: { shape: 'gland', color: 0xff5544 }, stat: () => ({}), onKill: null },
  { id: 'echoChamber', name: 'Echo Chamber', rarity: ItemRarity.Legendary, maxStacks: 1, price: 580, weight: 2, tags: ['offense', 'special'],
    description: 'Every 4th shot fires twice.', icon: { shape: 'ring', color: 0x8a5bff }, stat: () => ({}), onUpdate: null },
  { id: 'gravityBoots', name: 'Gravity Boots', rarity: ItemRarity.Rare, maxStacks: 1, price: 240, weight: 6, tags: ['mobility'],
    description: '+15% move speed and dashing knocks back nearby enemies.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.15 }) },
  { id: 'vitalResonator', name: 'Vital Resonator', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['sustain', 'defense'],
    description: '+40 max HP and regen 2 HP/s.', icon: { shape: 'heart', color: 0x4fd07a }, stat: () => ({ maxHP: 40, regen: 2 }) },
  { id: 'shatter', name: 'Shatter', rarity: ItemRarity.Epic, maxStacks: 1, price: 380, weight: 5, tags: ['offense', 'special'],
    description: 'Frozen enemies shatter for bonus damage on death.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({}), onKill: null },
  { id: 'overload', name: 'Overload', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['offense', 'curse'],
    description: '+90% fire rate, but weapons heat up and jam briefly.', icon: { shape: 'flame', color: 0xff3df0 }, stat: () => ({ fireRateMult: 1.9 }) },
  { id: 'pact', name: 'Pact', rarity: ItemRarity.Curse, maxStacks: 1, price: 0, weight: 4, tags: ['economy', 'curse'],
    description: '+100% currency and XP, but -30% damage.', icon: { shape: 'coin', color: 0xff3df0 }, stat: () => ({ currencyMult: 2, xpMult: 2, damageMult: 0.7 }) },
]);
