// ============================================================================
// ballistic.js — Kinetic ballistic weapons: rifles, LMGs, marksman variants,
// and sidearms with distinct handling profiles.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  { id: 'battleRifle', name: 'Battle Rifle', category: 'rifle', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false, burst: 3, burstDelay: 0.06, damage: 16, damageType: DamageType.Kinetic, fireRate: 4, magazine: 24, reserveMax: 168, reloadTime: 1.8,
    spread: 0.008, range: 60, falloffStart: 35, falloffEnd: 55, falloffMin: 0.7, critChance: 0.08, critMult: 2.0, canHeadshot: true,
    knockback: 4, recoil: 1.4, screenShake: 0.06, sfx: 'shoot_rifle', viewmodel: { color: 0x223044, accent: 0x4fd07a, length: 0.7, shape: 'rifle' },
    tracerColor: 0xbfe7a0, impactColor: 0xbfe7a0, description: 'A 3-round-burst battle rifle. Disciplined and punchy.',
    price: 240, unlockWave: 4, tags: ['burst', 'versatile'] },
  { id: 'lmg', name: 'LMG', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true, damage: 14, damageType: DamageType.Kinetic, fireRate: 12, magazine: 80, reserveMax: 400, reloadTime: 3.4,
    spread: 0.024, movingSpread: 0.02, range: 55, falloffStart: 28, falloffEnd: 50, falloffMin: 0.65, critChance: 0.05, critMult: 1.7, canHeadshot: false,
    knockback: 3, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_smg', viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.8, shape: 'heavy' },
    tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A belt-fed LMG. Sustained suppression, huge magazine.',
    price: 460, unlockWave: 8, tags: ['auto', 'suppression', 'crowd'] },
  { id: 'marksman2', name: 'Dmr', category: 'sniper', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false, damage: 48, damageType: DamageType.Kinetic, fireRate: 2.2, magazine: 10, reserveMax: 80, reloadTime: 1.8,
    spread: 0.003, range: 85, falloffStart: 48, falloffEnd: 78, falloffMin: 0.8, critChance: 0.16, critMult: 2.1, canHeadshot: true, headshotMult: 1.9,
    knockback: 7, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_sniper', viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.8, shape: 'rifle' },
    tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, description: 'A semi-auto DMR. Fast, accurate, hard-hitting.',
    price: 280, unlockWave: 5, tags: ['precision', 'semi'] },
  { id: 'smg3', name: 'Hornet', category: 'smg', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: true, damage: 10, damageType: DamageType.Kinetic, fireRate: 20, magazine: 36, reserveMax: 288, reloadTime: 1.5,
    spread: 0.022, movingSpread: 0.016, range: 30, falloffStart: 12, falloffEnd: 26, falloffMin: 0.5, critChance: 0.06, critMult: 1.8, canHeadshot: true,
    knockback: 1, recoil: 0.7, screenShake: 0.03, sfx: 'shoot_smg', viewmodel: { color: 0x223044, accent: 0xff5544, length: 0.5, shape: 'smg' },
    tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'A blistering SMG. Highest RPM in its class.',
    price: 260, unlockWave: 5, tags: ['auto', 'crowd', 'close'] },
  { id: 'handCannon', name: 'Hand Cannon', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false, damage: 55, damageType: DamageType.Kinetic, fireRate: 1.6, magazine: 6, reserveMax: 48, reloadTime: 1.4,
    spread: 0.01, range: 50, falloffStart: 25, falloffEnd: 45, falloffMin: 0.7, critChance: 0.12, critMult: 2.3, canHeadshot: true, headshotMult: 2.0,
    knockback: 10, recoil: 2.4, screenShake: 0.14, sfx: 'shoot_sniper', viewmodel: { color: 0x223044, accent: 0xffb347, length: 0.5, shape: 'pistol' },
    tracerColor: 0xffd28a, impactColor: 0xffb347, description: 'A high-caliber revolver. Big hits, big kick.',
    price: 240, unlockWave: 5, tags: ['precision', 'high-damage', 'knockback'] },
  { id: 'carbine', name: 'Carbine', category: 'rifle', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: true, damage: 13, damageType: DamageType.Kinetic, fireRate: 10, magazine: 30, reserveMax: 210, reloadTime: 1.6,
    spread: 0.012, range: 50, falloffStart: 25, falloffEnd: 45, falloffMin: 0.7, critChance: 0.07, critMult: 1.9, canHeadshot: true,
    knockback: 2, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_rifle', viewmodel: { color: 0x223044, accent: 0x4aa3ff, length: 0.65, shape: 'rifle' },
    tracerColor: 0x9fd0ff, impactColor: 0x4aa3ff, description: 'A compact full-auto carbine. Balanced and forgiving.',
    price: 200, unlockWave: 3, tags: ['auto', 'versatile'] },
  { id: 'shotgunSlug', name: 'Slug Shotgun', category: 'shotgun', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false, damage: 60, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 5, reserveMax: 30, reloadTime: 1.8,
    spread: 0.005, range: 40, falloffStart: 18, falloffEnd: 36, falloffMin: 0.6, critChance: 0.1, critMult: 2.0, canHeadshot: true,
    knockback: 14, recoil: 2.6, screenShake: 0.18, sfx: 'shoot_shotgun', viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.6, shape: 'shotgun' },
    tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A single sabot slug. Range and knockback of a rifle.',
    price: 280, unlockWave: 6, tags: ['precision', 'knockback', 'close'] },
  { id: 'vector2', name: 'Vector-X', category: 'smg', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true, damage: 12, damageType: DamageType.Kinetic, fireRate: 22, magazine: 36, reserveMax: 288, reloadTime: 1.6,
    spread: 0.016, range: 34, critChance: 0.09, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_smg',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.5, shape: 'smg' }, tracerColor: 0xff9de0, impactColor: 0xff3df0,
    description: 'An elite SMG. Smooth recoil, extreme fire rate.', price: 420, unlockWave: 8, tags: ['auto', 'crowd', 'elite'] },
  { id: 'precisionRifle', name: 'Precision Rifle', category: 'rifle', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false, damage: 40, damageType: DamageType.Kinetic, fireRate: 3, magazine: 12, reserveMax: 96, reloadTime: 1.8,
    spread: 0.002, range: 80, falloffStart: 45, falloffEnd: 75, falloffMin: 0.8, critChance: 0.15, critMult: 2.3, canHeadshot: true, headshotMult: 2.1,
    knockback: 6, recoil: 1.8, screenShake: 0.1, sfx: 'shoot_sniper', viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.8, shape: 'rifle' },
    tracerColor: 0x9fd0ff, impactColor: 0x29e7ff, description: 'A semi-auto precision rifle. Headshot machine.',
    price: 420, unlockWave: 8, tags: ['precision', 'semi'] },
  { id: 'gatling', name: 'Gatling', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true, damage: 13, damageType: DamageType.Kinetic, fireRate: 30, magazine: 300, reserveMax: 1200, reloadTime: 5.0,
    spread: 0.03, movingSpread: 0.02, range: 60, falloffStart: 30, falloffEnd: 55, falloffMin: 0.65, critChance: 0.05, critMult: 1.7, canHeadshot: false,
    knockback: 3, recoil: 1.4, screenShake: 0.07, sfx: 'shoot_smg', viewmodel: { color: 0x223044, accent: 0xff5544, length: 0.9, shape: 'heavy' },
    tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'A multi-barrel gatling. The ceiling of raw DPS.',
    price: 700, unlockWave: 13, tags: ['auto', 'suppression', 'crowd'] },
]);
