// ============================================================================
// core.js — The foundational arsenal: sidearm, SMG, shotgun, rifle, sniper,
// rocket launcher, laser, plasma, minigun, and a melee blade. These cover the
// core fire modes and serve as the player's reliable toolkit.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  {
    id: 'pistol', name: 'Sidearm', category: 'sidearm', rarity: WeaponRarity.Common,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 18, damageType: DamageType.Kinetic, fireRate: 6, magazine: 14, reserveMax: 120, reloadTime: 1.1,
    spread: 0.006, range: 60, falloffStart: 30, falloffEnd: 55, falloffMin: 0.6,
    critChance: 0.08, critMult: 2.0, canHeadshot: true, headshotMult: 1.75,
    knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_pistol',
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.5, shape: 'pistol' },
    tracerColor: 0xffe08a, impactColor: 0xffe08a,
    description: 'Reliable semi-auto sidearm. Infinite viability.',
    flavor: 'Every survivor starts here. Make it count.',
    price: 0, tags: ['starter', 'precision'],
  },
  {
    id: 'smg', name: 'Vector SMG', category: 'smg', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 9, damageType: DamageType.Kinetic, fireRate: 14, magazine: 30, reserveMax: 240, reloadTime: 1.6,
    spread: 0.018, movingSpread: 0.02, range: 38, falloffStart: 18, falloffEnd: 34, falloffMin: 0.55,
    critChance: 0.05, critMult: 1.8, canHeadshot: true,
    knockback: 1.5, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_smg',
    viewmodel: { color: 0x223044, accent: 0x4fd07a, length: 0.55, shape: 'smg' },
    tracerColor: 0xbfe7a0, impactColor: 0xbfe7a0,
    description: 'High rate of fire, low per-shot damage. Great vs swarms.',
    price: 120, unlockWave: 1, tags: ['auto', 'crowd'],
  },
  {
    id: 'shotgun', name: 'Scattergun', category: 'shotgun', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 7, damageType: DamageType.Kinetic, fireRate: 1.4, magazine: 6, reserveMax: 48, reloadTime: 2.0,
    pellets: 8, spread: 0.09, movingSpread: 0.02, range: 18, falloffStart: 8, falloffEnd: 16, falloffMin: 0.3,
    critChance: 0.06, critMult: 1.7, canHeadshot: false,
    knockback: 8, recoil: 2.2, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random',
    viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.6, shape: 'shotgun' },
    tracerColor: 0xffd28a, impactColor: 0xffaa44,
    description: 'Eight-pellet spread. Devastating point-blank.',
    price: 160, unlockWave: 2, tags: ['close', 'crowd', 'knockback'],
  },
  {
    id: 'rifle', name: 'Pulse Rifle', category: 'rifle', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 16, damageType: DamageType.Kinetic, fireRate: 8, magazine: 30, reserveMax: 210, reloadTime: 1.8,
    spread: 0.01, movingSpread: 0.012, range: 70, falloffStart: 40, falloffEnd: 65, falloffMin: 0.7,
    critChance: 0.07, critMult: 2.0, canHeadshot: true, headshotMult: 1.8,
    knockback: 3, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_rifle',
    viewmodel: { color: 0x223044, accent: 0x4aa3ff, length: 0.7, shape: 'rifle' },
    tracerColor: 0x9fd0ff, impactColor: 0x4aa3ff,
    description: 'Versatile full-auto rifle. Strong at any range.',
    price: 260, unlockWave: 3, tags: ['auto', 'versatile'],
  },
  {
    id: 'sniper', name: 'Rail Lance', category: 'sniper', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 95, damageType: DamageType.Energy, fireRate: 1.0, magazine: 5, reserveMax: 40, reloadTime: 2.4,
    spread: 0.0, range: 120, falloffStart: 80, falloffEnd: 110, falloffMin: 0.85,
    critChance: 0.25, critMult: 2.5, canHeadshot: true, headshotMult: 2.5,
    knockback: 12, recoil: 4.0, screenShake: 0.22, sfx: 'shoot_sniper',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.85, shape: 'rifle' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2,
    description: 'High-damage precision rifle. Headshots delete elites.',
    price: 320, unlockWave: 4, tags: ['precision', 'high-damage'],
  },
  {
    id: 'rocket', name: 'Phoenix Launcher', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 70, damageType: DamageType.Explosive, fireRate: 0.8, magazine: 4, reserveMax: 24, reloadTime: 2.6,
    spread: 0.0, range: 80,
    knockback: 14, recoil: 3.5, screenShake: 0.2, sfx: 'shoot_rocket',
    projectile: { speed: 38, gravity: 0.4, lifetime: 3, color: 0xff7733, radius: 0.22, shape: 'chunky', scale: 1.4, aoe: 5, aoeFalloff: 0.5, glow: true, trail: true },
    critChance: 0.0, canHeadshot: false,
    viewmodel: { color: 0x223044, accent: 0xff7733, length: 0.7, shape: 'launcher' },
    projectileColor: 0xff7733, impactColor: 0xff7733,
    description: 'Explosive rockets with area damage. Crowd clear king.',
    price: 420, unlockWave: 6, tags: ['explosive', 'crowd', 'aoe'],
  },
  {
    id: 'laser', name: 'Laser Lance', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: true,
    damage: 14, damageType: DamageType.Energy, fireRate: 10, magazine: 120, reserveMax: 0, reloadTime: 1.8,
    spread: 0.0, range: 60, critChance: 0.1, critMult: 1.8, canHeadshot: false,
    knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser',
    beam: { width: 0.1, tickRate: 0.08, color: 0xff3df0 },
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.6, shape: 'energy' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0,
    statusChance: 0.15, statusType: StatusType.Burn, statusPower: 1, statusDuration: 2,
    description: 'Continuous beam that melts single targets. No reserve ammo.',
    price: 380, unlockWave: 5, tags: ['beam', 'sustained', 'burn'],
  },
  {
    id: 'plasma', name: 'Plasma Caster', category: 'energy', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: true,
    damage: 26, damageType: DamageType.Energy, fireRate: 5, magazine: 20, reserveMax: 140, reloadTime: 1.9,
    spread: 0.02, range: 60, critChance: 0.08, critMult: 2.0, canHeadshot: true,
    knockback: 4, recoil: 1.4, screenShake: 0.07, sfx: 'shoot_plasma',
    projectile: { speed: 50, gravity: 0, lifetime: 2.4, color: 0x29e7ff, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 2.2, aoeFalloff: 0.4, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.6, shape: 'energy' },
    projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'Lobs plasma orbs that splash on impact.',
    price: 300, unlockWave: 4, tags: ['projectile', 'aoe', 'energy'],
  },
  {
    id: 'minigun', name: 'Cyclone', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 8, damageType: DamageType.Kinetic, fireRate: 22, magazine: 120, reserveMax: 600, reloadTime: 3.2,
    spread: 0.03, movingSpread: 0.02, range: 50, falloffStart: 25, falloffEnd: 45, falloffMin: 0.6,
    critChance: 0.04, critMult: 1.6, canHeadshot: false,
    knockback: 2, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_smg',
    viewmodel: { color: 0x223044, accent: 0xffb347, length: 0.7, shape: 'heavy' },
    tracerColor: 0xffd28a, impactColor: 0xffb347,
    description: 'Suppressing fire at extreme RPM. Chews through ammo.',
    price: 500, unlockWave: 7, tags: ['auto', 'suppression', 'crowd'],
  },
  {
    id: 'blade', name: 'Phase Blade', category: 'melee', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Melee, auto: true,
    damage: 45, damageType: DamageType.Energy, fireRate: 3, magazine: 1, reserveMax: 0, reloadTime: 0,
    spread: 0, range: 2.4, critChance: 0.12, critMult: 2.2, canHeadshot: false,
    knockback: 10, recoil: 0.6, screenShake: 0.1, sfx: 'shoot_lightning',
    melee: { range: 2.6, arc: 1.3, angle: 1.3 },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.7, shape: 'blade' },
    impactColor: 0x29e7ff,
    statusChance: 0.3, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5,
    lifesteal: 0.1,
    description: 'Arc melee that shocks and heals you on hit.',
    price: 200, unlockWave: 2, tags: ['melee', 'lifesteal', 'shock'],
  },
]);
