// ============================================================================
// energy3.js — More energy weapons: beams, plasma, and elemental variants.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'energy', len = 0.6) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'pulseBeam2', name: 'Pulse Beam-X', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: true,
  damage: 14, damageType: DamageType.Energy, fireRate: 13, magazine: 100, reserveMax: 0, reloadTime: 1.8, spread: 0.0, range: 55, critChance: 0.12, critMult: 2.0, canHeadshot: true, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser', beam: { width: 0.1, tickRate: 0.07, color: 0x29e7ff }, viewmodel: vmdl(0x29e7ff), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'An upgraded sustained pulse beam.', price: 420, unlockWave: 8, tags: ['beam', 'sustained', 'energy'] });
R({ id: 'emberBeam2', name: 'Ember Beam-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 14, damageType: DamageType.Fire, fireRate: 16, magazine: 120, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 42, critChance: 0.1, critMult: 1.9, canHeadshot: false, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_flame', beam: { width: 0.14, tickRate: 0.06, color: 0xff5522 }, viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, lifesteal: 0.03, description: 'An ember beam. Sustained fire that ignites and leeches.', price: 660, unlockWave: 13, tags: ['beam', 'fire', 'status', 'lifesteal'] });
R({ id: 'cryoBeam2', name: 'Cryo Beam-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 13, damageType: DamageType.Cryo, fireRate: 13, magazine: 100, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 42, critChance: 0.1, critMult: 1.9, canHeadshot: false, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser', beam: { width: 0.14, tickRate: 0.07, color: 0x9fe7ff }, viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.6, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'A cryo beam. Locks targets in ice.', price: 640, unlockWave: 13, tags: ['beam', 'cryo', 'control'] });
R({ id: 'voidBeam2', name: 'Void Beam-X', category: 'energy', rarity: WeaponRarity.Mythic, fireMode: FireMode.Beam, auto: true,
  damage: 28, damageType: DamageType.Energy, fireRate: 13, magazine: 150, reserveMax: 0, reloadTime: 2.2, spread: 0.0, range: 55, critChance: 0.22, critMult: 2.5, canHeadshot: true, knockback: 4, recoil: 0.5, screenShake: 0.04, sfx: 'shoot_railgun', beam: { width: 0.18, tickRate: 0.05, color: 0x8a5bff }, viewmodel: vmdl(0x8a5bff), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.5, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, lifesteal: 0.08, description: 'A mythic void beam. Marks, leeches, and shreds.', price: 950, unlockWave: 18, tags: ['beam', 'mythic', 'sustain', 'lifesteal'] });
R({ id: 'arcBeam2', name: 'Arc Beam-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 12, damageType: DamageType.Shock, fireRate: 16, magazine: 120, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 40, critChance: 0.12, critMult: 1.9, canHeadshot: false, knockback: 1, recoil: 0.3, screenShake: 0.03, sfx: 'shoot_lightning', beam: { width: 0.12, tickRate: 0.05, color: 0xffe066 }, viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, description: 'An arc beam. Sustained shock that stuns and chains.', price: 660, unlockWave: 13, tags: ['beam', 'shock', 'status'] });
R({ id: 'plasmaRifle3', name: 'Plasma Repeater-X', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: true,
  damage: 24, damageType: DamageType.Energy, fireRate: 8, magazine: 26, reserveMax: 182, reloadTime: 1.7, spread: 0.014, range: 60, critChance: 0.09, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 58, gravity: 0, lifetime: 2.2, color: 0x29e7ff, radius: 0.2, shape: 'orb', scale: 1.1, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff, 'rifle', 0.7), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A rapid plasma repeater. High single-target output.', price: 440, unlockWave: 9, tags: ['projectile', 'energy', 'auto'] });
R({ id: 'tesla2', name: 'Tesla Coil-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 14, damageType: DamageType.Shock, fireRate: 14, magazine: 100, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 38, critChance: 0.12, critMult: 1.9, canHeadshot: false, knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_lightning', beam: { width: 0.13, tickRate: 0.06, color: 0x9fe7ff }, viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, description: 'A chain-lightning beam that shocks and chains.', price: 660, unlockWave: 13, tags: ['beam', 'shock', 'sustained'] });
R({ id: 'frostbeam2', name: 'Cryo Lance-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 12, damageType: DamageType.Cryo, fireRate: 11, magazine: 100, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 36, critChance: 0.1, critMult: 1.8, canHeadshot: false, knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_laser', beam: { width: 0.15, tickRate: 0.07, color: 0x9fe7ff }, viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.6, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'A freezing beam that locks enemies in place.', price: 640, unlockWave: 13, tags: ['beam', 'cryo', 'control'] });
R({ id: 'ionDriver2', name: 'Ion Driver-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: true,
  damage: 18, damageType: DamageType.Energy, fireRate: 10, magazine: 40, reserveMax: 280, reloadTime: 2.0, spread: 0.016, range: 55, critChance: 0.1, critMult: 2.1, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 72, gravity: 0, lifetime: 1.8, color: 0x4fffd0, radius: 0.16, shape: 'shard', scale: 1.1, pierce: 2, glow: true, trail: true }, viewmodel: vmdl(0x4fffd0, 'rifle', 0.7), projectileColor: 0x4fffd0, impactColor: 0x4fffd0, description: 'High-velocity ion shards that pierce two enemies.', price: 620, unlockWave: 12, tags: ['projectile', 'energy', 'pierce'] });
R({ id: 'stellarCannon2', name: 'Stellar Cannon-X', category: 'energy', rarity: WeaponRarity.Mythic, fireMode: FireMode.Projectile, auto: false,
  damage: 120, damageType: DamageType.Energy, fireRate: 1.0, magazine: 6, reserveMax: 36, reloadTime: 2.4, spread: 0.0, range: 75, critChance: 0.15, critMult: 2.4, canHeadshot: false, knockback: 16, recoil: 3.5, screenShake: 0.2, sfx: 'shoot_plasma', projectile: { speed: 46, gravity: 0, lifetime: 2.5, color: 0xffb347, radius: 0.3, shape: 'orb', scale: 1.8, aoe: 5, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xffb347, 'heavy', 0.8), projectileColor: 0xffb347, impactColor: 0xffb347, statusChance: 0.4, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, description: 'A mythic stellar cannon. Heavy fiery AoE orbs.', price: 920, unlockWave: 18, tags: ['projectile', 'aoe', 'burn', 'mythic', 'high-damage'] });
R({ id: 'photonRepeater2', name: 'Photon Repeater-X', category: 'energy', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: true,
  damage: 14, damageType: DamageType.Energy, fireRate: 12, magazine: 28, reserveMax: 196, reloadTime: 1.6, spread: 0.011, range: 58, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_laser', viewmodel: vmdl(0xff3df0, 'smg', 0.6), tracerColor: 0xff3df0, impactColor: 0xff3df0, description: 'A full-auto photon pulse repeater. Crisp and precise.', price: 300, unlockWave: 6, tags: ['auto', 'energy', 'precision'] });
R({ id: 'pyroBeam2', name: 'Inferno Projector-X', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 13, damageType: DamageType.Fire, fireRate: 16, magazine: 120, reserveMax: 0, reloadTime: 1.8, spread: 0.0, range: 24, critChance: 0.06, critMult: 1.7, canHeadshot: false, knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_flame', beam: { width: 0.24, tickRate: 0.05, color: 0xff6633 }, viewmodel: vmdl(0xff6633, 'launcher', 0.6), tracerColor: 0xff6633, impactColor: 0xff6633, statusChance: 0.6, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, description: 'A proper flamethrower beam. Short range, massive melt.', price: 660, unlockWave: 13, tags: ['beam', 'fire', 'close', 'crowd'] });
