// ============================================================================
// energy.js — Energy / elemental weapons: beams, plasma, tesla, cryo, void.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  {
    id: 'tesla', name: 'Tesla Coil', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: true,
    damage: 11, damageType: DamageType.Shock, fireRate: 12, magazine: 100, reserveMax: 0, reloadTime: 2.0,
    spread: 0.0, range: 36, critChance: 0.1, critMult: 1.8, canHeadshot: false,
    knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_lightning',
    beam: { width: 0.12, tickRate: 0.07, color: 0x9fe7ff },
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.6, shape: 'energy' },
    tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5,
    description: 'Chain-lightning beam that shocks targets. Chains to nearby foes via perks.',
    price: 420, unlockWave: 8, tags: ['beam', 'shock', 'sustained'],
  },
  {
    id: 'frostbeam', name: 'Cryo Lance', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: true,
    damage: 10, damageType: DamageType.Cryo, fireRate: 10, magazine: 100, reserveMax: 0, reloadTime: 2.0,
    spread: 0.0, range: 34, critChance: 0.08, critMult: 1.7,
    knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_laser',
    beam: { width: 0.14, tickRate: 0.08, color: 0x9fe7ff },
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.6, shape: 'energy' },
    tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2,
    description: 'Freezing beam that locks enemies in place.',
    price: 420, unlockWave: 9, tags: ['beam', 'cryo', 'control'],
  },
  {
    id: 'plasmaRifle', name: 'Plasma Repeater', category: 'energy', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: true,
    damage: 22, damageType: DamageType.Energy, fireRate: 7, magazine: 24, reserveMax: 160, reloadTime: 1.7,
    spread: 0.015, range: 60, critChance: 0.08, critMult: 2.0, canHeadshot: true,
    knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_plasma',
    projectile: { speed: 56, gravity: 0, lifetime: 2.2, color: 0x29e7ff, radius: 0.2, shape: 'orb', scale: 1.1, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.7, shape: 'rifle' },
    projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'Rapid plasma orbs. No splash but high single-target output.',
    price: 300, unlockWave: 5, tags: ['projectile', 'energy', 'auto'],
  },
  {
    id: 'arcCannon', name: 'Arc Cannon', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 60, damageType: DamageType.Shock, fireRate: 1.5, magazine: 8, reserveMax: 64, reloadTime: 2.0,
    spread: 0.0, range: 50, critChance: 0.1, critMult: 2.2, canHeadshot: true,
    knockback: 6, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_lightning',
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.7, shape: 'heavy' },
    tracerColor: 0xffe066, impactColor: 0xffe066, tracerWidth: 2,
    statusChance: 0.6, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2,
    description: 'Charged arc shot that shocks and chains. Pierces 2 targets.',
    price: 460, unlockWave: 10, tags: ['precision', 'shock', 'pierce'],
    projectile: { pierce: 2 },
  },
  {
    id: 'voidLance', name: 'Void Lance', category: 'energy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 130, damageType: DamageType.Energy, fireRate: 0.9, magazine: 4, reserveMax: 32, reloadTime: 2.2,
    spread: 0.0, range: 100, falloffStart: 60, falloffEnd: 95, falloffMin: 0.8,
    critChance: 0.3, critMult: 2.6, canHeadshot: true, headshotMult: 2.4,
    knockback: 16, recoil: 4.5, screenShake: 0.24, sfx: 'shoot_railgun',
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.9, shape: 'rifle' },
    tracerColor: 0x8a5bff, impactColor: 0x8a5bff, tracerWidth: 3,
    description: 'A void-infused rail that punches through everything. Devastating crits.',
    price: 700, unlockWave: 14, tags: ['precision', 'high-damage', 'pierce'],
    projectile: { pierce: 8 },
  },
  {
    id: 'ionDriver', name: 'Ion Driver', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: true,
    damage: 16, damageType: DamageType.Energy, fireRate: 9, magazine: 40, reserveMax: 280, reloadTime: 2.0,
    spread: 0.02, range: 50, critChance: 0.07, critMult: 1.9, canHeadshot: true,
    knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma',
    projectile: { speed: 70, gravity: 0, lifetime: 1.8, color: 0x4fffd0, radius: 0.16, shape: 'shard', scale: 1, pierce: 1, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x4fffd0, length: 0.7, shape: 'rifle' },
    projectileColor: 0x4fffd0, impactColor: 0x4fffd0,
    description: 'High-velocity ion shards that pierce one enemy.',
    price: 440, unlockWave: 11, tags: ['projectile', 'energy', 'pierce'],
  },
  {
    id: 'photonRepeater', name: 'Photon Repeater', category: 'energy', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 13, damageType: DamageType.Energy, fireRate: 11, magazine: 28, reserveMax: 196, reloadTime: 1.6,
    spread: 0.012, range: 55, critChance: 0.09, critMult: 2.0, canHeadshot: true,
    knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_laser',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.6, shape: 'smg' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'Full-auto photon pulses. Crisp and precise.',
    price: 280, unlockWave: 6, tags: ['auto', 'energy', 'precision'],
  },
  {
    id: 'stellarCannon', name: 'Stellar Cannon', category: 'energy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false,
    damage: 110, damageType: DamageType.Energy, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 2.4,
    spread: 0.0, range: 70, critChance: 0.15, critMult: 2.4, canHeadshot: false,
    knockback: 16, recoil: 3.5, screenShake: 0.2, sfx: 'shoot_plasma',
    projectile: { speed: 45, gravity: 0, lifetime: 2.5, color: 0xffb347, radius: 0.3, shape: 'orb', scale: 1.8, aoe: 5, aoeFalloff: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffb347, length: 0.8, shape: 'heavy' },
    projectileColor: 0xffb347, impactColor: 0xffb347,
    statusChance: 0.4, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3,
    description: 'Lobs stellar orbs that detonate in fiery AoE. Heavy hitter.',
    price: 680, unlockWave: 16, tags: ['projectile', 'aoe', 'burn', 'high-damage'],
  },
  {
    id: 'pyroBeam', name: 'Inferno Projector', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: true,
    damage: 12, damageType: DamageType.Fire, fireRate: 14, magazine: 120, reserveMax: 0, reloadTime: 1.8,
    spread: 0.0, range: 22, critChance: 0.05, critMult: 1.6, canHeadshot: false,
    knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_flame',
    beam: { width: 0.22, tickRate: 0.06, color: 0xff6633 },
    viewmodel: { color: 0x223044, accent: 0xff6633, length: 0.6, shape: 'energy' },
    tracerColor: 0xff6633, impactColor: 0xff6633,
    statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3,
    description: 'Short-range flamethrower beam. Melts crowds up close.',
    price: 440, unlockWave: 10, tags: ['beam', 'fire', 'close', 'crowd'],
  },
]);
