// ============================================================================
// energy2.js — A large roster of energy weapons: beams, plasma, tesla, cryo,
// void, and hybrid energy weapons for elemental and sustained-DPS builds.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'energy', len = 0.6) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'pulseBeam', name: 'Pulse Beam', category: 'energy', rarity: WeaponRarity.Rare, fireMode: FireMode.Beam, auto: true,
  damage: 12, damageType: DamageType.Energy, fireRate: 12, magazine: 100, reserveMax: 0, reloadTime: 1.8, spread: 0.0, range: 50, critChance: 0.1, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser', beam: { width: 0.1, tickRate: 0.08, color: 0x29e7ff }, viewmodel: vmdl(0x29e7ff), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A sustained pulse beam. Reliable energy DPS.', price: 320, unlockWave: 6, tags: ['beam', 'sustained', 'energy'] });
R({ id: 'emberBeam', name: 'Ember Beam', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: true,
  damage: 11, damageType: DamageType.Fire, fireRate: 14, magazine: 120, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 40, critChance: 0.08, critMult: 1.8, canHeadshot: false, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_flame', beam: { width: 0.14, tickRate: 0.07, color: 0xff5522 }, viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.4, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, description: 'An ember beam. Sustained fire that ignites.', price: 440, unlockWave: 9, tags: ['beam', 'fire', 'status'] });
R({ id: 'cryoBeam', name: 'Cryo Beam', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: true,
  damage: 11, damageType: DamageType.Cryo, fireRate: 12, magazine: 100, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 40, critChance: 0.08, critMult: 1.8, canHeadshot: false, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser', beam: { width: 0.14, tickRate: 0.08, color: 0x9fe7ff }, viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'A cryo beam. Locks targets in ice.', price: 440, unlockWave: 9, tags: ['beam', 'cryo', 'control'] });
R({ id: 'voidBeam', name: 'Void Beam', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 22, damageType: DamageType.Energy, fireRate: 12, magazine: 150, reserveMax: 0, reloadTime: 2.2, spread: 0.0, range: 50, critChance: 0.18, critMult: 2.4, canHeadshot: true, knockback: 4, recoil: 0.5, screenShake: 0.04, sfx: 'shoot_railgun', beam: { width: 0.16, tickRate: 0.06, color: 0x8a5bff }, viewmodel: vmdl(0x8a5bff), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, lifesteal: 0.06, description: 'A void beam. Marks, leeches, and shreds.', price: 680, unlockWave: 14, tags: ['beam', 'sustain', 'lifesteal', 'energy'] });
R({ id: 'arcBeam', name: 'Arc Beam', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: true,
  damage: 10, damageType: DamageType.Shock, fireRate: 14, magazine: 120, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 36, critChance: 0.1, critMult: 1.8, canHeadshot: false, knockback: 1, recoil: 0.3, screenShake: 0.03, sfx: 'shoot_lightning', beam: { width: 0.12, tickRate: 0.06, color: 0xffe066 }, viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, description: 'An arc beam. Sustained shock that stuns.', price: 440, unlockWave: 9, tags: ['beam', 'shock', 'status'] });
R({ id: 'plasmaOrb', name: 'Plasma Orb', category: 'energy', rarity: WeaponRarity.Rare, fireMode: FireMode.Projectile, auto: false,
  damage: 35, damageType: DamageType.Energy, fireRate: 3, magazine: 16, reserveMax: 112, reloadTime: 1.8, spread: 0.02, range: 50, critChance: 0.08, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_plasma', projectile: { speed: 48, gravity: 0, lifetime: 2.2, color: 0x29e7ff, radius: 0.2, shape: 'orb', scale: 1.2, aoe: 2.5, aoeFalloff: 0.4, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A plasma orb caster. Splash damage per shot.', price: 300, unlockWave: 5, tags: ['projectile', 'aoe', 'energy'] });
R({ id: 'teslaOrb', name: 'Tesla Orb', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 30, damageType: DamageType.Shock, fireRate: 2.5, magazine: 14, reserveMax: 98, reloadTime: 1.9, spread: 0.02, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_lightning', projectile: { speed: 40, gravity: 0, lifetime: 2.2, color: 0xffe066, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 3, aoeFalloff: 0.4, homing: 0.3, glow: true, trail: true }, viewmodel: vmdl(0xffe066), projectileColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, description: 'A tesla orb. Homing shock with a splash.', price: 420, unlockWave: 9, tags: ['projectile', 'shock', 'homing', 'aoe'] });
R({ id: 'frostOrb', name: 'Frost Orb', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 30, damageType: DamageType.Cryo, fireRate: 2.5, magazine: 14, reserveMax: 98, reloadTime: 1.9, spread: 0.02, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_plasma', projectile: { speed: 40, gravity: 0, lifetime: 2.2, color: 0x9fe7ff, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 3, aoeFalloff: 0.4, glow: true, trail: true }, viewmodel: vmdl(0x9fe7ff), projectileColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'A frost orb. Splash that freezes.', price: 420, unlockWave: 9, tags: ['projectile', 'cryo', 'aoe', 'control'] });
R({ id: 'emberOrb', name: 'Ember Orb', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 30, damageType: DamageType.Fire, fireRate: 2.5, magazine: 14, reserveMax: 98, reloadTime: 1.9, spread: 0.02, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_plasma', projectile: { speed: 40, gravity: 0, lifetime: 2.2, color: 0xff5522, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 3, aoeFalloff: 0.4, glow: true, trail: true }, viewmodel: vmdl(0xff5522), projectileColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, description: 'An ember orb. Splash that ignites.', price: 420, unlockWave: 9, tags: ['projectile', 'fire', 'aoe', 'status'] });
R({ id: 'ionCannon', name: 'Ion Cannon', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: true,
  damage: 22, damageType: DamageType.Energy, fireRate: 8, magazine: 30, reserveMax: 210, reloadTime: 2.0, spread: 0.016, range: 50, critChance: 0.1, critMult: 2.1, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 70, gravity: 0, lifetime: 1.8, color: 0x4fffd0, radius: 0.16, shape: 'shard', scale: 1.1, pierce: 2, glow: true, trail: true }, viewmodel: vmdl(0x4fffd0), projectileColor: 0x4fffd0, impactColor: 0x4fffd0, description: 'An ion cannon. High-velocity piercing shards.', price: 620, unlockWave: 12, tags: ['auto', 'projectile', 'pierce', 'energy'] });
R({ id: 'photonCannon', name: 'Photon Cannon', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 16, damageType: DamageType.Energy, fireRate: 12, magazine: 30, reserveMax: 210, reloadTime: 1.8, spread: 0.01, range: 55, critChance: 0.12, critMult: 2.2, canHeadshot: true, knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_laser', viewmodel: vmdl(0xff3df0), tracerColor: 0xff3df0, impactColor: 0xff3df0, description: 'A photon cannon. Full-auto precision energy.', price: 620, unlockWave: 12, tags: ['auto', 'precision', 'energy'] });
R({ id: 'stellarBeam', name: 'Stellar Beam', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: true,
  damage: 20, damageType: DamageType.Energy, fireRate: 14, magazine: 150, reserveMax: 0, reloadTime: 2.2, spread: 0.0, range: 50, critChance: 0.15, critMult: 2.3, canHeadshot: true, knockback: 2, recoil: 0.4, screenShake: 0.04, sfx: 'shoot_railgun', beam: { width: 0.16, tickRate: 0.06, color: 0xffb347 }, viewmodel: vmdl(0xffb347), tracerColor: 0xffb347, impactColor: 0xffb347, statusChance: 0.4, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, description: 'A stellar beam. Sustained stellar fire.', price: 660, unlockWave: 13, tags: ['beam', 'sustained', 'fire', 'energy'] });
