// ============================================================================
// experimental.js — Experimental/proto weapons with unusual trade-offs and
// mechanics. High variance, high reward, occasionally weird.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  { id: 'pulseShotgun', name: 'Pulse Shotgun', category: 'shotgun', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 18, damageType: DamageType.Energy, fireRate: 1.6, magazine: 8, reserveMax: 48, reloadTime: 2.0,
    pellets: 6, spread: 0.07, range: 22, critChance: 0.06, critMult: 1.8, canHeadshot: false, knockback: 8, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_plasma',
    projectile: { speed: 40, gravity: 0, lifetime: 1.2, color: 0x29e7ff, radius: 0.16, shape: 'orb', scale: 0.9, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.6, shape: 'shotgun' }, projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'A plasma shotgun. Pellets travel as energy orbs.', price: 420, unlockWave: 8, tags: ['close', 'energy', 'crowd'] },
  { id: 'chargePistol', name: 'Charge Pistol', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Charged, chargeTime: 0.8, auto: false, damage: 20, damageType: DamageType.Energy, fireRate: 2, magazine: 12, reserveMax: 96, reloadTime: 1.3,
    spread: 0.004, range: 60, critChance: 0.12, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 6, recoil: 1.4, screenShake: 0.08, sfx: 'shoot_plasma',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.5, shape: 'pistol' }, tracerColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'Hold to charge for up to 3x damage. Release to fire.', price: 260, unlockWave: 5, tags: ['charged', 'precision'] },
  { id: 'splitShotgun', name: 'Split Scattershot', category: 'shotgun', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 14, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 2.0,
    pellets: 8, spread: 0.08, range: 26, critChance: 0.05, critMult: 1.7, canHeadshot: false, knockback: 6, recoil: 2.2, screenShake: 0.14, sfx: 'shoot_shotgun',
    projectile: { speed: 50, gravity: 0, lifetime: 1.4, color: 0xffaa44, radius: 0.14, shape: 'shard', scale: 0.8, pierce: 1, ricochet: 1, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.6, shape: 'shotgun' }, projectileColor: 0xffaa44, impactColor: 0xffaa44,
    description: 'Pellets that pierce one target and ricochet once. Crowd mulcher.', price: 620, unlockWave: 12, tags: ['close', 'pierce', 'ricochet', 'crowd'] },
  { id: 'waveCannon', name: 'Wave Cannon', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 45, damageType: DamageType.Energy, fireRate: 1.0, magazine: 6, reserveMax: 36, reloadTime: 2.2,
    spread: 0.0, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: false, knockback: 12, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_plasma',
    projectile: { speed: 30, gravity: 0, lifetime: 2, color: 0x29e7ff, radius: 0.5, shape: 'ring', scale: 1.5, aoe: 4, aoeFalloff: 0.3, pierce: 99, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.7, shape: 'heavy' }, projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'Fires an expanding shock ring that pierces and detonates.', price: 480, unlockWave: 10, tags: ['aoe', 'pierce', 'control'] },
  { id: 'leechGun', name: 'Leech Gun', category: 'energy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Beam, auto: true, damage: 18, damageType: DamageType.Energy, fireRate: 10, magazine: 100, reserveMax: 0, reloadTime: 2.0,
    spread: 0.0, range: 32, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser',
    beam: { width: 0.1, tickRate: 0.08, color: 0xff3df0 }, viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.6, shape: 'energy' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0, lifesteal: 0.25,
    description: 'A drain beam that returns 25% of damage as health.', price: 640, unlockWave: 12, tags: ['beam', 'lifesteal', 'sustain'] },
  { id: 'chainGun', name: 'Whiplash', category: 'special', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true, damage: 14, damageType: DamageType.Shock, fireRate: 5, magazine: 20, reserveMax: 140, reloadTime: 1.8,
    spread: 0.02, range: 45, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_lightning',
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.6, shape: 'energy' }, tracerColor: 0xffe066, impactColor: 0xffe066,
    statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 2, projectile: { pierce: 2 },
    description: 'Hitscan that pierces two foes and shocks on contact.', price: 440, unlockWave: 9, tags: ['pierce', 'shock', 'auto'] },
  { id: 'vortex', name: 'Vortex Gun', category: 'special', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 35, damageType: DamageType.Energy, fireRate: 0.9, magazine: 4, reserveMax: 20, reloadTime: 2.4,
    spread: 0.0, range: 40, critChance: 0.0, canHeadshot: false, knockback: 0, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_plasma',
    projectile: { speed: 20, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.4, shape: 'ring', scale: 1.6, aoe: 7, aoeFalloff: 0.0, homing: 0.2, glow: true, trail: true },
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.7, shape: 'heavy' }, projectileColor: 0x8a5bff, impactColor: 0x8a5bff,
    statusChance: 0.6, statusType: StatusType.Slow, statusPower: 3, statusDuration: 3,
    description: 'A slow vortex that pulls enemies in and slows them.', price: 660, unlockWave: 13, tags: ['control', 'aoe', 'special'] },
  { id: 'shotLance', name: 'Shot Lance', category: 'melee', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Melee, auto: true, damage: 70, damageType: DamageType.Energy, fireRate: 1.6, magazine: 1, reserveMax: 0, reloadTime: 0,
    spread: 0, range: 4, critChance: 0.18, critMult: 2.4, canHeadshot: false, knockback: 18, recoil: 1.0, screenShake: 0.14, sfx: 'shoot_lightning',
    melee: { range: 4.2, arc: 1.4, angle: 1.4 }, viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.9, shape: 'blade' }, impactColor: 0x29e7ff,
    lifesteal: 0.15, statusChance: 0.3, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5,
    description: 'A long energy lance with wide arc, shock, and lifesteal.', price: 420, unlockWave: 9, tags: ['melee', 'lifesteal', 'shock'] },
  { id: 'splitterCannon', name: 'Splitter Cannon', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 40, damageType: DamageType.Explosive, fireRate: 1.0, magazine: 5, reserveMax: 25, reloadTime: 2.4,
    spread: 0.0, range: 55, critChance: 0.0, canHeadshot: false, knockback: 10, recoil: 2.6, screenShake: 0.18, sfx: 'shoot_rocket',
    projectile: { speed: 34, gravity: 0.2, lifetime: 2.5, color: 0xff7733, radius: 0.24, shape: 'chunky', scale: 1.3, aoe: 4, aoeFalloff: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff7733, length: 0.7, shape: 'launcher' }, projectileColor: 0xff7733, impactColor: 0xff7733,
    description: 'Rockets that split into clusters mid-flight (via perks).', price: 640, unlockWave: 12, tags: ['explosive', 'aoe', 'crowd'] },
  { id: 'echoRifle', name: 'Echo Rifle', category: 'rifle', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true, damage: 20, damageType: DamageType.Energy, fireRate: 6, magazine: 24, reserveMax: 168, reloadTime: 1.8,
    spread: 0.006, range: 60, critChance: 0.14, critMult: 2.2, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_laser',
    viewmodel: { color: 0x223044, accent: 0x4fffd0, length: 0.7, shape: 'rifle' }, tracerColor: 0x4fffd0, impactColor: 0x4fffd0,
    statusChance: 0.3, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3,
    description: 'Phased rounds that mark targets and echo damage to nearby foes.', price: 620, unlockWave: 12, tags: ['auto', 'mark', 'special'] },
  { id: 'gravityWell', name: 'Gravity Well', category: 'special', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Projectile, auto: false, damage: 60, damageType: DamageType.Energy, fireRate: 0.6, magazine: 3, reserveMax: 12, reloadTime: 2.8,
    spread: 0.0, range: 45, critChance: 0.0, canHeadshot: false, knockback: 0, recoil: 2.4, screenShake: 0.2, sfx: 'shoot_plasma',
    projectile: { speed: 18, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.7, shape: 'orb', scale: 2.2, aoe: 10, aoeFalloff: 0.0, proximity: 8, glow: true, trail: true },
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.8, shape: 'heavy' }, projectileColor: 0x8a5bff, impactColor: 0x8a5bff,
    statusChance: 0.7, statusType: StatusType.Slow, statusPower: 3, statusDuration: 4,
    description: 'A mythic gravity well that collapses a whole area.', price: 900, unlockWave: 17, tags: ['control', 'aoe', 'mythic', 'special'] },
  { id: 'prismCannon', name: 'Prism Cannon', category: 'energy', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Beam, auto: true, damage: 26, damageType: DamageType.Energy, fireRate: 14, magazine: 150, reserveMax: 0, reloadTime: 2.2,
    spread: 0.0, range: 50, critChance: 0.2, critMult: 2.5, canHeadshot: true, knockback: 3, recoil: 0.5, screenShake: 0.04, sfx: 'shoot_railgun',
    beam: { width: 0.16, tickRate: 0.06, color: 0xff3df0 }, viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.7, shape: 'energy' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0, lifesteal: 0.06, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3,
    description: 'A mythic prism beam: high DPS, marks, leeches, and chains.', price: 950, unlockWave: 18, tags: ['beam', 'mythic', 'sustain'] },
]);
