// ============================================================================
// heavy2.js — Heavy ordnance: more launchers, a rotary, and area saturation.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  { id: 'autoLauncher', name: 'Salvo', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: true, damage: 55, damageType: DamageType.Explosive, fireRate: 2.2, magazine: 8, reserveMax: 48, reloadTime: 2.6,
    spread: 0.0, range: 70, critChance: 0.0, canHeadshot: false, knockback: 12, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_rocket',
    projectile: { speed: 42, gravity: 0.3, lifetime: 2.5, color: 0xff5544, radius: 0.2, shape: 'chunky', scale: 1.2, aoe: 4.5, aoeFalloff: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff5544, length: 0.7, shape: 'launcher' }, projectileColor: 0xff5544, impactColor: 0xff5544,
    description: 'Full-auto rocket launcher. A barrage of explosions.', price: 640, unlockWave: 12, tags: ['explosive', 'aoe', 'auto', 'crowd'] },
  { id: 'clusterBomb', name: 'Cluster Bomb', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 70, damageType: DamageType.Explosive, fireRate: 0.8, magazine: 4, reserveMax: 20, reloadTime: 2.6,
    spread: 0.0, range: 60, critChance: 0.0, canHeadshot: false, knockback: 14, recoil: 3.0, screenShake: 0.2, sfx: 'shoot_rocket',
    projectile: { speed: 30, gravity: 0.6, lifetime: 2.5, color: 0xffaa44, radius: 0.3, shape: 'chunky', scale: 1.6, aoe: 6, aoeFalloff: 0.4, proximity: 4, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.7, shape: 'launcher' }, projectileColor: 0xffaa44, impactColor: 0xffaa44,
    description: 'A slow arcing bomb that airbursts into a huge blast.', price: 480, unlockWave: 10, tags: ['explosive', 'aoe', 'proximity'] },
  { id: 'rotary', name: 'Annihilator', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true, damage: 12, damageType: DamageType.Kinetic, fireRate: 28, magazine: 200, reserveMax: 800, reloadTime: 4.0,
    spread: 0.035, movingSpread: 0.02, range: 55, falloffStart: 28, falloffEnd: 50, falloffMin: 0.6, critChance: 0.05, critMult: 1.7, canHeadshot: false,
    knockback: 3, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_smg', viewmodel: { color: 0x223044, accent: 0xff5544, length: 0.8, shape: 'heavy' },
    tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'A monstrous rotary cannon. Unmatched suppression.',
    price: 700, unlockWave: 13, tags: ['auto', 'suppression', 'crowd'] },
  { id: 'plasmaBomb', name: 'Plasma Bomb', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 90, damageType: DamageType.Energy, fireRate: 0.9, magazine: 5, reserveMax: 25, reloadTime: 2.4,
    spread: 0.0, range: 50, critChance: 0.0, canHeadshot: false, knockback: 16, recoil: 2.8, screenShake: 0.2, sfx: 'shoot_plasma',
    projectile: { speed: 28, gravity: 0.5, lifetime: 2.4, color: 0x29e7ff, radius: 0.4, shape: 'orb', scale: 1.8, aoe: 7, aoeFalloff: 0.3, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.7, shape: 'launcher' }, projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3,
    description: 'Lobs a plasma bomb that detonates in a burning sphere.', price: 460, unlockWave: 9, tags: ['explosive', 'aoe', 'energy', 'burn'] },
  { id: 'napalm', name: 'Napalm Launcher', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 40, damageType: DamageType.Fire, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 2.2,
    spread: 0.0, range: 40, critChance: 0.0, canHeadshot: false, knockback: 6, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_flame',
    projectile: { speed: 26, gravity: 0.6, lifetime: 2.5, color: 0xff5522, radius: 0.28, shape: 'chunky', scale: 1.4, aoe: 5, aoeFalloff: 0.2, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff5522, length: 0.7, shape: 'launcher' }, projectileColor: 0xff5522, impactColor: 0xff5522,
    statusChance: 0.8, statusType: StatusType.Burn, statusPower: 3, statusDuration: 4,
    description: 'Sprays fire on impact. Leaves enemies burning.', price: 440, unlockWave: 8, tags: ['explosive', 'fire', 'aoe', 'status'] },
  { id: 'teslaCannon', name: 'Tesla Cannon', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 60, damageType: DamageType.Shock, fireRate: 1.0, magazine: 6, reserveMax: 36, reloadTime: 2.2,
    spread: 0.0, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: false, knockback: 10, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_lightning',
    projectile: { speed: 36, gravity: 0, lifetime: 2.5, color: 0x9fe7ff, radius: 0.3, shape: 'orb', scale: 1.5, aoe: 6, aoeFalloff: 0.4, homing: 0.3, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.8, shape: 'heavy' }, projectileColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    statusChance: 0.7, statusType: StatusType.Shock, statusPower: 3, statusDuration: 3,
    description: 'A homing tesla orb that shocks everything in its blast.', price: 660, unlockWave: 13, tags: ['explosive', 'shock', 'homing', 'aoe'] },
  { id: 'gravCannon', name: 'Grav Cannon', category: 'heavy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 50, damageType: DamageType.Energy, fireRate: 0.9, magazine: 4, reserveMax: 20, reloadTime: 2.8,
    spread: 0.0, range: 50, critChance: 0.0, canHeadshot: false, knockback: 0, recoil: 2.2, screenShake: 0.18, sfx: 'shoot_plasma',
    projectile: { speed: 24, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.6, shape: 'orb', scale: 2, aoe: 9, aoeFalloff: 0.0, proximity: 7, glow: true, trail: true },
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.8, shape: 'heavy' }, projectileColor: 0x8a5bff, impactColor: 0x8a5bff,
    statusChance: 0.5, statusType: StatusType.Slow, statusPower: 3, statusDuration: 3,
    description: 'A gravity warhead that pulls foes in and slows survivors.', price: 700, unlockWave: 14, tags: ['explosive', 'control', 'aoe', 'special'] },
  { id: 'micromissiles', name: 'Swarm Missiles', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: true, damage: 28, damageType: DamageType.Explosive, fireRate: 4, magazine: 20, reserveMax: 120, reloadTime: 2.4,
    spread: 0.05, range: 55, critChance: 0.0, canHeadshot: false, knockback: 6, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_rocket',
    projectile: { speed: 38, gravity: 0.1, lifetime: 2.5, color: 0xff7733, radius: 0.16, shape: 'chunky', scale: 0.8, aoe: 2.5, aoeFalloff: 0.5, homing: 0.4, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff7733, length: 0.7, shape: 'launcher' }, projectileColor: 0xff7733, impactColor: 0xff7733,
    description: 'Spams homing micro-missiles. Locks onto the nearest foe.', price: 480, unlockWave: 10, tags: ['explosive', 'homing', 'auto', 'aoe'] },
]);
