// ============================================================================
// heavy4.js — More heavy ordnance: launchers, cannons, and saturation tools.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'launcher', len = 0.7) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'rocket3', name: 'Viper', category: 'heavy', rarity: WeaponRarity.Rare, fireMode: FireMode.Projectile, auto: false,
  damage: 65, damageType: DamageType.Explosive, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 2.0, spread: 0.0, range: 75, knockback: 14, recoil: 2.8, screenShake: 0.18, sfx: 'shoot_rocket',
  projectile: { speed: 48, gravity: 0.1, lifetime: 2.5, color: 0xff5544, radius: 0.22, shape: 'chunky', scale: 1.3, aoe: 5, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xff5544), projectileColor: 0xff5544, impactColor: 0xff5544, description: 'A viper launcher. Fast, direct rockets.', price: 300, unlockWave: 6, tags: ['explosive', 'aoe', 'crowd'] });
R({ id: 'homingLauncher2', name: 'Swarm Launcher', category: 'heavy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: true,
  damage: 30, damageType: DamageType.Explosive, fireRate: 4, magazine: 20, reserveMax: 120, reloadTime: 2.4, spread: 0.06, range: 60, knockback: 6, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_rocket',
  projectile: { speed: 40, gravity: 0.1, lifetime: 2.5, color: 0xff7733, radius: 0.16, shape: 'chunky', scale: 0.8, aoe: 2.5, aoeFalloff: 0.5, homing: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xff7733), projectileColor: 0xff7733, impactColor: 0xff7733, description: 'Spams homing micro-missiles. Locks onto the nearest foe.', price: 480, unlockWave: 10, tags: ['explosive', 'homing', 'auto', 'aoe'] });
R({ id: 'plasmaCannon3', name: 'Plasma Cannon', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 120, damageType: DamageType.Energy, fireRate: 0.7, magazine: 5, reserveMax: 25, reloadTime: 2.4, spread: 0.0, range: 55, knockback: 20, recoil: 3.2, screenShake: 0.24, sfx: 'shoot_plasma',
  projectile: { speed: 30, gravity: 0.3, lifetime: 2.4, color: 0x29e7ff, radius: 0.42, shape: 'orb', scale: 2, aoe: 8, aoeFalloff: 0.3, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, description: 'A plasma cannon. Huge burning plasma orbs.', price: 680, unlockWave: 14, tags: ['explosive', 'aoe', 'energy', 'burn', 'high-damage'] });
R({ id: 'teslaCannon2', name: 'Tesla Cannon', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 70, damageType: DamageType.Shock, fireRate: 1.0, magazine: 6, reserveMax: 36, reloadTime: 2.2, spread: 0.0, range: 50, critChance: 0.1, critMult: 2.0, canHeadshot: false, knockback: 12, recoil: 2.4, screenShake: 0.18, sfx: 'shoot_lightning',
  projectile: { speed: 38, gravity: 0, lifetime: 2.5, color: 0x9fe7ff, radius: 0.3, shape: 'orb', scale: 1.5, aoe: 7, aoeFalloff: 0.4, homing: 0.4, glow: true, trail: true }, viewmodel: vmdl(0x9fe7ff), projectileColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.8, statusType: StatusType.Shock, statusPower: 3, statusDuration: 3, description: 'A tesla cannon. Homing shock orbs that stun a wide area.', price: 680, unlockWave: 14, tags: ['explosive', 'shock', 'homing', 'aoe'] });
R({ id: 'gravCannon2', name: 'Grav Cannon', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 60, damageType: DamageType.Energy, fireRate: 0.9, magazine: 4, reserveMax: 20, reloadTime: 2.8, spread: 0.0, range: 50, knockback: 0, recoil: 2.2, screenShake: 0.18, sfx: 'shoot_plasma',
  projectile: { speed: 24, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.6, shape: 'orb', scale: 2, aoe: 10, aoeFalloff: 0.0, proximity: 8, glow: true, trail: true }, viewmodel: vmdl(0x8a5bff), projectileColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.6, statusType: StatusType.Slow, statusPower: 3, statusDuration: 3, description: 'A gravity warhead that pulls foes in and slows survivors.', price: 720, unlockWave: 15, tags: ['explosive', 'control', 'aoe', 'special'] });
R({ id: 'autoLauncher2', name: 'Salvo', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: true,
  damage: 60, damageType: DamageType.Explosive, fireRate: 2.5, magazine: 10, reserveMax: 60, reloadTime: 2.6, spread: 0.0, range: 75, knockback: 12, recoil: 2.2, screenShake: 0.16, sfx: 'shoot_rocket',
  projectile: { speed: 46, gravity: 0.2, lifetime: 2.5, color: 0xff5544, radius: 0.22, shape: 'chunky', scale: 1.2, aoe: 5, aoeFalloff: 0.5, homing: 0.2, glow: true, trail: true }, viewmodel: vmdl(0xff5544), projectileColor: 0xff5544, impactColor: 0xff5544, description: 'A full-auto rocket launcher. A barrage of explosions.', price: 680, unlockWave: 13, tags: ['explosive', 'aoe', 'auto', 'crowd'] });
R({ id: 'clusterBomb2', name: 'Cluster Bomb', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 80, damageType: DamageType.Explosive, fireRate: 0.7, magazine: 4, reserveMax: 20, reloadTime: 2.6, spread: 0.0, range: 60, knockback: 14, recoil: 3.0, screenShake: 0.22, sfx: 'shoot_rocket',
  projectile: { speed: 30, gravity: 0.6, lifetime: 2.5, color: 0xffaa44, radius: 0.3, shape: 'chunky', scale: 1.6, aoe: 6, aoeFalloff: 0.4, proximity: 4, glow: true, trail: true }, viewmodel: vmdl(0xffaa44), projectileColor: 0xffaa44, impactColor: 0xffaa44, description: 'A slow arcing bomb that airbursts into a huge blast.', price: 660, unlockWave: 13, tags: ['explosive', 'aoe', 'proximity'] });
R({ id: 'napalm2', name: 'Napalm Launcher', category: 'heavy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 50, damageType: DamageType.Fire, fireRate: 1.0, magazine: 6, reserveMax: 36, reloadTime: 2.2, spread: 0.0, range: 45, knockback: 6, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_flame',
  projectile: { speed: 28, gravity: 0.5, lifetime: 2.5, color: 0xff5522, radius: 0.28, shape: 'chunky', scale: 1.4, aoe: 6, aoeFalloff: 0.2, glow: true, trail: true }, viewmodel: vmdl(0xff5522), projectileColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.9, statusType: StatusType.Burn, statusPower: 4, statusDuration: 5, description: 'A napalm launcher. Leaves enemies burning for a long time.', price: 660, unlockWave: 13, tags: ['explosive', 'fire', 'aoe', 'status'] });
R({ id: 'railCannon', name: 'Rail Cannon', category: 'heavy', rarity: WeaponRarity.Mythic, fireMode: FireMode.Hitscan, auto: false,
  damage: 200, damageType: DamageType.Kinetic, fireRate: 0.5, magazine: 3, reserveMax: 15, reloadTime: 3.0, spread: 0.0, range: 120, falloffStart: 80, falloffEnd: 110, falloffMin: 0.9, critChance: 0.3, critMult: 2.8, canHeadshot: true, headshotMult: 2.8, knockback: 30, recoil: 5.0, screenShake: 0.3, sfx: 'shoot_railgun', viewmodel: vmdl(0xff3df0, 'heavy', 0.9), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 4, projectile: { pierce: 10 }, description: 'A mythic rail cannon. The hardest-hitting single shot in the game.', price: 950, unlockWave: 18, tags: ['precision', 'pierce', 'high-damage', 'mythic'] });
R({ id: 'obliteration', name: 'Obliteration', category: 'heavy', rarity: WeaponRarity.Mythic, fireMode: FireMode.Projectile, auto: false,
  damage: 300, damageType: DamageType.Explosive, fireRate: 0.4, magazine: 2, reserveMax: 8, reloadTime: 3.2, spread: 0.0, range: 100, critChance: 0.0, canHeadshot: false, knockback: 50, recoil: 5.5, screenShake: 0.4, sfx: 'shoot_railgun',
  projectile: { speed: 42, gravity: 0, lifetime: 3, color: 0xff3df0, radius: 0.7, shape: 'orb', scale: 2.6, aoe: 16, aoeFalloff: 0.2, glow: true, trail: true }, viewmodel: vmdl(0xff3df0, 'heavy', 0.95), projectileColor: 0xff3df0, impactColor: 0xff3df0, description: 'A mythic single shot that erases everything in a huge radius.', price: 1200, unlockWave: 22, tags: ['explosive', 'aoe', 'mythic', 'high-damage'] });
