// ============================================================================
// legendary.js — Mythic & legendary weapons: end-game powerhouses with
// unique mechanics and the highest damage ceilings in the game.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  {
    id: 'excalibur', name: 'Excalibur', category: 'melee', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Melee, auto: true,
    damage: 180, damageType: DamageType.Energy, fireRate: 2.5, magazine: 1, reserveMax: 0, reloadTime: 0,
    spread: 0, range: 3.2, critChance: 0.25, critMult: 3.0, canHeadshot: false,
    knockback: 24, recoil: 0.8, screenShake: 0.18, sfx: 'shoot_lightning',
    melee: { range: 3.4, arc: 1.6, angle: 1.6 },
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.9, shape: 'blade' },
    impactColor: 0xffe066,
    statusChance: 0.5, statusType: StatusType.Mark, statusPower: 3, statusDuration: 4,
    lifesteal: 0.25,
    description: 'The legendary blade. Vast arc, huge damage, massive lifesteal.',
    price: 900, unlockWave: 18, tags: ['melee', 'lifesteal', 'mythic', 'high-damage'],
  },
  {
    id: 'bfg', name: 'Nexus BFG', category: 'heavy', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 200, damageType: DamageType.Energy, fireRate: 0.5, magazine: 3, reserveMax: 15, reloadTime: 3.0,
    spread: 0.0, range: 80, critChance: 0.0, canHeadshot: false,
    knockback: 30, recoil: 4.0, screenShake: 0.3, sfx: 'shoot_railgun',
    projectile: { speed: 30, gravity: 0, lifetime: 3, color: 0x29e7ff, radius: 0.6, shape: 'orb', scale: 2.2, aoe: 10, aoeFalloff: 0.3, pierce: 99, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.9, shape: 'heavy' },
    projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'Fires a colossal plasma orb that pierces and detonates repeatedly. Room cleaner.',
    price: 1000, unlockWave: 20, tags: ['explosive', 'aoe', 'pierce', 'mythic', 'crowd'],
  },
  {
    id: 'voidReaper', name: 'Void Reaper', category: 'energy', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Beam, auto: true,
    damage: 30, damageType: DamageType.Energy, fireRate: 12, magazine: 150, reserveMax: 0, reloadTime: 2.2,
    spread: 0.0, range: 50, critChance: 0.2, critMult: 2.5, canHeadshot: true,
    knockback: 4, recoil: 0.5, screenShake: 0.04, sfx: 'shoot_railgun',
    beam: { width: 0.18, tickRate: 0.06, color: 0x8a5bff },
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.7, shape: 'energy' },
    tracerColor: 0x8a5bff, impactColor: 0x8a5bff,
    statusChance: 0.5, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3,
    lifesteal: 0.08,
    description: 'A scything void beam that marks and leeches. The ultimate sustain DPS.',
    price: 950, unlockWave: 19, tags: ['beam', 'mythic', 'sustain', 'lifesteal'],
  },
  {
    id: 'phoenix', name: 'Phoenix Fang', category: 'sidearm', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 28, damageType: DamageType.Fire, fireRate: 9, magazine: 18, reserveMax: 144, reloadTime: 1.4,
    spread: 0.01, range: 60, critChance: 0.15, critMult: 2.4, canHeadshot: true,
    knockback: 5, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_plasma',
    viewmodel: { color: 0x223044, accent: 0xff7733, length: 0.5, shape: 'pistol' },
    tracerColor: 0xff7733, impactColor: 0xff7733,
    statusChance: 0.5, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3,
    lifesteal: 0.05,
    description: 'A flaming sidearm that ignites and leeches. Punches above its class.',
    price: 620, unlockWave: 13, tags: ['auto', 'fire', 'lifesteal', 'precision'],
  },
  {
    id: 'frostbite', name: 'Frostbite', category: 'rifle', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 20, damageType: DamageType.Cryo, fireRate: 8, magazine: 30, reserveMax: 210, reloadTime: 1.8,
    spread: 0.008, range: 65, critChance: 0.12, critMult: 2.2, canHeadshot: true,
    knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_laser',
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.7, shape: 'rifle' },
    tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2,
    description: 'Full-auto cryo rounds that freeze targets solid.',
    price: 620, unlockWave: 13, tags: ['auto', 'cryo', 'control'],
  },
  {
    id: 'stormCaller', name: 'Stormcaller', category: 'energy', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: true,
    damage: 24, damageType: DamageType.Shock, fireRate: 6, magazine: 24, reserveMax: 168, reloadTime: 1.9,
    spread: 0.03, range: 45, critChance: 0.1, critMult: 2.2, canHeadshot: true,
    knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_lightning',
    projectile: { speed: 48, gravity: 0, lifetime: 2.2, color: 0xffe066, radius: 0.2, shape: 'shard', scale: 1.1, homing: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.7, shape: 'energy' },
    projectileColor: 0xffe066, impactColor: 0xffe066,
    statusChance: 0.4, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2,
    description: 'Homing lightning shards that seek enemies and shock them.',
    price: 600, unlockWave: 12, tags: ['projectile', 'homing', 'shock'],
  },
  {
    id: 'twinFang', name: 'Twin Fang', category: 'smg', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: true, burst: 2, burstDelay: 0.04,
    damage: 14, damageType: DamageType.Kinetic, fireRate: 11, magazine: 40, reserveMax: 320, reloadTime: 1.5,
    spread: 0.014, range: 42, critChance: 0.12, critMult: 2.2, canHeadshot: true,
    knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_smg',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.55, shape: 'smg' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'Twin-barrel burst SMG. Fires 2 rounds per shot at high cadence.',
    price: 560, unlockWave: 11, tags: ['auto', 'burst', 'crowd'],
  },
  {
    id: 'oblivion', name: 'Oblivion', category: 'heavy', rarity: WeaponRarity.Mythic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 260, damageType: DamageType.Explosive, fireRate: 0.4, magazine: 2, reserveMax: 10, reloadTime: 3.2,
    spread: 0.0, range: 90, critChance: 0.0, canHeadshot: false,
    knockback: 40, recoil: 5.0, screenShake: 0.35, sfx: 'shoot_railgun',
    projectile: { speed: 40, gravity: 0, lifetime: 3, color: 0xff3df0, radius: 0.7, shape: 'orb', scale: 2.6, aoe: 14, aoeFalloff: 0.2, glow: true, trail: true },
    viewmodel: { color: 0x1a0a20, accent: 0xff3df0, length: 0.95, shape: 'heavy' },
    projectileColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'The ultimate weapon. A single shot that erases everything in a huge radius.',
    price: 1200, unlockWave: 22, tags: ['explosive', 'aoe', 'mythic', 'high-damage'],
  },
]);
