// ============================================================================
// melee2.js — A roster of melee weapons: blades, hammers, fists, lances, and
// elemental melee for close-quarters lifesteal and crowd control builds.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'blade', len = 0.7) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'katana', name: 'Katana', category: 'melee', rarity: WeaponRarity.Rare, fireMode: FireMode.Melee, auto: true,
  damage: 55, damageType: DamageType.Kinetic, fireRate: 4, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.6, critChance: 0.15, critMult: 2.3, canHeadshot: false, knockback: 8, recoil: 0.7, screenShake: 0.1, sfx: 'shoot_lightning', melee: { range: 2.8, arc: 1.4, angle: 1.4 }, viewmodel: vmdl(0x29e7ff), impactColor: 0x29e7ff, statusChance: 0.3, statusType: StatusType.Bleed, statusPower: 1, statusDuration: 2, lifesteal: 0.08, description: 'A katana. Fast, wide arc, bleeds and leeches.', price: 260, unlockWave: 4, tags: ['melee', 'lifesteal', 'bleed'] });
R({ id: 'warhammer', name: 'Warhammer', category: 'melee', rarity: WeaponRarity.Epic, fireMode: FireMode.Melee, auto: true,
  damage: 90, damageType: DamageType.Kinetic, fireRate: 1.6, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.8, critChance: 0.1, critMult: 2.2, canHeadshot: false, knockback: 24, recoil: 1.0, screenShake: 0.16, sfx: 'shoot_shotgun', melee: { range: 3.0, arc: 1.2, angle: 1.2 }, viewmodel: vmdl(0xffaa44, 'blade', 0.7), impactColor: 0xffaa44, description: 'A warhammer. Slow, huge damage, massive knockback.', price: 380, unlockWave: 8, tags: ['melee', 'knockback', 'high-damage'] });
R({ id: 'fist', name: 'Power Fists', category: 'melee', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Melee, auto: true,
  damage: 35, damageType: DamageType.Kinetic, fireRate: 5, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.2, critChance: 0.1, critMult: 2.0, canHeadshot: false, knockback: 14, recoil: 0.5, screenShake: 0.08, sfx: 'shoot_lightning', melee: { range: 2.4, arc: 1.0, angle: 1.0 }, viewmodel: vmdl(0xff5544, 'blade', 0.5), impactColor: 0xff5544, lifesteal: 0.05, description: 'Power fists. Fast jabs with big knockback.', price: 200, unlockWave: 3, tags: ['melee', 'knockback', 'lifesteal'] });
R({ id: 'voidBlade', name: 'Void Blade', category: 'melee', rarity: WeaponRarity.Legendary, fireMode: FireMode.Melee, auto: true,
  damage: 120, damageType: DamageType.Energy, fireRate: 2.5, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 3.0, critChance: 0.2, critMult: 2.6, canHeadshot: false, knockback: 16, recoil: 0.8, screenShake: 0.14, sfx: 'shoot_railgun', melee: { range: 3.2, arc: 1.5, angle: 1.5 }, viewmodel: vmdl(0x8a5bff), impactColor: 0x8a5bff, statusChance: 0.5, statusType: StatusType.Mark, statusPower: 3, statusDuration: 4, lifesteal: 0.2, description: 'A void blade. Wide arc, marks, and huge lifesteal.', price: 700, unlockWave: 14, tags: ['melee', 'lifesteal', 'mark', 'high-damage'] });
R({ id: 'emberBlade', name: 'Ember Blade', category: 'melee', rarity: WeaponRarity.Epic, fireMode: FireMode.Melee, auto: true,
  damage: 60, damageType: DamageType.Fire, fireRate: 3, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.6, critChance: 0.12, critMult: 2.2, canHeadshot: false, knockback: 10, recoil: 0.7, screenShake: 0.1, sfx: 'shoot_plasma', melee: { range: 2.8, arc: 1.4, angle: 1.4 }, viewmodel: vmdl(0xff5522), impactColor: 0xff5522, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, lifesteal: 0.1, description: 'An ember blade. Ignites and leeches.', price: 420, unlockWave: 9, tags: ['melee', 'fire', 'lifesteal', 'status'] });
R({ id: 'frostBlade', name: 'Frost Blade', category: 'melee', rarity: WeaponRarity.Epic, fireMode: FireMode.Melee, auto: true,
  damage: 60, damageType: DamageType.Cryo, fireRate: 3, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.6, critChance: 0.12, critMult: 2.2, canHeadshot: false, knockback: 10, recoil: 0.7, screenShake: 0.1, sfx: 'shoot_laser', melee: { range: 2.8, arc: 1.4, angle: 1.4 }, viewmodel: vmdl(0x9fe7ff), impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, lifesteal: 0.1, description: 'A frost blade. Freezes and leeches.', price: 420, unlockWave: 9, tags: ['melee', 'cryo', 'lifesteal', 'control'] });
R({ id: 'shockBlade', name: 'Shock Blade', category: 'melee', rarity: WeaponRarity.Epic, fireMode: FireMode.Melee, auto: true,
  damage: 60, damageType: DamageType.Shock, fireRate: 3, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.6, critChance: 0.12, critMult: 2.2, canHeadshot: false, knockback: 10, recoil: 0.7, screenShake: 0.1, sfx: 'shoot_lightning', melee: { range: 2.8, arc: 1.4, angle: 1.4 }, viewmodel: vmdl(0xffe066), impactColor: 0xffe066, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, lifesteal: 0.1, description: 'A shock blade. Stuns and leeches.', price: 420, unlockWave: 9, tags: ['melee', 'shock', 'lifesteal', 'status'] });
R({ id: 'whip', name: 'Energy Whip', category: 'melee', rarity: WeaponRarity.Rare, fireMode: FireMode.Melee, auto: true,
  damage: 40, damageType: DamageType.Energy, fireRate: 4, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 4.0, critChance: 0.12, critMult: 2.1, canHeadshot: false, knockback: 12, recoil: 0.6, screenShake: 0.08, sfx: 'shoot_lightning', melee: { range: 4.2, arc: 1.6, angle: 1.6 }, viewmodel: vmdl(0xff3df0), impactColor: 0xff3df0, statusChance: 0.3, statusType: StatusType.Mark, statusPower: 1, statusDuration: 2, description: 'An energy whip. Long reach, wide arc.', price: 280, unlockWave: 5, tags: ['melee', 'mark', 'reach'] });
R({ id: 'dualBlades', name: 'Dual Blades', category: 'melee', rarity: WeaponRarity.Epic, fireMode: FireMode.Melee, auto: true,
  damage: 48, damageType: DamageType.Kinetic, fireRate: 5, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 2.6, critChance: 0.14, critMult: 2.2, canHeadshot: false, knockback: 8, recoil: 0.6, screenShake: 0.08, sfx: 'shoot_lightning', melee: { range: 2.8, arc: 1.5, angle: 1.5 }, viewmodel: vmdl(0x29e7ff), impactColor: 0x29e7ff, statusChance: 0.25, statusType: StatusType.Bleed, statusPower: 1, statusDuration: 2, lifesteal: 0.12, description: 'Dual blades. Fast, wide, bleeds and leeches.', price: 380, unlockWave: 7, tags: ['melee', 'lifesteal', 'bleed', 'fast'] });
R({ id: 'glaive', name: 'Glaive', category: 'melee', rarity: WeaponRarity.Legendary, fireMode: FireMode.Melee, auto: true,
  damage: 80, damageType: DamageType.Energy, fireRate: 2.8, magazine: 1, reserveMax: 0, reloadTime: 0, spread: 0, range: 3.4, critChance: 0.16, critMult: 2.4, canHeadshot: false, knockback: 14, recoil: 0.8, screenShake: 0.12, sfx: 'shoot_lightning', melee: { range: 3.6, arc: 1.5, angle: 1.5 }, viewmodel: vmdl(0xffb347, 'blade', 0.8), impactColor: 0xffb347, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, lifesteal: 0.15, description: 'A glaive. Long reach, marks, and strong lifesteal.', price: 620, unlockWave: 12, tags: ['melee', 'reach', 'lifesteal', 'mark'] });
