// ============================================================================
// precision2.js — More marksman & precision weapons for accuracy-focused
// builds. High damage, high crit, rewarding headshots.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, len = 0.85) => ({ color: 0x223044, accent, length: len, shape: 'rifle' });

R({ id: 'marksman3', name: 'Dmr-X', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 55, damageType: DamageType.Kinetic, fireRate: 2, magazine: 10, reserveMax: 80, reloadTime: 1.8, spread: 0.002, range: 90, falloffStart: 50, falloffEnd: 82, falloffMin: 0.82, critChance: 0.18, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 7, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_sniper', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, description: 'An elite DMR. Fast, accurate, hard-hitting.', price: 420, unlockWave: 8, tags: ['precision', 'semi'] });
R({ id: 'crossbow2', name: 'Arc Crossbow', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 95, damageType: DamageType.Kinetic, fireRate: 0.9, magazine: 5, reserveMax: 30, reloadTime: 2.2, spread: 0.0, range: 75, critChance: 0.22, critMult: 2.4, canHeadshot: true, headshotMult: 2.2, knockback: 16, recoil: 2.8, screenShake: 0.16, sfx: 'shoot_rifle', projectile: { speed: 72, gravity: 0.3, lifetime: 2, color: 0x66ff88, radius: 0.16, shape: 'shard', scale: 1.3, pierce: 4, glow: true, trail: true }, viewmodel: vmdl(0x66ff88), projectileColor: 0x66ff88, impactColor: 0x66ff88, description: 'A heavy crossbow firing piercing bolts.', price: 460, unlockWave: 9, tags: ['precision', 'pierce', 'projectile'] });
R({ id: 'thermoLance2', name: 'Thermal Lance', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Beam, auto: false,
  damage: 80, damageType: DamageType.Fire, fireRate: 1.2, magazine: 12, reserveMax: 96, reloadTime: 2.0, spread: 0.0, range: 75, critChance: 0.18, critMult: 2.3, canHeadshot: true, knockback: 4, recoil: 1.8, screenShake: 0.1, sfx: 'shoot_laser', beam: { width: 0.16, tickRate: 0.1, color: 0xff6633 }, viewmodel: vmdl(0xff6633, 0.85), tracerColor: 0xff6633, impactColor: 0xff6633, statusChance: 0.6, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, description: 'A pinpoint thermal beam that ignites on contact.', price: 680, unlockWave: 14, tags: ['precision', 'beam', 'fire'] });
R({ id: 'repHunter2', name: 'Hunter Repeater', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 34, damageType: DamageType.Kinetic, fireRate: 3.5, magazine: 10, reserveMax: 80, reloadTime: 2.0, spread: 0.004, range: 82, falloffStart: 46, falloffEnd: 76, falloffMin: 0.78, critChance: 0.16, critMult: 2.1, canHeadshot: true, headshotMult: 1.9, knockback: 6, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_rifle', viewmodel: vmdl(0x4fd07a), tracerColor: 0x4fd07a, impactColor: 0x4fd07a, description: 'A full-auto heavy-caliber repeater. Sustained precision.', price: 420, unlockWave: 9, tags: ['precision', 'auto'] });
R({ id: 'shockLance2', name: 'Shock Lance', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 90, damageType: DamageType.Shock, fireRate: 1.0, magazine: 6, reserveMax: 48, reloadTime: 2.0, spread: 0.0, range: 85, critChance: 0.18, critMult: 2.3, canHeadshot: true, headshotMult: 2.1, knockback: 12, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, tracerWidth: 2, statusChance: 0.6, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, projectile: { pierce: 4 }, description: 'A rail-charged shock spear that pierces and stuns.', price: 700, unlockWave: 14, tags: ['precision', 'shock', 'pierce'] });
R({ id: 'voidRifle3', name: 'Void Rifle', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 120, damageType: DamageType.Energy, fireRate: 0.8, magazine: 5, reserveMax: 35, reloadTime: 2.4, spread: 0.0, range: 115, falloffStart: 72, falloffEnd: 105, falloffMin: 0.85, critChance: 0.3, critMult: 2.6, canHeadshot: true, headshotMult: 2.5, knockback: 16, recoil: 4.0, screenShake: 0.22, sfx: 'shoot_railgun', viewmodel: vmdl(0x8a5bff, 0.9), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, tracerWidth: 3, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, projectile: { pierce: 6 }, description: 'A void rifle that pierces ranks and marks survivors.', price: 720, unlockWave: 15, tags: ['precision', 'pierce', 'mark', 'high-damage'] });
R({ id: 'galGun2', name: 'Galileo', category: 'sniper', rarity: WeaponRarity.Mythic, fireMode: FireMode.Projectile, auto: false,
  damage: 160, damageType: DamageType.Energy, fireRate: 0.7, magazine: 4, reserveMax: 24, reloadTime: 2.6, spread: 0.0, range: 105, critChance: 0.28, critMult: 2.7, canHeadshot: true, headshotMult: 2.6, knockback: 22, recoil: 4.5, screenShake: 0.26, sfx: 'shoot_railgun', projectile: { speed: 82, gravity: 0, lifetime: 2, color: 0xffb347, radius: 0.22, shape: 'shard', scale: 1.6, pierce: 99, aoe: 3, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xffb347, 0.95), projectileColor: 0xffb347, impactColor: 0xffb347, description: 'A mythic hyper-velocity rail that pierces everything and detonates on each hit.', price: 900, unlockWave: 18, tags: ['precision', 'pierce', 'aoe', 'mythic', 'high-damage'] });
R({ id: 'phaser2', name: 'Phaser', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 70, damageType: DamageType.Energy, fireRate: 1.4, magazine: 8, reserveMax: 64, reloadTime: 1.8, spread: 0.0, range: 68, critChance: 0.2, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 6, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_laser', viewmodel: vmdl(0xff3df0), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2, statusChance: 0.4, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2, description: 'A phased beam rifle that slows targets on hit.', price: 460, unlockWave: 10, tags: ['precision', 'control'] });
R({ id: 'marksman4', name: 'Marksman Pro', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 75, damageType: DamageType.Kinetic, fireRate: 2.4, magazine: 12, reserveMax: 96, reloadTime: 1.8, spread: 0.001, range: 95, falloffStart: 55, falloffEnd: 88, falloffMin: 0.85, critChance: 0.24, critMult: 2.4, canHeadshot: true, headshotMult: 2.1, knockback: 8, recoil: 2.2, screenShake: 0.14, sfx: 'shoot_sniper', viewmodel: vmdl(0x9fe7ff, 0.85), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, description: 'A pro marksman rifle. The pinnacle of semi-auto precision.', price: 680, unlockWave: 14, tags: ['precision', 'semi'] });
R({ id: 'hunterRifle2', name: 'Hunter-X', category: 'sniper', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 52, damageType: DamageType.Kinetic, fireRate: 2.2, magazine: 8, reserveMax: 64, reloadTime: 1.8, spread: 0.002, range: 88, falloffStart: 50, falloffEnd: 80, falloffMin: 0.82, critChance: 0.17, critMult: 2.1, canHeadshot: true, headshotMult: 1.9, knockback: 7, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_sniper', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, description: 'An upgraded bolt-action hunter. Reliable precision.', price: 280, unlockWave: 6, tags: ['precision', 'semi'] });
