// ============================================================================
// precision.js — Marksman & sniper-class weapons: high damage, high crit,
// low fire rate. Reward accuracy and positioning.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  { id: 'marksman', name: 'Marksman', category: 'sniper', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false, damage: 55, damageType: DamageType.Kinetic, fireRate: 1.8, magazine: 8, reserveMax: 64, reloadTime: 1.8,
    spread: 0.002, range: 90, falloffStart: 50, falloffEnd: 85, falloffMin: 0.8, critChance: 0.18, critMult: 2.2, canHeadshot: true, headshotMult: 2.0,
    knockback: 8, recoil: 2.4, screenShake: 0.14, sfx: 'shoot_sniper',
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.8, shape: 'rifle' }, tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    description: 'Semi-auto marksman rifle. Punchy and precise.', price: 220, unlockWave: 3, tags: ['precision', 'semi'] },
  { id: 'crossbow', name: 'Arc Crossbow', category: 'sniper', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: false, damage: 85, damageType: DamageType.Kinetic, fireRate: 1.0, magazine: 5, reserveMax: 30, reloadTime: 2.2,
    spread: 0.0, range: 70, critChance: 0.2, critMult: 2.4, canHeadshot: true, headshotMult: 2.2, knockback: 14, recoil: 2.8, screenShake: 0.16, sfx: 'shoot_rifle',
    projectile: { speed: 70, gravity: 0.3, lifetime: 2, color: 0x66ff88, radius: 0.16, shape: 'shard', scale: 1.3, pierce: 3, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x66ff88, length: 0.8, shape: 'rifle' }, projectileColor: 0x66ff88, impactColor: 0x66ff88,
    description: 'Fires heavy piercing bolts. Travels and punches through foes.', price: 300, unlockWave: 5, tags: ['precision', 'pierce', 'projectile'] },
  { id: 'thermoLance', name: 'Thermal Lance', category: 'sniper', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: false, damage: 70, damageType: DamageType.Fire, fireRate: 1.4, magazine: 12, reserveMax: 96, reloadTime: 2.0,
    spread: 0.0, range: 70, critChance: 0.15, critMult: 2.3, canHeadshot: true, knockback: 4, recoil: 1.8, screenShake: 0.1, sfx: 'shoot_laser',
    beam: { width: 0.16, tickRate: 0.12, color: 0xff6633 }, viewmodel: { color: 0x223044, accent: 0xff6633, length: 0.85, shape: 'rifle' },
    tracerColor: 0xff6633, impactColor: 0xff6633, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3,
    description: 'A pinpoint thermal beam that ignites on contact.', price: 460, unlockWave: 9, tags: ['precision', 'beam', 'fire'] },
  { id: 'repHunter', name: 'Hunter Repeater', category: 'sniper', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: true, damage: 32, damageType: DamageType.Kinetic, fireRate: 3, magazine: 10, reserveMax: 80, reloadTime: 2.0,
    spread: 0.004, range: 80, falloffStart: 45, falloffEnd: 75, falloffMin: 0.75, critChance: 0.14, critMult: 2.1, canHeadshot: true, headshotMult: 1.9,
    knockback: 6, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_rifle', viewmodel: { color: 0x223044, accent: 0x4fd07a, length: 0.8, shape: 'rifle' },
    tracerColor: 0x4fd07a, impactColor: 0x4fd07a, description: 'Full-auto heavy-caliber repeater. Sustained precision.',
    price: 320, unlockWave: 6, tags: ['precision', 'auto'] },
  { id: 'shockLance', name: 'Shock Lance', category: 'sniper', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false, damage: 80, damageType: DamageType.Shock, fireRate: 1.1, magazine: 6, reserveMax: 48, reloadTime: 2.0,
    spread: 0.0, range: 80, critChance: 0.16, critMult: 2.3, canHeadshot: true, headshotMult: 2.1, knockback: 10, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_lightning',
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.85, shape: 'rifle' }, tracerColor: 0xffe066, impactColor: 0xffe066, tracerWidth: 2,
    statusChance: 0.5, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, projectile: { pierce: 3 },
    description: 'A rail-charged shock spear that pierces and stuns.', price: 460, unlockWave: 10, tags: ['precision', 'shock', 'pierce'] },
  { id: 'voidRifle', name: 'Void Rifle', category: 'sniper', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: false, damage: 110, damageType: DamageType.Energy, fireRate: 0.9, magazine: 5, reserveMax: 35, reloadTime: 2.4,
    spread: 0.0, range: 110, falloffStart: 70, falloffEnd: 100, falloffMin: 0.85, critChance: 0.28, critMult: 2.6, canHeadshot: true, headshotMult: 2.5,
    knockback: 14, recoil: 4.0, screenShake: 0.22, sfx: 'shoot_railgun', viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.9, shape: 'rifle' },
    tracerColor: 0x8a5bff, impactColor: 0x8a5bff, tracerWidth: 3, projectile: { pierce: 5 },
    statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3,
    description: 'A void-infused rifle that pierces ranks and marks survivors.', price: 680, unlockWave: 14, tags: ['precision', 'pierce', 'high-damage'] },
  { id: 'galGun', name: 'Galileo', category: 'sniper', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false, damage: 150, damageType: DamageType.Energy, fireRate: 0.8, magazine: 4, reserveMax: 24, reloadTime: 2.6,
    spread: 0.0, range: 100, critChance: 0.25, critMult: 2.7, canHeadshot: true, headshotMult: 2.6, knockback: 20, recoil: 4.5, screenShake: 0.26, sfx: 'shoot_railgun',
    projectile: { speed: 80, gravity: 0, lifetime: 2, color: 0xffb347, radius: 0.22, shape: 'shard', scale: 1.6, pierce: 99, aoe: 3, aoeFalloff: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffb347, length: 0.95, shape: 'rifle' }, projectileColor: 0xffb347, impactColor: 0xffb347,
    description: 'A hyper-velocity rail that pierces everything and detonates on each hit.', price: 720, unlockWave: 15, tags: ['precision', 'pierce', 'aoe', 'high-damage'] },
  { id: 'phaser', name: 'Phaser', category: 'sniper', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false, damage: 65, damageType: DamageType.Energy, fireRate: 1.6, magazine: 8, reserveMax: 64, reloadTime: 1.8,
    spread: 0.0, range: 65, critChance: 0.18, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 6, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_laser',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.8, shape: 'rifle' }, tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2,
    statusChance: 0.4, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2,
    description: 'A phased beam rifle that slows targets on hit.', price: 420, unlockWave: 9, tags: ['precision', 'control'] },
]);
