// ============================================================================
// rifles2.js — A large roster of assault & battle rifles covering a range of
// fire rates, damage profiles, and elemental variants.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'rifle', len = 0.7) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'pulseRifle2', name: 'Pulse Rifle Mk2', category: 'rifle', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: true,
  damage: 15, damageType: DamageType.Kinetic, fireRate: 9, magazine: 32, reserveMax: 224, reloadTime: 1.7, spread: 0.009, range: 65, falloffStart: 38, falloffEnd: 60, falloffMin: 0.72, critChance: 0.07, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.1, screenShake: 0.05, sfx: 'shoot_rifle', viewmodel: vmdl(0x4aa3ff), tracerColor: 0x9fd0ff, impactColor: 0x4aa3ff, description: 'An upgraded pulse rifle. Smooth, steady, deadly.', price: 280, unlockWave: 4, tags: ['auto', 'versatile'] });
R({ id: 'arcRifle', name: 'Arc Rifle', category: 'rifle', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 14, damageType: DamageType.Shock, fireRate: 8, magazine: 28, reserveMax: 196, reloadTime: 1.8, spread: 0.01, range: 55, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.35, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, projectile: { pierce: 1 }, description: 'A shock rifle. Rounds arc through one foe and stun.', price: 420, unlockWave: 8, tags: ['auto', 'shock', 'pierce'] });
R({ id: 'emberRifle', name: 'Ember Rifle', category: 'rifle', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 14, damageType: DamageType.Fire, fireRate: 8, magazine: 28, reserveMax: 196, reloadTime: 1.8, spread: 0.01, range: 55, critChance: 0.08, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.35, statusType: StatusType.Burn, statusPower: 1, statusDuration: 2, description: 'An incendiary rifle. Rounds ignite on hit.', price: 420, unlockWave: 8, tags: ['auto', 'fire', 'status'] });
R({ id: 'frostRifle', name: 'Frost Rifle', category: 'rifle', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 14, damageType: DamageType.Cryo, fireRate: 8, magazine: 28, reserveMax: 196, reloadTime: 1.8, spread: 0.01, range: 55, critChance: 0.08, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_laser', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.35, statusType: StatusType.Slow, statusPower: 1, statusDuration: 2, description: 'A cryo rifle. Rounds chill and slow.', price: 420, unlockWave: 8, tags: ['auto', 'cryo', 'control'] });
R({ id: 'voidRifle2', name: 'Null Rifle', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 22, damageType: DamageType.Energy, fireRate: 7, magazine: 24, reserveMax: 168, reloadTime: 1.9, spread: 0.006, range: 65, critChance: 0.16, critMult: 2.3, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_railgun', viewmodel: vmdl(0x8a5bff), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.3, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, projectile: { pierce: 2 }, description: 'A null rifle. Void rounds pierce and mark.', price: 640, unlockWave: 13, tags: ['auto', 'pierce', 'mark', 'energy'] });
R({ id: 'plasmaRifle2', name: 'Storm Rifle', category: 'rifle', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: true,
  damage: 20, damageType: DamageType.Energy, fireRate: 8, magazine: 26, reserveMax: 182, reloadTime: 1.8, spread: 0.014, range: 55, critChance: 0.09, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 60, gravity: 0, lifetime: 2, color: 0x29e7ff, radius: 0.16, shape: 'orb', scale: 1, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A storm rifle. Rapid plasma orbs with travel time.', price: 420, unlockWave: 8, tags: ['auto', 'energy', 'projectile'] });
R({ id: 'burstRifle', name: 'Hammerburst', category: 'rifle', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false, burst: 4, burstDelay: 0.05,
  damage: 14, damageType: DamageType.Kinetic, fireRate: 3.5, magazine: 24, reserveMax: 168, reloadTime: 1.8, spread: 0.007, range: 60, falloffStart: 35, falloffEnd: 55, falloffMin: 0.75, critChance: 0.09, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.3, screenShake: 0.06, sfx: 'shoot_rifle', viewmodel: vmdl(0xffb347), tracerColor: 0xffd28a, impactColor: 0xffb347, description: 'A 4-round-burst rifle. Disciplined bursts, high output.', price: 280, unlockWave: 5, tags: ['burst', 'versatile'] });
R({ id: 'beamRifle', name: 'Lancer Beam', category: 'rifle', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: true,
  damage: 16, damageType: DamageType.Energy, fireRate: 12, magazine: 100, reserveMax: 0, reloadTime: 2.0, spread: 0.0, range: 50, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 1, recoil: 0.4, screenShake: 0.03, sfx: 'shoot_laser', beam: { width: 0.1, tickRate: 0.07, color: 0x29e7ff }, viewmodel: vmdl(0x29e7ff), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A beam rifle. Sustained energy DPS, no reserve ammo.', price: 440, unlockWave: 9, tags: ['beam', 'sustained', 'energy'] });
R({ id: 'gaussRifle', name: 'Gauss Rifle', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 90, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 8, reserveMax: 56, reloadTime: 2.0, spread: 0.002, range: 100, falloffStart: 60, falloffEnd: 95, falloffMin: 0.85, critChance: 0.22, critMult: 2.6, canHeadshot: true, headshotMult: 2.4, knockback: 12, recoil: 3.5, screenShake: 0.2, sfx: 'shoot_railgun', viewmodel: vmdl(0xff3df0, 'rifle', 0.85), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 3, projectile: { pierce: 4 }, description: 'A gauss rifle. Hyper-velocity rounds pierce ranks.', price: 680, unlockWave: 14, tags: ['precision', 'pierce', 'high-damage'] });
R({ id: 'tracerRifle', name: 'Tracer Rifle', category: 'rifle', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: true,
  damage: 12, damageType: DamageType.Kinetic, fireRate: 11, magazine: 30, reserveMax: 210, reloadTime: 1.6, spread: 0.011, range: 50, falloffStart: 25, falloffEnd: 45, falloffMin: 0.7, critChance: 0.06, critMult: 1.9, canHeadshot: true, knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_rifle', viewmodel: vmdl(0x4fd07a), tracerColor: 0xbfe7a0, impactColor: 0x4fd07a, description: 'A tracer rifle. Visible streaks help you walk fire.', price: 220, unlockWave: 3, tags: ['auto', 'versatile'] });
R({ id: 'hellfireRifle', name: 'Hellfire', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 18, damageType: DamageType.Fire, fireRate: 9, magazine: 30, reserveMax: 210, reloadTime: 1.8, spread: 0.009, range: 55, critChance: 0.12, critMult: 2.2, canHeadshot: true, knockback: 3, recoil: 1.1, screenShake: 0.05, sfx: 'shoot_plasma', viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, lifesteal: 0.03, description: 'A hellfire rifle. Burns, leeches, and shreds.', price: 640, unlockWave: 13, tags: ['auto', 'fire', 'lifesteal'] });
R({ id: 'cryoRifle2', name: 'Avalanche', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 18, damageType: DamageType.Cryo, fireRate: 9, magazine: 30, reserveMax: 210, reloadTime: 1.8, spread: 0.009, range: 55, critChance: 0.12, critMult: 2.2, canHeadshot: true, knockback: 3, recoil: 1.1, screenShake: 0.05, sfx: 'shoot_laser', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'An avalanche rifle. Freezes targets solid.', price: 640, unlockWave: 13, tags: ['auto', 'cryo', 'control'] });
R({ id: 'shockRifle2', name: 'Thunder', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 18, damageType: DamageType.Shock, fireRate: 9, magazine: 30, reserveMax: 210, reloadTime: 1.8, spread: 0.009, range: 55, critChance: 0.12, critMult: 2.2, canHeadshot: true, knockback: 3, recoil: 1.1, screenShake: 0.05, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, projectile: { pierce: 2 }, description: 'A thunder rifle. Shocks, pierces, and chains.', price: 640, unlockWave: 13, tags: ['auto', 'shock', 'pierce'] });
R({ id: 'matchRifle', name: 'Match Rifle', category: 'rifle', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 35, damageType: DamageType.Kinetic, fireRate: 3, magazine: 12, reserveMax: 96, reloadTime: 1.8, spread: 0.003, range: 80, falloffStart: 45, falloffEnd: 75, falloffMin: 0.8, critChance: 0.14, critMult: 2.2, canHeadshot: true, headshotMult: 2.0, knockback: 6, recoil: 1.8, screenShake: 0.1, sfx: 'shoot_sniper', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fd0ff, impactColor: 0x9fe7ff, description: 'A match rifle. Semi-auto precision for mid-range.', price: 300, unlockWave: 6, tags: ['precision', 'semi'] });
R({ id: 'stormRifle2', name: 'Tempest Rifle', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: true,
  damage: 16, damageType: DamageType.Shock, fireRate: 7, magazine: 24, reserveMax: 168, reloadTime: 1.9, spread: 0.016, range: 50, critChance: 0.1, critMult: 2.1, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_lightning', projectile: { speed: 48, gravity: 0, lifetime: 2, color: 0xffe066, radius: 0.18, shape: 'shard', scale: 1, homing: 0.3, glow: true, trail: true }, viewmodel: vmdl(0xffe066), projectileColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 2, description: 'A tempest rifle. Homing lightning shards.', price: 620, unlockWave: 12, tags: ['auto', 'homing', 'shock', 'projectile'] });
