// ============================================================================
// shotguns2.js — A large roster of shotguns: pumps, autos, doubles, slugs,
// and elemental variants for close-range devastation.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent) => ({ color: 0x223044, accent, length: 0.6, shape: 'shotgun' });

R({ id: 'pumpShotgun', name: 'Pump Shotgun', category: 'shotgun', rarity: WeaponRarity.Common, fireMode: FireMode.Hitscan, auto: false,
  damage: 8, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 1.6, pellets: 8, spread: 0.09, range: 16, falloffStart: 7, falloffEnd: 14, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 8, recoil: 2.2, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0x9fb3d6), tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A pump shotgun. Classic close-range punch.', price: 140, unlockWave: 2, tags: ['close', 'crowd', 'knockback'] });
R({ id: 'tacticalShotgun', name: 'Tactical Shotgun', category: 'shotgun', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 1.6, magazine: 8, reserveMax: 48, reloadTime: 1.8, pellets: 9, spread: 0.08, range: 18, falloffStart: 8, falloffEnd: 16, falloffMin: 0.35, critChance: 0.06, critMult: 1.7, canHeadshot: false, knockback: 8, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0x4fd07a), tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A tactical shotgun. Tighter spread, faster handling.', price: 200, unlockWave: 4, tags: ['close', 'crowd'] });
R({ id: 'heavyShotgun', name: 'Heavy Shotgun', category: 'shotgun', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 11, damageType: DamageType.Kinetic, fireRate: 1.0, magazine: 5, reserveMax: 30, reloadTime: 2.0, pellets: 10, spread: 0.1, range: 18, falloffStart: 8, falloffEnd: 16, falloffMin: 0.3, critChance: 0.06, critMult: 1.7, canHeadshot: false, knockback: 12, recoil: 3.0, screenShake: 0.22, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xff5544), tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'A heavy shotgun. More pellets, more kick, more knockback.', price: 280, unlockWave: 6, tags: ['close', 'crowd', 'knockback'] });
R({ id: 'autoShotgun2', name: 'Storm Shotgun', category: 'shotgun', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 7, damageType: DamageType.Kinetic, fireRate: 4, magazine: 14, reserveMax: 84, reloadTime: 2.4, pellets: 8, spread: 0.08, range: 16, falloffStart: 7, falloffEnd: 14, falloffMin: 0.35, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 7, recoil: 1.6, screenShake: 0.12, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xff3df0), tracerColor: 0xffd28a, impactColor: 0xff3df0, description: 'A full-auto storm shotgun. A wall of lead at high cadence.', price: 640, unlockWave: 12, tags: ['close', 'crowd', 'auto'] });
R({ id: 'fireShotgun', name: 'Dragon Breath', category: 'shotgun', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 8, damageType: DamageType.Fire, fireRate: 1.4, magazine: 6, reserveMax: 36, reloadTime: 1.8, pellets: 8, spread: 0.1, range: 15, falloffStart: 6, falloffEnd: 13, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 6, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.5, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, description: 'A dragon-breath shotgun. Pellets ignite on hit.', price: 420, unlockWave: 8, tags: ['close', 'crowd', 'fire', 'status'] });
R({ id: 'frostShotgun', name: 'Frost Shotgun', category: 'shotgun', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 8, damageType: DamageType.Cryo, fireRate: 1.4, magazine: 6, reserveMax: 36, reloadTime: 1.8, pellets: 8, spread: 0.1, range: 15, falloffStart: 6, falloffEnd: 13, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 6, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2, description: 'A frost shotgun. Pellets chill and slow.', price: 420, unlockWave: 8, tags: ['close', 'crowd', 'cryo', 'control'] });
R({ id: 'shockShotgun', name: 'Arc Shotgun', category: 'shotgun', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 8, damageType: DamageType.Shock, fireRate: 1.4, magazine: 6, reserveMax: 36, reloadTime: 1.8, pellets: 8, spread: 0.1, range: 15, falloffStart: 6, falloffEnd: 13, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 6, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_lightning', recoilPattern: 'random', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.5, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, description: 'An arc shotgun. Pellets shock on hit.', price: 420, unlockWave: 8, tags: ['close', 'crowd', 'shock', 'status'] });
R({ id: 'combatShotgun', name: 'Combat Shotgun', category: 'shotgun', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 1.8, magazine: 8, reserveMax: 56, reloadTime: 1.6, pellets: 8, spread: 0.085, range: 18, falloffStart: 8, falloffEnd: 16, falloffMin: 0.35, critChance: 0.06, critMult: 1.7, canHeadshot: false, knockback: 9, recoil: 2.0, screenShake: 0.16, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0x4aa3ff), tracerColor: 0xffd28a, impactColor: 0x4aa3ff, description: 'A combat shotgun. Balanced rate and punch.', price: 220, unlockWave: 4, tags: ['close', 'crowd'] });
R({ id: 'leverShotgun', name: 'Lever Shotgun', category: 'shotgun', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 10, damageType: DamageType.Kinetic, fireRate: 1.4, magazine: 7, reserveMax: 42, reloadTime: 1.8, pellets: 9, spread: 0.085, range: 19, falloffStart: 8, falloffEnd: 17, falloffMin: 0.35, critChance: 0.07, critMult: 1.7, canHeadshot: false, knockback: 9, recoil: 2.2, screenShake: 0.18, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xffb347), tracerColor: 0xffd28a, impactColor: 0xffb347, description: 'A lever-action shotgun. Classic feel, solid output.', price: 260, unlockWave: 5, tags: ['close', 'crowd'] });
R({ id: 'autoSlug', name: 'Auto Slugger', category: 'shotgun', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 35, damageType: DamageType.Kinetic, fireRate: 2.5, magazine: 8, reserveMax: 48, reloadTime: 2.0, spread: 0.01, range: 30, falloffStart: 14, falloffEnd: 28, falloffMin: 0.6, critChance: 0.1, critMult: 1.9, canHeadshot: true, knockback: 12, recoil: 1.8, screenShake: 0.12, sfx: 'shoot_shotgun', viewmodel: vmdl(0xff5544), tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'An auto-slugger. Full-auto sabot slugs with range.', price: 440, unlockWave: 9, tags: ['close', 'precision', 'auto', 'knockback'] });
R({ id: 'quadBarrel', name: 'Quad Barrel', category: 'shotgun', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false, burst: 4, burstDelay: 0.08,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 0.8, magazine: 4, reserveMax: 16, reloadTime: 2.4, pellets: 12, spread: 0.11, range: 16, falloffStart: 6, falloffEnd: 14, falloffMin: 0.3, critChance: 0.06, critMult: 1.7, canHeadshot: false, knockback: 14, recoil: 3.0, screenShake: 0.24, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xff3df0), tracerColor: 0xffd28a, impactColor: 0xff3df0, description: 'A quad-barrel. Dump all four barrels in one trigger pull.', price: 600, unlockWave: 12, tags: ['close', 'burst', 'crowd', 'knockback'] });
R({ id: 'plasmaShotgun', name: 'Plasma Shotgun', category: 'shotgun', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 16, damageType: DamageType.Energy, fireRate: 1.4, magazine: 8, reserveMax: 48, reloadTime: 2.0, pellets: 6, spread: 0.07, range: 22, critChance: 0.08, critMult: 1.9, canHeadshot: false, knockback: 8, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_plasma', projectile: { speed: 40, gravity: 0, lifetime: 1.2, color: 0x29e7ff, radius: 0.16, shape: 'orb', scale: 0.9, aoe: 1.5, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A plasma shotgun. Energy pellets with mini-splash.', price: 620, unlockWave: 12, tags: ['close', 'energy', 'aoe', 'crowd'] });
