// ============================================================================
// sidearms.js — A large roster of sidearms & pistols: the player's reliable
// backup category. Each has a distinct handling profile, from fast peashooters
// to heavy hand cannons and elemental sidearms.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  { id: 'peashooter', name: 'Peashooter', category: 'sidearm', rarity: WeaponRarity.Common,
    fireMode: FireMode.Hitscan, auto: false, damage: 12, damageType: DamageType.Kinetic, fireRate: 7, magazine: 16, reserveMax: 128, reloadTime: 1.0,
    spread: 0.005, range: 50, falloffStart: 25, falloffEnd: 45, falloffMin: 0.65, critChance: 0.06, critMult: 1.8, canHeadshot: true,
    knockback: 2, recoil: 0.7, screenShake: 0.04, sfx: 'shoot_pistol', viewmodel: { color: 0x223044, accent: 0x9fb3d6, length: 0.45, shape: 'pistol' },
    tracerColor: 0xffe08a, impactColor: 0xffe08a, description: 'A featherlight peashooter. Fast, weak, endless.', price: 0, unlockWave: 0, tags: ['starter', 'fast'] },
  { id: 'revolver', name: 'Revolver', category: 'sidearm', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false, damage: 38, damageType: DamageType.Kinetic, fireRate: 2.4, magazine: 6, reserveMax: 48, reloadTime: 1.6,
    spread: 0.008, range: 55, falloffStart: 28, falloffEnd: 50, falloffMin: 0.7, critChance: 0.12, critMult: 2.2, canHeadshot: true, headshotMult: 1.9,
    knockback: 8, recoil: 1.8, screenShake: 0.12, sfx: 'shoot_sniper', viewmodel: { color: 0x223044, accent: 0xffb347, length: 0.5, shape: 'pistol' },
    tracerColor: 0xffd28a, impactColor: 0xffb347, description: 'A classic revolver. Six hard-hitting rounds.', price: 140, unlockWave: 2, tags: ['precision', 'high-damage'] },
  { id: 'machinePistol', name: 'Machine Pistol', category: 'sidearm', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: true, damage: 8, damageType: DamageType.Kinetic, fireRate: 13, magazine: 24, reserveMax: 192, reloadTime: 1.3,
    spread: 0.02, range: 32, falloffStart: 14, falloffEnd: 28, falloffMin: 0.55, critChance: 0.05, critMult: 1.7, canHeadshot: true,
    knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: { color: 0x223044, accent: 0x4fd07a, length: 0.45, shape: 'pistol' },
    tracerColor: 0xbfe7a0, impactColor: 0xbfe7a0, description: 'A full-auto machine pistol. Pocket SMG.', price: 160, unlockWave: 2, tags: ['auto', 'close'] },
  { id: 'flareGun', name: 'Flare Gun', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: false, damage: 45, damageType: DamageType.Fire, fireRate: 1.2, magazine: 4, reserveMax: 24, reloadTime: 1.8,
    spread: 0.02, range: 40, critChance: 0.08, critMult: 2.0, canHeadshot: false, knockback: 6, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_plasma',
    projectile: { speed: 34, gravity: 0.3, lifetime: 2.5, color: 0xff5522, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 3, aoeFalloff: 0.4, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff5522, length: 0.45, shape: 'pistol' }, projectileColor: 0xff5522, impactColor: 0xff5522,
    statusChance: 0.6, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3,
    description: 'A flare gun. Lobs burning projectiles that ignite areas.', price: 240, unlockWave: 5, tags: ['projectile', 'fire', 'aoe'] },
  { id: 'shockPistol', name: 'Shock Pistol', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false, damage: 26, damageType: DamageType.Shock, fireRate: 3, magazine: 10, reserveMax: 80, reloadTime: 1.2,
    spread: 0.006, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 5, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_lightning',
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.5, shape: 'pistol' }, tracerColor: 0xffe066, impactColor: 0xffe066,
    statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, projectile: { pierce: 1 },
    description: 'A shock pistol. Bolts pierce one foe and stun.', price: 240, unlockWave: 5, tags: ['precision', 'shock', 'pierce'] },
  { id: 'icePistol', name: 'Cryo Pistol', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: false, damage: 22, damageType: DamageType.Cryo, fireRate: 3.5, magazine: 12, reserveMax: 96, reloadTime: 1.2,
    spread: 0.01, range: 40, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 3, recoil: 0.9, screenShake: 0.05, sfx: 'shoot_plasma',
    projectile: { speed: 48, gravity: 0, lifetime: 2, color: 0x9fe7ff, radius: 0.18, shape: 'orb', scale: 1, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x9fe7ff, length: 0.5, shape: 'pistol' }, projectileColor: 0x9fe7ff, impactColor: 0x9fe7ff,
    statusChance: 0.5, statusType: StatusType.Slow, statusPower: 1, statusDuration: 2,
    description: 'A cryo pistol. Frost rounds that chill targets.', price: 240, unlockWave: 5, tags: ['projectile', 'cryo', 'control'] },
  { id: 'magnum', name: 'Magnum', category: 'sidearm', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false, damage: 70, damageType: DamageType.Kinetic, fireRate: 1.4, magazine: 5, reserveMax: 30, reloadTime: 1.6,
    spread: 0.006, range: 60, falloffStart: 30, falloffEnd: 55, falloffMin: 0.75, critChance: 0.18, critMult: 2.5, canHeadshot: true, headshotMult: 2.2,
    knockback: 12, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_sniper', viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.55, shape: 'pistol' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2, description: 'A heavy magnum. Hand-cannon headshots delete elites.',
    price: 380, unlockWave: 8, tags: ['precision', 'high-damage', 'knockback'] },
  { id: 'burstPistol', name: 'Burst Pistol', category: 'sidearm', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false, burst: 3, burstDelay: 0.05, damage: 14, damageType: DamageType.Kinetic, fireRate: 4, magazine: 18, reserveMax: 144, reloadTime: 1.3,
    spread: 0.008, range: 48, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_pistol',
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.5, shape: 'pistol' }, tracerColor: 0x9fd0ff, impactColor: 0x29e7ff,
    description: 'A 3-round-burst pistol. Crisp and rhythmic.', price: 180, unlockWave: 3, tags: ['burst', 'precision'] },
  { id: 'plasmaPistol', name: 'Plasma Pistol', category: 'sidearm', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Projectile, auto: false, damage: 24, damageType: DamageType.Energy, fireRate: 4, magazine: 16, reserveMax: 128, reloadTime: 1.3,
    spread: 0.012, range: 45, critChance: 0.08, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma',
    projectile: { speed: 50, gravity: 0, lifetime: 2, color: 0x29e7ff, radius: 0.16, shape: 'orb', scale: 0.9, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.5, shape: 'energy' }, projectileColor: 0x29e7ff, impactColor: 0x29e7ff,
    description: 'A plasma pistol. Energy orbs with travel time.', price: 200, unlockWave: 4, tags: ['projectile', 'energy'] },
  { id: 'needlePistol', name: 'Needler', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: true, damage: 11, damageType: DamageType.Kinetic, fireRate: 10, magazine: 20, reserveMax: 160, reloadTime: 1.2,
    spread: 0.004, range: 50, critChance: 0.12, critMult: 2.0, canHeadshot: true, headshotMult: 1.8, knockback: 2, recoil: 0.7, screenShake: 0.04, sfx: 'shoot_smg',
    viewmodel: { color: 0x223044, accent: 0x4fffd0, length: 0.5, shape: 'pistol' }, tracerColor: 0x4fffd0, impactColor: 0x4fffd0,
    statusChance: 0.3, statusType: StatusType.Bleed, statusPower: 1, statusDuration: 2,
    description: 'A needler. Tiny precise needles that cause bleed.', price: 240, unlockWave: 5, tags: ['auto', 'precision', 'status'] },
  { id: 'blunderbuss', name: 'Blunderbuss', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false, damage: 9, damageType: DamageType.Kinetic, fireRate: 1.6, magazine: 4, reserveMax: 32, reloadTime: 1.5,
    pellets: 6, spread: 0.12, range: 12, falloffStart: 5, falloffEnd: 11, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false,
    knockback: 9, recoil: 2.2, screenShake: 0.14, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: { color: 0x223044, accent: 0xffaa44, length: 0.5, shape: 'pistol' },
    tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A pocket blunderbuss. A fan of lead up close.', price: 220, unlockWave: 4, tags: ['close', 'crowd', 'knockback'] },
  { id: 'boltPistol', name: 'Bolt Pistol', category: 'sidearm', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false, damage: 50, damageType: DamageType.Energy, fireRate: 2, magazine: 8, reserveMax: 64, reloadTime: 1.5,
    spread: 0.004, range: 60, critChance: 0.15, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 7, recoil: 1.8, screenShake: 0.12, sfx: 'shoot_railgun',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.55, shape: 'pistol' }, tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2,
    statusChance: 0.3, statusType: StatusType.Mark, statusPower: 1, statusDuration: 3, projectile: { pierce: 2 },
    description: 'A bolt pistol. Energy bolts that pierce and mark.', price: 380, unlockWave: 8, tags: ['precision', 'pierce', 'energy'] },
  { id: 'silencedPistol', name: 'Silenced Pistol', category: 'sidearm', rarity: WeaponRarity.Uncommon,
    fireMode: FireMode.Hitscan, auto: false, damage: 20, damageType: DamageType.Kinetic, fireRate: 5, magazine: 12, reserveMax: 96, reloadTime: 1.1,
    spread: 0.003, range: 52, critChance: 0.14, critMult: 2.1, canHeadshot: true, headshotMult: 2.0, knockback: 2, recoil: 0.6, screenShake: 0.03, sfx: 'shoot_pistol',
    viewmodel: { color: 0x223044, accent: 0x6f86a8, length: 0.5, shape: 'pistol' }, tracerColor: 0xcfe6ff, impactColor: 0x9fb3d6,
    description: 'A silenced pistol. Quiet, precise, high headshot crit.', price: 180, unlockWave: 3, tags: ['precision', 'stealth'] },
  { id: 'plasmaRevolver', name: 'Plasma Revolver', category: 'sidearm', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false, damage: 55, damageType: DamageType.Energy, fireRate: 1.8, magazine: 6, reserveMax: 48, reloadTime: 1.7,
    spread: 0.005, range: 55, critChance: 0.14, critMult: 2.3, canHeadshot: true, knockback: 8, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_plasma',
    projectile: { speed: 55, gravity: 0, lifetime: 2, color: 0xff3df0, radius: 0.2, shape: 'orb', scale: 1.3, aoe: 2, aoeFalloff: 0.5, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.55, shape: 'pistol' }, projectileColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'A plasma revolver. Energy rounds with a small splash.', price: 400, unlockWave: 8, tags: ['precision', 'energy', 'aoe'] },
  { id: 'twinPistol', name: 'Twin Pistols', category: 'sidearm', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true, damage: 16, damageType: DamageType.Kinetic, fireRate: 8, magazine: 24, reserveMax: 192, reloadTime: 1.5,
    spread: 0.01, range: 45, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 0.9, screenShake: 0.05, sfx: 'shoot_pistol',
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.5, shape: 'pistol' }, tracerColor: 0x9fd0ff, impactColor: 0x29e7ff,
    description: 'Akimbo twin pistols. Double the barrels, double the rate.', price: 380, unlockWave: 8, tags: ['auto', 'crowd'] },
]);
