// ============================================================================
// weapons/definitions/sidearms2.js — More sidearms & pistols for backup
// variety across all rarities.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent) => ({ color: 0x223044, accent, length: 0.5, shape: 'pistol' });

R({ id: 'peaShooter2', name: 'Pea Shooter', category: 'sidearm', rarity: WeaponRarity.Common, fireMode: FireMode.Hitscan, auto: false,
  damage: 10, damageType: DamageType.Kinetic, fireRate: 8, magazine: 18, reserveMax: 144, reloadTime: 0.9, spread: 0.004, range: 45, falloffStart: 22, falloffEnd: 40, falloffMin: 0.65, critChance: 0.05, critMult: 1.7, canHeadshot: true, knockback: 1, recoil: 0.5, screenShake: 0.03, sfx: 'shoot_pistol', viewmodel: vmdl(0x9fb3d6), tracerColor: 0xffe08a, impactColor: 0xffe08a, description: 'A featherlight pea shooter. Fast and endless.', price: 0, unlockWave: 0, tags: ['starter', 'fast'] });
R({ id: 'revolver2', name: 'Revolver-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 42, damageType: DamageType.Kinetic, fireRate: 2.2, magazine: 6, reserveMax: 48, reloadTime: 1.5, spread: 0.007, range: 58, falloffStart: 30, falloffEnd: 52, falloffMin: 0.72, critChance: 0.14, critMult: 2.2, canHeadshot: true, headshotMult: 2.0, knockback: 9, recoil: 1.8, screenShake: 0.13, sfx: 'shoot_sniper', viewmodel: vmdl(0xffb347), tracerColor: 0xffd28a, impactColor: 0xffb347, description: 'A classic revolver. Six hard-hitting rounds.', price: 240, unlockWave: 5, tags: ['precision', 'high-damage'] });
R({ id: 'machinePistol2', name: 'Machine Pistol-X', category: 'sidearm', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: true,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 15, magazine: 28, reserveMax: 224, reloadTime: 1.2, spread: 0.018, range: 34, falloffStart: 14, falloffEnd: 30, falloffMin: 0.55, critChance: 0.05, critMult: 1.7, canHeadshot: true, knockback: 1, recoil: 0.7, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: vmdl(0x4fd07a), tracerColor: 0xbfe7a0, impactColor: 0xbfe7a0, description: 'A full-auto machine pistol. Pocket SMG.', price: 180, unlockWave: 3, tags: ['auto', 'close'] });
R({ id: 'flareGun2', name: 'Flare Gun-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Projectile, auto: false,
  damage: 50, damageType: DamageType.Fire, fireRate: 1.0, magazine: 4, reserveMax: 24, reloadTime: 1.6, spread: 0.02, range: 42, critChance: 0.08, critMult: 2.0, canHeadshot: false, knockback: 6, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_plasma', projectile: { speed: 36, gravity: 0.3, lifetime: 2.5, color: 0xff5522, radius: 0.22, shape: 'orb', scale: 1.2, aoe: 3, aoeFalloff: 0.4, glow: true, trail: true }, viewmodel: vmdl(0xff5522), projectileColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.6, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3, description: 'A flare gun. Lobs burning projectiles that ignite areas.', price: 260, unlockWave: 6, tags: ['projectile', 'fire', 'aoe'] });
R({ id: 'shockPistol2', name: 'Shock Pistol-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 28, damageType: DamageType.Shock, fireRate: 2.8, magazine: 10, reserveMax: 80, reloadTime: 1.1, spread: 0.005, range: 48, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 5, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.4, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, projectile: { pierce: 1 }, description: 'A shock pistol. Bolts pierce one foe and stun.', price: 260, unlockWave: 6, tags: ['precision', 'shock', 'pierce'] });
R({ id: 'icePistol2', name: 'Cryo Pistol-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Projectile, auto: false,
  damage: 24, damageType: DamageType.Cryo, fireRate: 3.2, magazine: 12, reserveMax: 96, reloadTime: 1.1, spread: 0.01, range: 42, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 3, recoil: 0.9, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 50, gravity: 0, lifetime: 2, color: 0x9fe7ff, radius: 0.18, shape: 'orb', scale: 1, glow: true, trail: true }, viewmodel: vmdl(0x9fe7ff), projectileColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.5, statusType: StatusType.Slow, statusPower: 1, statusDuration: 2, description: 'A cryo pistol. Frost rounds that chill targets.', price: 260, unlockWave: 6, tags: ['projectile', 'cryo', 'control'] });
R({ id: 'magnum2', name: 'Magnum-X', category: 'sidearm', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 80, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 5, reserveMax: 30, reloadTime: 1.5, spread: 0.005, range: 65, falloffStart: 32, falloffEnd: 58, falloffMin: 0.78, critChance: 0.2, critMult: 2.5, canHeadshot: true, headshotMult: 2.3, knockback: 14, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_sniper', viewmodel: vmdl(0xff3df0), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2, description: 'A heavy magnum. Hand-cannon headshots delete elites.', price: 420, unlockWave: 9, tags: ['precision', 'high-damage', 'knockback'] });
R({ id: 'burstPistol2', name: 'Burst Pistol-X', category: 'sidearm', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false, burst: 3, burstDelay: 0.05,
  damage: 15, damageType: DamageType.Kinetic, fireRate: 4, magazine: 18, reserveMax: 144, reloadTime: 1.2, spread: 0.007, range: 50, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_pistol', viewmodel: vmdl(0x29e7ff), tracerColor: 0x9fd0ff, impactColor: 0x29e7ff, description: 'A 3-round-burst pistol. Crisp and rhythmic.', price: 200, unlockWave: 4, tags: ['burst', 'precision'] });
R({ id: 'plasmaPistol2', name: 'Plasma Pistol-X', category: 'sidearm', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Projectile, auto: false,
  damage: 26, damageType: DamageType.Energy, fireRate: 4, magazine: 16, reserveMax: 128, reloadTime: 1.2, spread: 0.012, range: 48, critChance: 0.08, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_plasma', projectile: { speed: 52, gravity: 0, lifetime: 2, color: 0x29e7ff, radius: 0.16, shape: 'orb', scale: 0.9, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff, 'energy'), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A plasma pistol. Energy orbs with travel time.', price: 220, unlockWave: 5, tags: ['projectile', 'energy'] });
R({ id: 'needlePistol2', name: 'Needler-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: true,
  damage: 12, damageType: DamageType.Kinetic, fireRate: 11, magazine: 20, reserveMax: 160, reloadTime: 1.1, spread: 0.003, range: 52, critChance: 0.13, critMult: 2.0, canHeadshot: true, headshotMult: 1.8, knockback: 2, recoil: 0.7, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: vmdl(0x4fffd0), tracerColor: 0x4fffd0, impactColor: 0x4fffd0, statusChance: 0.3, statusType: StatusType.Bleed, statusPower: 1, statusDuration: 2, description: 'A needler. Tiny precise needles that cause bleed.', price: 260, unlockWave: 6, tags: ['auto', 'precision', 'status'] });
R({ id: 'blunderbuss2', name: 'Blunderbuss-X', category: 'sidearm', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: false,
  damage: 10, damageType: DamageType.Kinetic, fireRate: 1.4, magazine: 4, reserveMax: 32, reloadTime: 1.4, pellets: 7, spread: 0.12, range: 13, falloffStart: 5, falloffEnd: 12, falloffMin: 0.3, critChance: 0.05, critMult: 1.6, canHeadshot: false, knockback: 10, recoil: 2.2, screenShake: 0.14, sfx: 'shoot_shotgun', recoilPattern: 'random', viewmodel: vmdl(0xffaa44), tracerColor: 0xffd28a, impactColor: 0xffaa44, description: 'A pocket blunderbuss. A fan of lead up close.', price: 240, unlockWave: 5, tags: ['close', 'crowd', 'knockback'] });
R({ id: 'boltPistol2', name: 'Bolt Pistol-X', category: 'sidearm', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 55, damageType: DamageType.Energy, fireRate: 1.8, magazine: 8, reserveMax: 64, reloadTime: 1.4, spread: 0.003, range: 65, critChance: 0.16, critMult: 2.3, canHeadshot: true, headshotMult: 2.0, knockback: 7, recoil: 1.8, screenShake: 0.12, sfx: 'shoot_railgun', viewmodel: vmdl(0xff3df0), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 2, statusChance: 0.3, statusType: StatusType.Mark, statusPower: 1, statusDuration: 3, projectile: { pierce: 2 }, description: 'A bolt pistol. Energy bolts that pierce and mark.', price: 420, unlockWave: 9, tags: ['precision', 'pierce', 'energy'] });
R({ id: 'silencedPistol2', name: 'Silenced Pistol-X', category: 'sidearm', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false,
  damage: 22, damageType: DamageType.Kinetic, fireRate: 5, magazine: 12, reserveMax: 96, reloadTime: 1.0, spread: 0.002, range: 54, critChance: 0.15, critMult: 2.1, canHeadshot: true, headshotMult: 2.0, knockback: 2, recoil: 0.6, screenShake: 0.03, sfx: 'shoot_pistol', viewmodel: vmdl(0x6f86a8), tracerColor: 0xcfe6ff, impactColor: 0x9fb3d6, description: 'A silenced pistol. Quiet, precise, high headshot crit.', price: 200, unlockWave: 4, tags: ['precision', 'stealth'] });
R({ id: 'plasmaRevolver2', name: 'Plasma Revolver-X', category: 'sidearm', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 60, damageType: DamageType.Energy, fireRate: 1.6, magazine: 6, reserveMax: 48, reloadTime: 1.6, spread: 0.004, range: 58, critChance: 0.15, critMult: 2.3, canHeadshot: true, knockback: 9, recoil: 2.0, screenShake: 0.14, sfx: 'shoot_plasma', projectile: { speed: 58, gravity: 0, lifetime: 2, color: 0xff3df0, radius: 0.2, shape: 'orb', scale: 1.3, aoe: 2, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xff3df0), projectileColor: 0xff3df0, impactColor: 0xff3df0, description: 'A plasma revolver. Energy rounds with a small splash.', price: 440, unlockWave: 9, tags: ['precision', 'energy', 'aoe'] });
R({ id: 'twinPistol2', name: 'Twin Pistols-X', category: 'sidearm', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 18, damageType: DamageType.Kinetic, fireRate: 9, magazine: 24, reserveMax: 192, reloadTime: 1.4, spread: 0.009, range: 48, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 3, recoil: 0.9, screenShake: 0.05, sfx: 'shoot_pistol', viewmodel: vmdl(0x29e7ff), tracerColor: 0x9fd0ff, impactColor: 0x29e7ff, description: 'Akimbo twin pistols. Double the barrels, double the rate.', price: 420, unlockWave: 9, tags: ['auto', 'crowd'] });
R({ id: 'voidPistol', name: 'Void Pistol', category: 'sidearm', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 60, damageType: DamageType.Energy, fireRate: 2, magazine: 10, reserveMax: 80, reloadTime: 1.3, spread: 0.003, range: 60, critChance: 0.22, critMult: 2.5, canHeadshot: true, headshotMult: 2.2, knockback: 8, recoil: 1.6, screenShake: 0.12, sfx: 'shoot_railgun', viewmodel: vmdl(0x8a5bff), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, tracerWidth: 2, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, projectile: { pierce: 3 }, description: 'A void pistol. Pierces, marks, and crits like a rifle.', price: 620, unlockWave: 13, tags: ['precision', 'pierce', 'mark', 'energy'] });
R({ id: 'infernoPistol', name: 'Inferno Pistol', category: 'sidearm', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 40, damageType: DamageType.Fire, fireRate: 3, magazine: 12, reserveMax: 96, reloadTime: 1.3, spread: 0.01, range: 45, critChance: 0.15, critMult: 2.2, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_plasma', projectile: { speed: 44, gravity: 0, lifetime: 2, color: 0xff5522, radius: 0.2, shape: 'orb', scale: 1.1, aoe: 1.5, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xff5522), projectileColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.6, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, lifesteal: 0.04, description: 'An inferno sidearm. Burns, splashes, and leeches.', price: 600, unlockWave: 12, tags: ['projectile', 'fire', 'lifesteal', 'aoe'] });
