// ============================================================================
// smgs2.js — A large roster of SMGs and machine pistols covering fire rates,
// damage tiers, and elemental variants for close-to-mid range suppression.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent) => ({ color: 0x223044, accent, length: 0.5, shape: 'smg' });

R({ id: 'compactSMG', name: 'Compact SMG', category: 'smg', rarity: WeaponRarity.Common, fireMode: FireMode.Hitscan, auto: true,
  damage: 7, damageType: DamageType.Kinetic, fireRate: 16, magazine: 30, reserveMax: 240, reloadTime: 1.4, spread: 0.02, range: 30, falloffStart: 12, falloffEnd: 26, falloffMin: 0.5, critChance: 0.05, critMult: 1.7, canHeadshot: true, knockback: 1, recoil: 0.7, screenShake: 0.03, sfx: 'shoot_smg', viewmodel: vmdl(0x9fb3d6), tracerColor: 0xbfe7a0, impactColor: 0xbfe7a0, description: 'A compact SMG. Lightweight, fast, cheap.', price: 140, unlockWave: 2, tags: ['auto', 'crowd'] });
R({ id: 'pulseSMG', name: 'Pulse SMG', category: 'smg', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: true,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 14, magazine: 32, reserveMax: 256, reloadTime: 1.5, spread: 0.018, range: 34, falloffStart: 14, falloffEnd: 30, falloffMin: 0.55, critChance: 0.06, critMult: 1.8, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: vmdl(0x4fd07a), tracerColor: 0xbfe7a0, impactColor: 0x4fd07a, description: 'A pulse SMG. Smooth recoil, steady DPS.', price: 200, unlockWave: 4, tags: ['auto', 'crowd'] });
R({ id: 'emberSMG', name: 'Ember SMG', category: 'smg', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 10, damageType: DamageType.Fire, fireRate: 13, magazine: 30, reserveMax: 240, reloadTime: 1.6, spread: 0.02, range: 32, critChance: 0.07, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_plasma', viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, statusChance: 0.3, statusType: StatusType.Burn, statusPower: 1, statusDuration: 2, description: 'An ember SMG. Incendiary rounds that ignite.', price: 420, unlockWave: 8, tags: ['auto', 'fire', 'status', 'crowd'] });
R({ id: 'frostSMG', name: 'Frost SMG', category: 'smg', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 10, damageType: DamageType.Cryo, fireRate: 13, magazine: 30, reserveMax: 240, reloadTime: 1.6, spread: 0.02, range: 32, critChance: 0.07, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_laser', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, statusChance: 0.3, statusType: StatusType.Slow, statusPower: 1, statusDuration: 2, description: 'A frost SMG. Cryo rounds that chill.', price: 420, unlockWave: 8, tags: ['auto', 'cryo', 'control', 'crowd'] });
R({ id: 'shockSMG', name: 'Shock SMG', category: 'smg', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 10, damageType: DamageType.Shock, fireRate: 13, magazine: 30, reserveMax: 240, reloadTime: 1.6, spread: 0.02, range: 32, critChance: 0.07, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.3, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, description: 'A shock SMG. Arcs electricity through clustered foes.', price: 420, unlockWave: 8, tags: ['auto', 'shock', 'status', 'crowd'] });
R({ id: 'plasmaSMG', name: 'Plasma SMG', category: 'smg', rarity: WeaponRarity.Rare, fireMode: FireMode.Projectile, auto: true,
  damage: 12, damageType: DamageType.Energy, fireRate: 11, magazine: 28, reserveMax: 224, reloadTime: 1.6, spread: 0.018, range: 34, critChance: 0.07, critMult: 1.9, canHeadshot: true, knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_plasma', projectile: { speed: 58, gravity: 0, lifetime: 1.4, color: 0x29e7ff, radius: 0.14, shape: 'orb', scale: 0.8, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A plasma SMG. Rapid energy orbs.', price: 280, unlockWave: 5, tags: ['auto', 'energy', 'projectile', 'crowd'] });
R({ id: 'burstSMG', name: 'Burst SMG', category: 'smg', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false, burst: 4, burstDelay: 0.04,
  damage: 11, damageType: DamageType.Kinetic, fireRate: 4.5, magazine: 28, reserveMax: 224, reloadTime: 1.5, spread: 0.012, range: 36, critChance: 0.08, critMult: 1.9, canHeadshot: true, knockback: 2, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_smg', viewmodel: vmdl(0x4fd07a), tracerColor: 0xbfe7a0, impactColor: 0x4fd07a, description: 'A 4-round-burst SMG. Tight and rhythmic.', price: 220, unlockWave: 4, tags: ['burst', 'precision', 'crowd'] });
R({ id: 'heavySMG', name: 'Heavy SMG', category: 'smg', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: true,
  damage: 13, damageType: DamageType.Kinetic, fireRate: 10, magazine: 32, reserveMax: 256, reloadTime: 1.7, spread: 0.016, range: 38, falloffStart: 16, falloffEnd: 34, falloffMin: 0.6, critChance: 0.07, critMult: 1.9, canHeadshot: true, knockback: 2, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_rifle', viewmodel: vmdl(0xff5544), tracerColor: 0xffd28a, impactColor: 0xff5544, description: 'A heavy SMG. Bigger rounds, more punch.', price: 280, unlockWave: 5, tags: ['auto', 'crowd'] });
R({ id: 'vector3', name: 'Vector-X2', category: 'smg', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 13, damageType: DamageType.Kinetic, fireRate: 24, magazine: 40, reserveMax: 320, reloadTime: 1.6, spread: 0.015, range: 36, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 1, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: vmdl(0xff3df0), tracerColor: 0xff9de0, impactColor: 0xff3df0, description: 'An elite SMG. The fastest fire rate in the game.', price: 640, unlockWave: 12, tags: ['auto', 'crowd', 'elite'] });
R({ id: 'needlerSMG', name: 'Needler', category: 'smg', rarity: WeaponRarity.Rare, fireMode: FireMode.Hitscan, auto: true,
  damage: 9, damageType: DamageType.Kinetic, fireRate: 18, magazine: 40, reserveMax: 320, reloadTime: 1.4, spread: 0.008, range: 40, critChance: 0.1, critMult: 1.9, canHeadshot: true, knockback: 1, recoil: 0.6, screenShake: 0.03, sfx: 'shoot_smg', viewmodel: vmdl(0x4fffd0), tracerColor: 0x4fffd0, impactColor: 0x4fffd0, statusChance: 0.25, statusType: StatusType.Bleed, statusPower: 1, statusDuration: 2, description: 'A needler. Tiny precise needles that cause bleed.', price: 280, unlockWave: 5, tags: ['auto', 'precision', 'status', 'crowd'] });
R({ id: 'stormSMG2', name: 'Tempest SMG', category: 'smg', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 12, damageType: DamageType.Shock, fireRate: 18, magazine: 36, reserveMax: 288, reloadTime: 1.6, spread: 0.014, range: 40, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 2, recoil: 0.8, screenShake: 0.04, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, statusChance: 0.35, statusType: StatusType.Shock, statusPower: 1, statusDuration: 1.5, description: 'A tempest SMG. Shock rounds at extreme RPM.', price: 620, unlockWave: 11, tags: ['auto', 'shock', 'crowd', 'elite'] });
R({ id: 'twinSMG', name: 'Twin Fangs', category: 'smg', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true, burst: 2, burstDelay: 0.03,
  damage: 14, damageType: DamageType.Kinetic, fireRate: 11, magazine: 40, reserveMax: 320, reloadTime: 1.5, spread: 0.014, range: 38, critChance: 0.12, critMult: 2.2, canHeadshot: true, knockback: 2, recoil: 0.9, screenShake: 0.04, sfx: 'shoot_smg', viewmodel: vmdl(0xff3df0), tracerColor: 0xff9de0, impactColor: 0xff3df0, description: 'Twin-barrel burst SMG. Two rounds per shot, high cadence.', price: 560, unlockWave: 11, tags: ['auto', 'burst', 'crowd'] });
