// ============================================================================
// snipers2.js — A large roster of sniper & marksman weapons covering damage
// tiers, elemental variants, and unique precision mechanics.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, len = 0.85) => ({ color: 0x223044, accent, length: len, shape: 'rifle' });

R({ id: 'hunterRifle', name: 'Hunter', category: 'sniper', rarity: WeaponRarity.Uncommon, fireMode: FireMode.Hitscan, auto: false,
  damage: 48, damageType: DamageType.Kinetic, fireRate: 2, magazine: 8, reserveMax: 64, reloadTime: 1.8, spread: 0.003, range: 85, falloffStart: 48, falloffEnd: 78, falloffMin: 0.8, critChance: 0.16, critMult: 2.1, canHeadshot: true, headshotMult: 1.9, knockback: 7, recoil: 2.0, screenShake: 0.12, sfx: 'shoot_sniper', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, description: 'A bolt-action hunter. Reliable precision.', price: 220, unlockWave: 4, tags: ['precision', 'semi'] });
R({ id: 'shockSniper', name: 'Arc Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 75, damageType: DamageType.Shock, fireRate: 1.2, magazine: 6, reserveMax: 48, reloadTime: 2.0, spread: 0.0, range: 80, critChance: 0.16, critMult: 2.3, canHeadshot: true, headshotMult: 2.1, knockback: 10, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066), tracerColor: 0xffe066, impactColor: 0xffe066, tracerWidth: 2, statusChance: 0.6, statusType: StatusType.Shock, statusPower: 2, statusDuration: 2, projectile: { pierce: 3 }, description: 'A shock sniper. Pierces and stuns.', price: 460, unlockWave: 10, tags: ['precision', 'shock', 'pierce'] });
R({ id: 'fireSniper', name: 'Ember Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 70, damageType: DamageType.Fire, fireRate: 1.2, magazine: 6, reserveMax: 48, reloadTime: 2.0, spread: 0.0, range: 80, critChance: 0.15, critMult: 2.2, canHeadshot: true, headshotMult: 2.0, knockback: 8, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_plasma', viewmodel: vmdl(0xff5522), tracerColor: 0xff5522, impactColor: 0xff5522, tracerWidth: 2, statusChance: 0.6, statusType: StatusType.Burn, statusPower: 3, statusDuration: 3, description: 'An ember sniper. Ignites on hit.', price: 460, unlockWave: 10, tags: ['precision', 'fire', 'status'] });
R({ id: 'frostSniper', name: 'Frost Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: false,
  damage: 65, damageType: DamageType.Cryo, fireRate: 1.2, magazine: 6, reserveMax: 48, reloadTime: 2.0, spread: 0.0, range: 80, critChance: 0.15, critMult: 2.2, canHeadshot: true, headshotMult: 2.0, knockback: 8, recoil: 2.4, screenShake: 0.16, sfx: 'shoot_laser', viewmodel: vmdl(0x9fe7ff), tracerColor: 0x9fe7ff, impactColor: 0x9fe7ff, tracerWidth: 2, statusChance: 0.6, statusType: StatusType.Freeze, statusPower: 1, statusDuration: 2, description: 'A frost sniper. Freezes targets solid.', price: 460, unlockWave: 10, tags: ['precision', 'cryo', 'control'] });
R({ id: 'voidSniper', name: 'Void Sniper', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 120, damageType: DamageType.Energy, fireRate: 0.9, magazine: 4, reserveMax: 28, reloadTime: 2.4, spread: 0.0, range: 110, falloffStart: 70, falloffEnd: 100, falloffMin: 0.85, critChance: 0.3, critMult: 2.6, canHeadshot: true, headshotMult: 2.5, knockback: 16, recoil: 4.0, screenShake: 0.22, sfx: 'shoot_railgun', viewmodel: vmdl(0x8a5bff, 0.9), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, tracerWidth: 3, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, projectile: { pierce: 6 }, description: 'A void sniper. Pierces ranks and marks survivors.', price: 700, unlockWave: 14, tags: ['precision', 'pierce', 'mark', 'high-damage'] });
R({ id: 'autoSniper', name: 'Auto Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Hitscan, auto: true,
  damage: 35, damageType: DamageType.Kinetic, fireRate: 3.5, magazine: 10, reserveMax: 80, reloadTime: 2.0, spread: 0.004, range: 75, falloffStart: 42, falloffEnd: 70, falloffMin: 0.78, critChance: 0.14, critMult: 2.1, canHeadshot: true, headshotMult: 1.9, knockback: 6, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_sniper', viewmodel: vmdl(0x4fd07a), tracerColor: 0x9fd0ff, impactColor: 0x4fd07a, description: 'A full-auto sniper. Sustained precision fire.', price: 420, unlockWave: 9, tags: ['precision', 'auto'] });
R({ id: 'railDriver', name: 'Rail Driver', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 160, damageType: DamageType.Kinetic, fireRate: 0.7, magazine: 4, reserveMax: 28, reloadTime: 2.8, spread: 0.0, range: 140, falloffStart: 100, falloffEnd: 130, falloffMin: 0.9, critChance: 0.35, critMult: 2.8, canHeadshot: true, headshotMult: 3.0, knockback: 22, recoil: 5.0, screenShake: 0.28, sfx: 'shoot_railgun', viewmodel: vmdl(0xff3df0, 0.95), tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 3, projectile: { pierce: 8 }, description: 'A rail driver. The hardest single-shot hitscan in the game.', price: 760, unlockWave: 15, tags: ['precision', 'pierce', 'high-damage'] });
R({ id: 'plasmaSniper', name: 'Plasma Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 90, damageType: DamageType.Energy, fireRate: 1.0, magazine: 5, reserveMax: 35, reloadTime: 2.2, spread: 0.0, range: 90, critChance: 0.2, critMult: 2.4, canHeadshot: true, knockback: 14, recoil: 3.0, screenShake: 0.2, sfx: 'shoot_plasma', projectile: { speed: 90, gravity: 0, lifetime: 1.8, color: 0x29e7ff, radius: 0.2, shape: 'shard', scale: 1.4, pierce: 4, aoe: 2, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A plasma sniper. Hyper-velocity orbs that pierce and splash.', price: 480, unlockWave: 11, tags: ['precision', 'pierce', 'aoe', 'energy'] });
R({ id: 'chronoSniper', name: 'Chrono Sniper', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 85, damageType: DamageType.Energy, fireRate: 1.2, magazine: 6, reserveMax: 42, reloadTime: 2.0, spread: 0.0, range: 90, critChance: 0.2, critMult: 2.5, canHeadshot: true, headshotMult: 2.3, knockback: 10, recoil: 2.6, screenShake: 0.18, sfx: 'shoot_railgun', viewmodel: vmdl(0x29e7ff, 0.9), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, tracerWidth: 2, statusChance: 0.5, statusType: StatusType.Slow, statusPower: 3, statusDuration: 2, projectile: { pierce: 3 }, description: 'A chrono sniper. Slows time for the target on hit.', price: 640, unlockWave: 13, tags: ['precision', 'control', 'pierce'] });
R({ id: 'splitSniper', name: 'Split Sniper', category: 'sniper', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 60, damageType: DamageType.Kinetic, fireRate: 1.2, magazine: 6, reserveMax: 42, reloadTime: 2.0, spread: 0.0, range: 80, critChance: 0.15, critMult: 2.2, canHeadshot: true, knockback: 12, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_rifle', projectile: { speed: 70, gravity: 0.2, lifetime: 2, color: 0x9fb3d6, radius: 0.18, shape: 'shard', scale: 1.3, pierce: 3, ricochet: 2, glow: true, trail: true }, viewmodel: vmdl(0x9fb3d6), projectileColor: 0x9fb3d6, impactColor: 0x9fb3d6, description: 'A split sniper. Rounds pierce and ricochet off walls.', price: 440, unlockWave: 10, tags: ['precision', 'pierce', 'ricochet'] });
R({ id: 'stormSniper', name: 'Storm Sniper', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 100, damageType: DamageType.Shock, fireRate: 1.0, magazine: 5, reserveMax: 35, reloadTime: 2.2, spread: 0.0, range: 95, critChance: 0.22, critMult: 2.5, canHeadshot: true, headshotMult: 2.3, knockback: 14, recoil: 3.2, screenShake: 0.22, sfx: 'shoot_lightning', viewmodel: vmdl(0xffe066, 0.9), tracerColor: 0xffe066, impactColor: 0xffe066, tracerWidth: 3, statusChance: 0.7, statusType: StatusType.Shock, statusPower: 3, statusDuration: 2, projectile: { pierce: 5 }, description: 'A storm sniper. Pierces and chains shock through ranks.', price: 700, unlockWave: 14, tags: ['precision', 'shock', 'pierce', 'high-damage'] });
R({ id: 'galSniper', name: 'Galileo Sniper', category: 'sniper', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 140, damageType: DamageType.Energy, fireRate: 0.8, magazine: 4, reserveMax: 24, reloadTime: 2.6, spread: 0.0, range: 100, critChance: 0.25, critMult: 2.7, canHeadshot: true, headshotMult: 2.6, knockback: 20, recoil: 4.5, screenShake: 0.26, sfx: 'shoot_railgun', projectile: { speed: 80, gravity: 0, lifetime: 2, color: 0xffb347, radius: 0.22, shape: 'shard', scale: 1.6, pierce: 99, aoe: 3, aoeFalloff: 0.5, glow: true, trail: true }, viewmodel: vmdl(0xffb347, 0.95), projectileColor: 0xffb347, impactColor: 0xffb347, description: 'A hyper-velocity rail that pierces everything and detonates on each hit.', price: 720, unlockWave: 15, tags: ['precision', 'pierce', 'aoe', 'high-damage'] });
