// ============================================================================
// special.js — Special/exotic weapons: launchers, flamethrower, ricochet,
// boomerang, black hole, time rifle, mine layer, harpoon. Unique mechanics.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

WeaponRegistry.registerMany([
  {
    id: 'grenadeLauncher', name: 'Grenade Launcher', category: 'heavy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 55, damageType: DamageType.Explosive, fireRate: 1.6, magazine: 6, reserveMax: 36, reloadTime: 2.2,
    spread: 0.0, range: 60, critChance: 0.0, canHeadshot: false,
    knockback: 12, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_rocket',
    projectile: { speed: 32, gravity: 0.8, lifetime: 3, color: 0x66ff88, radius: 0.2, shape: 'chunky', scale: 1.2, aoe: 4, aoeFalloff: 0.4, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0x66ff88, length: 0.6, shape: 'launcher' },
    projectileColor: 0x66ff88, impactColor: 0x66ff88,
    description: 'Lobs bouncing grenades that explode on impact. Versatile AoE.',
    price: 380, unlockWave: 6, tags: ['explosive', 'aoe', 'projectile'],
  },
  {
    id: 'mineLayer', name: 'Mine Layer', category: 'special', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 90, damageType: DamageType.Explosive, fireRate: 1.0, magazine: 5, reserveMax: 30, reloadTime: 2.4,
    spread: 0.0, range: 18, critChance: 0.0, canHeadshot: false,
    knockback: 16, recoil: 1.5, screenShake: 0.18, sfx: 'shoot_rocket',
    projectile: { speed: 10, gravity: 1.0, lifetime: 8, color: 0xff3df0, radius: 0.25, shape: 'orb', scale: 1.2, aoe: 5, aoeFalloff: 0.4, proximity: 3, glow: true, trail: false },
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.5, shape: 'launcher' },
    projectileColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'Deploys proximity mines. Lure enemies into the blast.',
    price: 420, unlockWave: 9, tags: ['explosive', 'aoe', 'tactical', 'proximity'],
  },
  {
    id: 'flamethrower', name: 'Dragon', category: 'special', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Beam, auto: true,
    damage: 14, damageType: DamageType.Fire, fireRate: 16, magazine: 100, reserveMax: 0, reloadTime: 2.0,
    spread: 0.0, range: 16, critChance: 0.04, critMult: 1.5, canHeadshot: false,
    knockback: 1, recoil: 0.3, screenShake: 0.02, sfx: 'shoot_flame',
    beam: { width: 0.3, tickRate: 0.05, color: 0xff7733 },
    viewmodel: { color: 0x223044, accent: 0xff7733, length: 0.6, shape: 'launcher' },
    tracerColor: 0xff7733, impactColor: 0xff7733,
    statusChance: 0.6, statusType: StatusType.Burn, statusPower: 2, statusDuration: 3,
    description: 'A proper flamethrower. Short range, massive crowd melt.',
    price: 460, unlockWave: 8, tags: ['beam', 'fire', 'close', 'crowd'],
  },
  {
    id: 'ricochetPistol', name: 'Ricochet', category: 'sidearm', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 22, damageType: DamageType.Kinetic, fireRate: 4, magazine: 10, reserveMax: 80, reloadTime: 1.2,
    spread: 0.008, range: 50, critChance: 0.1, critMult: 2.0, canHeadshot: true,
    knockback: 4, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_pistol',
    viewmodel: { color: 0x223044, accent: 0x4fd07a, length: 0.5, shape: 'pistol' },
    tracerColor: 0x4fd07a, impactColor: 0x4fd07a,
    description: 'Bullets ricochet off walls. Bend shots around cover.',
    price: 240, unlockWave: 5, tags: ['precision', 'ricochet'],
    projectile: { ricochet: 2 },
  },
  {
    id: 'boomerang', name: 'Boomerang Blade', category: 'special', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Projectile, auto: false,
    damage: 40, damageType: DamageType.Kinetic, fireRate: 1.5, magazine: 1, reserveMax: 0, reloadTime: 0,
    spread: 0.0, range: 30, critChance: 0.15, critMult: 2.2, canHeadshot: true,
    knockback: 8, recoil: 1.0, screenShake: 0.08, sfx: 'shoot_lightning',
    projectile: { speed: 30, gravity: 0, lifetime: 2.4, color: 0xffe066, radius: 0.3, shape: 'ring', scale: 1.2, pierce: 99, homing: 0.0, glow: true, trail: true },
    viewmodel: { color: 0x223044, accent: 0xffe066, length: 0.5, shape: 'blade' },
    projectileColor: 0xffe066, impactColor: 0xffe066,
    description: 'Hurls a piercing ring that slices through everything.',
    price: 400, unlockWave: 9, tags: ['projectile', 'pierce', 'special'],
  },
  {
    id: 'blackHole', name: 'Singularity', category: 'special', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Projectile, auto: false,
    damage: 30, damageType: DamageType.Energy, fireRate: 0.6, magazine: 3, reserveMax: 18, reloadTime: 2.8,
    spread: 0.0, range: 40, critChance: 0.0, canHeadshot: false,
    knockback: 0, recoil: 2.0, screenShake: 0.18, sfx: 'shoot_plasma',
    projectile: { speed: 22, gravity: 0, lifetime: 2.5, color: 0x8a5bff, radius: 0.5, shape: 'orb', scale: 1.6, aoe: 8, aoeFalloff: 0.0, glow: true, trail: true, proximity: 6 },
    viewmodel: { color: 0x1a1030, accent: 0x8a5bff, length: 0.7, shape: 'heavy' },
    projectileColor: 0x8a5bff, impactColor: 0x8a5bff,
    description: 'A collapsing singularity that pulls enemies in then detonates.',
    price: 720, unlockWave: 16, tags: ['explosive', 'aoe', 'control', 'special'],
  },
  {
    id: 'timeRifle', name: 'Chrono Rifle', category: 'special', rarity: WeaponRarity.Legendary,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 70, damageType: DamageType.Energy, fireRate: 1.2, magazine: 6, reserveMax: 48, reloadTime: 1.8,
    spread: 0.0, range: 80, critChance: 0.2, critMult: 2.5, canHeadshot: true,
    knockback: 8, recoil: 2.5, screenShake: 0.16, sfx: 'shoot_railgun',
    viewmodel: { color: 0x223044, accent: 0x29e7ff, length: 0.8, shape: 'rifle' },
    tracerColor: 0x29e7ff, impactColor: 0x29e7ff, tracerWidth: 2,
    statusChance: 0.5, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2,
    description: 'Hits that slow time for the target. Precision with control.',
    price: 700, unlockWave: 15, tags: ['precision', 'control', 'special'],
  },
  {
    id: 'harpoon', name: 'Harpoon Gun', category: 'special', rarity: WeaponRarity.Rare,
    fireMode: FireMode.Projectile, auto: false,
    damage: 80, damageType: DamageType.Kinetic, fireRate: 0.9, magazine: 4, reserveMax: 24, reloadTime: 2.0,
    spread: 0.0, range: 50, critChance: 0.12, critMult: 2.2, canHeadshot: true,
    knockback: 24, recoil: 2.6, screenShake: 0.16, sfx: 'shoot_rifle',
    projectile: { speed: 60, gravity: 0.2, lifetime: 1.6, color: 0x9fb3d6, radius: 0.12, shape: 'long', scale: 1.4, pierce: 2, glow: false, trail: true },
    viewmodel: { color: 0x223044, accent: 0x9fb3d6, length: 0.8, shape: 'rifle' },
    projectileColor: 0x9fb3d6, impactColor: 0x9fb3d6,
    description: 'Fires a heavy harpoon with massive knockback and pierce.',
    price: 300, unlockWave: 7, tags: ['projectile', 'knockback', 'pierce'],
  },
  {
    id: 'splitBeam', name: 'Prism Splitter', category: 'energy', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: true,
    damage: 9, damageType: DamageType.Energy, fireRate: 6, magazine: 20, reserveMax: 140, reloadTime: 1.8,
    spread: 0.04, range: 40, critChance: 0.06, critMult: 1.8, canHeadshot: false,
    pellets: 3, knockback: 2, recoil: 1.2, screenShake: 0.06, sfx: 'shoot_laser',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.6, shape: 'energy' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0,
    description: 'Fires a 3-beam spread of light. Great for crowds.',
    price: 380, unlockWave: 8, tags: ['spread', 'energy', 'crowd'],
  },
  {
    id: 'railSpike', name: 'Rail Spike', category: 'sniper', rarity: WeaponRarity.Epic,
    fireMode: FireMode.Hitscan, auto: false,
    damage: 140, damageType: DamageType.Kinetic, fireRate: 0.7, magazine: 4, reserveMax: 32, reloadTime: 2.6,
    spread: 0.0, range: 130, falloffStart: 90, falloffEnd: 120, falloffMin: 0.9,
    critChance: 0.35, critMult: 2.8, canHeadshot: true, headshotMult: 3.0,
    knockback: 20, recoil: 5.0, screenShake: 0.28, sfx: 'shoot_railgun',
    viewmodel: { color: 0x223044, accent: 0xff3df0, length: 0.95, shape: 'rifle' },
    tracerColor: 0xff3df0, impactColor: 0xff3df0, tracerWidth: 3,
    description: 'Anti-materiel rail. The hardest single-shot in the arsenal.',
    price: 600, unlockWave: 12, tags: ['precision', 'high-damage', 'pierce'],
    projectile: { pierce: 6 },
  },
]);
