// ============================================================================
// special2.js — More special/exotic weapons with unique mechanics: orbital
// drones, black-hole launchers, time rifles, beam-scatter hybrids, and more.
// ============================================================================

import { WeaponRegistry } from '../WeaponRegistry.js';
import { FireMode, WeaponRarity } from '../Weapon.js';
import { DamageType, StatusType } from '../../ecs/components/Combat.js';

const R = (def) => WeaponRegistry.register(def);
const vmdl = (accent, shape = 'launcher', len = 0.7) => ({ color: 0x223044, accent, length: len, shape });

R({ id: 'orbitalDrone', name: 'Orbital Drone', category: 'special', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 25, damageType: DamageType.Energy, fireRate: 1.2, magazine: 6, reserveMax: 36, reloadTime: 2.0, spread: 0.0, range: 40, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_plasma',
  projectile: { speed: 14, gravity: 0, lifetime: 5, color: 0x4fffd0, radius: 0.3, shape: 'orb', scale: 1.3, homing: 0.9, pierce: 4, glow: true, trail: true }, viewmodel: vmdl(0x4fffd0, 'energy', 0.6), projectileColor: 0x4fffd0, impactColor: 0x4fffd0, description: 'Launches a slow homing orb-drone that weaves through crowds.', price: 440, unlockWave: 9, tags: ['homing', 'pierce', 'special'] });
R({ id: 'blackHole2', name: 'Singularity', category: 'special', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 35, damageType: DamageType.Energy, fireRate: 0.7, magazine: 3, reserveMax: 15, reloadTime: 2.6, spread: 0.0, range: 45, critChance: 0.0, canHeadshot: false, knockback: 0, recoil: 2.2, screenShake: 0.2, sfx: 'shoot_plasma',
  projectile: { speed: 22, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.5, shape: 'orb', scale: 1.8, aoe: 9, aoeFalloff: 0.0, proximity: 7, glow: true, trail: true }, viewmodel: vmdl(0x8a5bff, 'heavy', 0.8), projectileColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.6, statusType: StatusType.Slow, statusPower: 3, statusDuration: 4, description: 'A singularity launcher. Collapses a whole area.', price: 720, unlockWave: 16, tags: ['control', 'aoe', 'special'] });
R({ id: 'timeRifle2', name: 'Chrono Rifle', category: 'special', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 75, damageType: DamageType.Energy, fireRate: 1.2, magazine: 6, reserveMax: 48, reloadTime: 1.8, spread: 0.0, range: 85, critChance: 0.2, critMult: 2.5, canHeadshot: true, knockback: 8, recoil: 2.5, screenShake: 0.16, sfx: 'shoot_railgun', viewmodel: vmdl(0x29e7ff, 'rifle', 0.8), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, tracerWidth: 2, statusChance: 0.5, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2, description: 'A chrono rifle. Hits that slow time for the target.', price: 700, unlockWave: 15, tags: ['precision', 'control', 'special'] });
R({ id: 'beamScatter2', name: 'Prism Burst', category: 'energy', rarity: WeaponRarity.Epic, fireMode: FireMode.Beam, auto: false,
  damage: 26, damageType: DamageType.Energy, fireRate: 1.4, magazine: 16, reserveMax: 96, reloadTime: 1.8, spread: 0.06, range: 30, critChance: 0.1, critMult: 2.0, canHeadshot: false, pellets: 5, knockback: 4, recoil: 1.6, screenShake: 0.1, sfx: 'shoot_laser', beam: { width: 0.08, tickRate: 0.12, color: 0xff3df0 }, viewmodel: vmdl(0xff3df0, 'energy', 0.6), tracerColor: 0xff3df0, impactColor: 0xff3df0, description: 'A prismatic beam-cannon firing a fan of beams per shot.', price: 440, unlockWave: 9, tags: ['beam', 'spread', 'crowd'] });
R({ id: 'chronoPistol2', name: 'Chrono Pistol', category: 'sidearm', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: false,
  damage: 42, damageType: DamageType.Energy, fireRate: 2.5, magazine: 12, reserveMax: 96, reloadTime: 1.4, spread: 0.004, range: 60, critChance: 0.2, critMult: 2.4, canHeadshot: true, headshotMult: 2.0, knockback: 6, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_laser', viewmodel: vmdl(0x29e7ff, 'pistol', 0.5), tracerColor: 0x29e7ff, impactColor: 0x29e7ff, statusChance: 0.4, statusType: StatusType.Slow, statusPower: 2, statusDuration: 2, description: 'A chrono sidearm firing rounds that slow targets.', price: 580, unlockWave: 11, tags: ['precision', 'control', 'special'] });
R({ id: 'dimensionRifle2', name: 'Phase Rifle', category: 'rifle', rarity: WeaponRarity.Legendary, fireMode: FireMode.Hitscan, auto: true,
  damage: 24, damageType: DamageType.Energy, fireRate: 7, magazine: 24, reserveMax: 168, reloadTime: 1.8, spread: 0.006, range: 60, critChance: 0.14, critMult: 2.2, canHeadshot: true, knockback: 3, recoil: 1.0, screenShake: 0.05, sfx: 'shoot_laser', viewmodel: vmdl(0x8a5bff, 'rifle', 0.7), tracerColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.3, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, projectile: { pierce: 2 }, description: 'A phase rifle. Rounds pierce cover and mark targets.', price: 620, unlockWave: 12, tags: ['auto', 'pierce', 'mark', 'special'] });
R({ id: 'sawLauncher2', name: 'Saw Launcher', category: 'heavy', rarity: WeaponRarity.Epic, fireMode: FireMode.Projectile, auto: false,
  damage: 18, damageType: DamageType.Kinetic, fireRate: 3, magazine: 8, reserveMax: 48, reloadTime: 2.0, spread: 0.0, range: 30, critChance: 0.05, critMult: 1.8, canHeadshot: false, knockback: 4, recoil: 1.0, screenShake: 0.06, sfx: 'shoot_rifle', projectile: { speed: 30, gravity: 0.2, lifetime: 2, color: 0x9fb3d6, radius: 0.3, shape: 'ring', scale: 1.2, pierce: 99, ricochet: 6, glow: false, trail: true }, viewmodel: vmdl(0x9fb3d6, 'launcher', 0.6), projectileColor: 0x9fb3d6, impactColor: 0x9fb3d6, description: 'Fires ricocheting sawblades that chew through lines.', price: 420, unlockWave: 9, tags: ['pierce', 'ricochet', 'special'] });
R({ id: 'mirrorGun2', name: 'Mirror Gun', category: 'energy', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: true,
  damage: 16, damageType: DamageType.Energy, fireRate: 5, magazine: 20, reserveMax: 140, reloadTime: 1.8, spread: 0.0, range: 40, critChance: 0.12, critMult: 2.1, canHeadshot: true, knockback: 3, recoil: 0.8, screenShake: 0.05, sfx: 'shoot_laser', projectile: { speed: 44, gravity: 0, lifetime: 2, color: 0xffffff, radius: 0.18, shape: 'shard', scale: 1, ricochet: 8, glow: true, trail: true }, viewmodel: vmdl(0xffffff, 'energy', 0.6), projectileColor: 0xffffff, impactColor: 0xffffff, description: 'Crystalline shards that bounce wildly off every surface.', price: 600, unlockWave: 12, tags: ['ricochet', 'energy', 'special'] });
R({ id: 'novaCannon3', name: 'Nova Cannon', category: 'special', rarity: WeaponRarity.Mythic, fireMode: FireMode.Projectile, auto: false,
  damage: 45, damageType: DamageType.Energy, fireRate: 0.6, magazine: 3, reserveMax: 12, reloadTime: 2.6, spread: 0.0, range: 50, critChance: 0.0, canHeadshot: false, knockback: 26, recoil: 3.0, screenShake: 0.26, sfx: 'shoot_railgun', projectile: { speed: 26, gravity: 0, lifetime: 2.8, color: 0x29e7ff, radius: 0.5, shape: 'orb', scale: 2, aoe: 10, aoeFalloff: 0.2, pierce: 99, glow: true, trail: true }, viewmodel: vmdl(0x29e7ff, 'heavy', 0.8), projectileColor: 0x29e7ff, impactColor: 0x29e7ff, description: 'A mythic orb that pierces and detonates repeatedly as a walking nova.', price: 900, unlockWave: 17, tags: ['explosive', 'aoe', 'pierce', 'mythic', 'special'] });
R({ id: 'gravityWell2', name: 'Gravity Well', category: 'special', rarity: WeaponRarity.Mythic, fireMode: FireMode.Projectile, auto: false,
  damage: 65, damageType: DamageType.Energy, fireRate: 0.5, magazine: 3, reserveMax: 12, reloadTime: 2.8, spread: 0.0, range: 45, critChance: 0.0, canHeadshot: false, knockback: 0, recoil: 2.4, screenShake: 0.2, sfx: 'shoot_plasma', projectile: { speed: 18, gravity: 0, lifetime: 3, color: 0x8a5bff, radius: 0.7, shape: 'orb', scale: 2.2, aoe: 11, aoeFalloff: 0.0, proximity: 8, glow: true, trail: true }, viewmodel: vmdl(0x8a5bff, 'heavy', 0.8), projectileColor: 0x8a5bff, impactColor: 0x8a5bff, statusChance: 0.7, statusType: StatusType.Slow, statusPower: 3, statusDuration: 4, description: 'A mythic gravity well that collapses an entire area.', price: 920, unlockWave: 18, tags: ['control', 'aoe', 'mythic', 'special'] });
R({ id: 'prismCannon2', name: 'Prism Cannon', category: 'energy', rarity: WeaponRarity.Mythic, fireMode: FireMode.Beam, auto: true,
  damage: 28, damageType: DamageType.Energy, fireRate: 14, magazine: 150, reserveMax: 0, reloadTime: 2.2, spread: 0.0, range: 50, critChance: 0.2, critMult: 2.5, canHeadshot: true, knockback: 3, recoil: 0.5, screenShake: 0.04, sfx: 'shoot_railgun', beam: { width: 0.16, tickRate: 0.06, color: 0xff3df0 }, viewmodel: vmdl(0xff3df0, 'energy', 0.7), tracerColor: 0xff3df0, impactColor: 0xff3df0, lifesteal: 0.06, statusChance: 0.4, statusType: StatusType.Mark, statusPower: 2, statusDuration: 3, description: 'A mythic prism beam: high DPS, marks, leeches, and chains.', price: 950, unlockWave: 18, tags: ['beam', 'mythic', 'sustain'] });
R({ id: 'orbWalker2', name: 'Orb Weaver', category: 'special', rarity: WeaponRarity.Legendary, fireMode: FireMode.Projectile, auto: false,
  damage: 35, damageType: DamageType.Energy, fireRate: 1.4, magazine: 6, reserveMax: 36, reloadTime: 2.0, spread: 0.0, range: 40, critChance: 0.1, critMult: 2.0, canHeadshot: true, knockback: 4, recoil: 1.2, screenShake: 0.08, sfx: 'shoot_plasma', projectile: { speed: 16, gravity: 0, lifetime: 4, color: 0x4fffd0, radius: 0.3, shape: 'orb', scale: 1.4, homing: 0.85, pierce: 4, glow: true, trail: true }, viewmodel: vmdl(0x4fffd0, 'energy', 0.6), projectileColor: 0x4fffd0, impactColor: 0x4fffd0, description: 'Slow homing orbs that weave through crowds, piercing as they go.', price: 640, unlockWave: 14, tags: ['homing', 'pierce', 'special'] });
