// ============================================================================
// perks6.js — More perks for build variety, themed around elemental
// specializations, precision, and survivability.
// ============================================================================

import { PerkRegistry } from '../PerkRegistry.js';

const P = (def) => PerkRegistry.register(def);

P({ id: 'emberLord', name: 'Ember Lord', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'Burning enemies take +50% damage; +50% burn power.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.5 }), apply: (p) => { p._perkArsonist = true; } });
P({ id: 'frostLord', name: 'Frost Lord', rarity: 'legendary', weight: 2, tags: ['offense', 'status', 'control'], description: 'Frozen enemies take +50% damage; +50% freeze power.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.5 }), apply: (p) => { p._perkCryo = true; } });
P({ id: 'stormLord2', name: 'Storm Lord', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'Shocked enemies take +50% damage; +50% shock power.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.5 }), apply: (p) => { p._perkShock = true; } });
P({ id: 'plagueLord', name: 'Plague Lord', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'Poisoned enemies take +40% damage; +40% poison power.', icon: { shape: 'virus', color: 0x66ff44 }, stat: () => ({ statusPowerMult: 1.4 }), apply: (p) => { p._perkPlague = true; } });
P({ id: 'bleedLord', name: 'Bleed Lord', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'Bleeding enemies take +40% damage; +40% bleed power.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.4 }), apply: (p) => { p._perkBleed = true; } });
P({ id: 'markLord', name: 'Mark Lord', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'Marked enemies take +50% damage; +40% mark power.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.4 }), apply: (p) => { p._perkMark = true; } });
P({ id: 'stoneSkin', name: 'Stone Skin', rarity: 'epic', weight: 4, tags: ['defense'], description: '+10 armor and -15% damage taken.', icon: { shape: 'shield', color: 0x9fb3d6 }, stat: () => ({ armor: 10, damageReduction: 0.15 }) });
P({ id: 'mountain', name: 'Mountain', rarity: 'legendary', weight: 2, tags: ['defense'], description: '+150 max HP, +10 armor, -20% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 150, armor: 10, moveMult: 0.8 }) });
P({ id: 'windwalker', name: 'Windwalker', rarity: 'epic', weight: 4, tags: ['mobility'], description: '+25% move speed and dash i-frames extended 0.2s.', icon: { shape: 'wind', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.25 }) });
P({ id: 'timeDilation', name: 'Time Dilation', rarity: 'legendary', weight: 2, tags: ['control', 'special'], description: 'Kills slow time briefly for enemies (not you).', icon: { shape: 'clock', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkTimeDilation = true; } });
P({ id: 'echoStrike', name: 'Echo Strike', rarity: 'epic', weight: 4, tags: ['offense', 'special'], description: 'Every 3rd shot fires an extra round.', icon: { shape: 'arrow', color: 0x29e7ff }, stat: () => ({}), apply: (p) => { p._perkEcho = (p._perkEcho || 0) + 1; } });
P({ id: 'splitShot', name: 'Split Shot', rarity: 'epic', weight: 4, tags: ['offense', 'special'], description: 'Hits have a 20% chance to split into 2 projectiles.', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: () => ({}), apply: (p) => { p._perkSplit = true; } });
P({ id: 'ricochetMaster', name: 'Ricochet Master', rarity: 'epic', weight: 4, tags: ['offense', 'special'], description: 'Hits ricochet to +1 nearby enemy.', icon: { shape: 'arrow', color: 0xffe066 }, stat: () => ({}), apply: (p) => { p._perkRicochet = true; } });
P({ id: 'homingMaster', name: 'Homing Master', rarity: 'epic', weight: 4, tags: ['offense', 'special'], description: 'Projectiles gain slight homing toward enemies.', icon: { shape: 'arrow', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkHoming = true; } });
P({ id: 'explosiveRounds2', name: 'Explosive Rounds', rarity: 'epic', weight: 4, tags: ['offense', 'aoe', 'special'], description: 'Hits have a 20% chance to detonate in a small AoE.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({}), apply: (p) => { p._perkExplosive = true; } });
P({ id: 'phoenixPerk', name: 'Phoenix', rarity: 'legendary', weight: 2, tags: ['defense', 'special'], description: 'On lethal hit, revive once per wave at 50% HP with a fire nova.', icon: { shape: 'feather', color: 0xff7733 }, stat: () => ({}), apply: (p) => { p._lastStand = true; } });
P({ id: 'undying', name: 'Undying', rarity: 'legendary', weight: 2, tags: ['defense', 'sustain', 'special'], description: 'Below 10% HP, become invulnerable for 2s (once per wave).', icon: { shape: 'shield', color: 0xffd24a }, stat: () => ({}), apply: (p) => { p._perkUndying = true; } });
P({ id: 'frenzy2', name: 'Frenzy', rarity: 'epic', weight: 4, tags: ['offense', 'special'], description: 'Kills grant +10% fire rate for 3s (stacks up to 5).', icon: { shape: 'lightning', color: 0xff5544 }, stat: () => ({}), apply: (p) => { p._perkFrenzy = true; } });
P({ id: 'momentum3', name: 'Momentum', rarity: 'epic', weight: 4, tags: ['mobility', 'offense'], description: '+20% damage while moving; +15% move speed.', icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({ moveMult: 1.15 }), apply: (p) => { p._perkMomentum = true; } });
P({ id: 'stillness2', name: 'Stillness', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: 'While stationary, +30% damage and +15% crit chance.', icon: { shape: 'target', color: 0x4fd07a }, stat: () => ({}), apply: (p) => { p._perkStillness = true; } });
P({ id: 'siegeMaster', name: 'Siege Master', rarity: 'legendary', weight: 2, tags: ['offense', 'aoe'], description: '+80% AoE and +40% explosive damage.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({ aoeMult: 1.8 }), apply: (p) => { p._perkDemo = true; } });
P({ id: 'overpenetrate3', name: 'Overpenetrate', rarity: 'legendary', weight: 2, tags: ['offense'], description: '+3 pierce; pierced enemies take +20% damage.', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: () => ({ pierce: 3 }), apply: (p) => { p._perkOverpen = true; } });
P({ id: 'criticalMass2', name: 'Critical Mass', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: '+20% crit chance; crits deal +60% and chain.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critChance: 0.2, critMult: 0.6 }) });
P({ id: 'soulHarvest3', name: 'Soul Harvest', rarity: 'legendary', weight: 2, tags: ['sustain', 'offense', 'special'], description: 'Kills grant +0.5% damage permanently (caps +60%) and heal 1% HP.', icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), apply: (p) => { p._perkSoulHarvest = true; } });
P({ id: 'warMachine', name: 'War Machine', rarity: 'legendary', weight: 2, tags: ['offense'], description: '+30% damage, +20% fire rate, +30% magazine.', icon: { shape: 'rifle', color: 0xff5544 }, stat: () => ({ damageMult: 1.3, fireRateMult: 1.2, magMult: 1.3 }) });
P({ id: 'ironFortress', name: 'Iron Fortress', rarity: 'legendary', weight: 2, tags: ['defense'], description: '+100 max HP, +12 armor, +60 shield, -20% damage taken.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 100, armor: 12, shield: 60, damageReduction: 0.2 }) });
P({ id: 'swiftStrike', name: 'Swift Strike', rarity: 'epic', weight: 4, tags: ['offense', 'mobility'], description: '+20% fire rate and +10% move speed.', icon: { shape: 'lightning', color: 0x29e7ff }, stat: () => ({ fireRateMult: 1.2, moveMult: 1.1 }) });
P({ id: 'heavyCaliber3', name: 'Heavy Caliber', rarity: 'epic', weight: 4, tags: ['offense'], description: '+40% damage and +60% knockback.', icon: { shape: 'shell', color: 0xffaa44 }, stat: () => ({ damageMult: 1.4, knockbackMult: 1.6 }) });
P({ id: 'longRange', name: 'Long Range', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+30% range and falloff reduced.', icon: { shape: 'scope', color: 0x9fe7ff }, stat: () => ({ rangeMult: 1.3 }) });
P({ id: 'tightGrip2', name: 'Tight Grip', rarity: 'rare', weight: 6, tags: ['offense'], description: '-20% spread.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({ spreadMult: 0.8 }) });
P({ id: 'munitionsExpert4', name: 'Munitions Expert', rarity: 'epic', weight: 4, tags: ['offense'], description: '+40% magazine and -25% reload.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({ magMult: 1.4, reloadMult: 0.75 }) });
