// ============================================================================
// perks7.js — Additional perks for elemental specializations and survival.
// ============================================================================

import { PerkRegistry } from '../PerkRegistry.js';

const P = (def) => PerkRegistry.register(def);

P({ id: 'inferno2', name: 'Inferno', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits burn; +60% burn power.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkPyromancer = true; } });
P({ id: 'glacier', name: 'Glacier', rarity: 'legendary', weight: 2, tags: ['offense', 'status', 'control'], description: 'All hits freeze; +60% freeze power.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkCryomancer = true; } });
P({ id: 'tempest', name: 'Tempest', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits shock; +60% shock power.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkStormcaller = true; } });
P({ id: 'contagion', name: 'Contagion', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'All hits poison; +40% poison power.', icon: { shape: 'virus', color: 0x66ff44 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.4 }), apply: (p) => { p._perkPlague = true; } });
P({ id: 'hemorrhage', name: 'Hemorrhage', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'All hits bleed; +40% bleed power.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.4 }), apply: (p) => { p._perkBleed = true; } });
P({ id: 'marked3', name: 'Marked', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: 'All hits mark; +40% mark power.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.4 }), apply: (p) => { p._perkMark = true; } });
P({ id: 'adrenalJunkie3', name: 'Adrenaline', rarity: 'rare', weight: 6, tags: ['mobility', 'offense'], description: '+25% fire rate and +15% move speed for 3s after dashing.', icon: { shape: 'bolt', color: 0x29e7ff }, stat: () => ({}), apply: (p) => { p._perkAdrenaline = true; } });
P({ id: 'executioner4', name: 'Executioner', rarity: 'epic', weight: 4, tags: ['offense'], description: 'Kills below 30% HP refund 8% ammo and grant +30% damage for 3s.', icon: { shape: 'skull', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkExecutioner = true; } });
P({ id: 'overclock3', name: 'Overclock', rarity: 'epic', weight: 4, tags: ['offense'], description: '+30% fire rate, but +12% spread.', icon: { shape: 'chip', color: 0xff5544 }, stat: () => ({ fireRateMult: 1.3, spreadMult: 1.12 }) });
P({ id: 'momentum4', name: 'Momentum', rarity: 'epic', weight: 4, tags: ['mobility', 'offense'], description: '+20% damage while moving; +12% move speed.', icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({ moveMult: 1.12 }), apply: (p) => { p._perkMomentum = true; } });
P({ id: 'scavenger3', name: 'Scavenger', rarity: 'rare', weight: 6, tags: ['economy'], description: '+35% currency and +25% pickup magnet.', icon: { shape: 'coin', color: 0xffb347 }, stat: () => ({ currencyMult: 1.35 }) });
P({ id: 'scholar3', name: 'Scholar', rarity: 'rare', weight: 6, tags: ['economy'], description: '+35% XP and +1 upgrade choice per level-up.', icon: { shape: 'book', color: 0x9fe7ff }, stat: () => ({ xpMult: 1.35 }), apply: (p) => { p._extraChoices = (p._extraChoices || 0) + 1; } });
P({ id: 'thornmail3', name: 'Thornmail', rarity: 'epic', weight: 4, tags: ['defense'], description: '+20 thorns and -12% damage taken.', icon: { shape: 'cactus', color: 0x4fd07a }, stat: () => ({ thorns: 20, damageReduction: 0.12 }) });
P({ id: 'elementalist4', name: 'Elementalist', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits apply a random status; +60% status power.', icon: { shape: 'flame', color: 0xff6633 }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkElementalist = true; } });
P({ id: 'munitionsExpert5', name: 'Munitions Expert', rarity: 'epic', weight: 4, tags: ['offense'], description: '+35% magazine, -25% reload, +10% fire rate.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({ magMult: 1.35, reloadMult: 0.75, fireRateMult: 1.1 }) });
P({ id: 'glassHeart3', name: 'Glass Heart', rarity: 'legendary', weight: 2, tags: ['offense', 'curse'], description: '+100% damage, but max HP set to 40.', icon: { shape: 'heart', color: 0xff3df0 }, stat: () => ({ damageMult: 2.0, maxHP: -60 }) });
P({ id: 'titan3', name: 'Titan', rarity: 'epic', weight: 4, tags: ['defense'], description: '+80 max HP, +6 armor, -10% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 80, armor: 6, moveMult: 0.9 }) });
P({ id: 'chainMaster3', name: 'Chain Master', rarity: 'epic', weight: 4, tags: ['offense'], description: 'Hits chain to +2 nearby enemies; +20% damage.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ damageMult: 1.2 }), apply: (p) => { p._perkChain = (p._perkChain || 0) + 2; } });
P({ id: 'fortress3', name: 'Fortress', rarity: 'epic', weight: 4, tags: ['defense'], description: '+6 armor, +30 shield, -20% damage taken while stationary.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ armor: 6, shield: 30 }) });
P({ id: 'overdriver3', name: 'Overdriver', rarity: 'epic', weight: 4, tags: ['offense'], description: '+40% fire rate, but +18% spread.', icon: { shape: 'chip', color: 0xff5544 }, stat: () => ({ fireRateMult: 1.4, spreadMult: 1.18 }) });
P({ id: 'necromancer3', name: 'Necromancer', rarity: 'legendary', weight: 2, tags: ['special'], description: 'Kills have 20% chance to spawn an allied drone for 10s.', icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), apply: (p) => { p._perkNecromancer = true; } });
P({ id: 'surgical3', name: 'Surgical', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+0.6 headshot mult; headshots refill 3% ammo.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ headshotMult: 0.6 }), apply: (p) => { p._perkSurgical = true; } });
P({ id: 'vanguard3', name: 'Vanguard', rarity: 'rare', weight: 6, tags: ['defense', 'mobility'], description: '+40 shield; dashing refunds 25% cooldown on kill.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 40 }) });
P({ id: 'pyromancer4', name: 'Pyromancer', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits ignite; +60% burn power; burning foes take +40% damage.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkPyromancer = true; p._perkArsonist = true; } });
P({ id: 'cryomancer4', name: 'Cryomancer', rarity: 'legendary', weight: 2, tags: ['offense', 'status', 'control'], description: 'All hits freeze; +60% freeze power; frozen foes take +40% damage.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkCryomancer = true; p._perkCryo = true; } });
P({ id: 'stormcaller5', name: 'Stormcaller', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits shock; +60% shock power; shocked foes take +40% damage.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.6, statusChanceMult: 1.6 }), apply: (p) => { p._perkStormcaller = true; p._perkShock = true; } });
P({ id: 'kineticist3', name: 'Kineticist', rarity: 'epic', weight: 4, tags: ['offense', 'control'], description: '+80% knockback; slammed enemies take +25% damage.', icon: { shape: 'fist', color: 0xffaa44 }, stat: () => ({ knockbackMult: 1.8 }), apply: (p) => { p._perkKineticist = true; } });
P({ id: 'ammoConservation3', name: 'Conservation', rarity: 'epic', weight: 4, tags: ['offense'], description: '25% chance not to consume ammo per shot.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), apply: (p) => { p._perkConserve = 0.25; } });
P({ id: 'overpenetrate4', name: 'Overpenetrate', rarity: 'legendary', weight: 2, tags: ['offense'], description: '+4 pierce; pierced enemies take +25% damage.', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: () => ({ pierce: 4 }), apply: (p) => { p._perkOverpen = true; } });
P({ id: 'secondWind3', name: 'Second Wind', rarity: 'epic', weight: 4, tags: ['defense', 'sustain'], description: 'Below 20% HP, regen 5 HP/s and +25% move speed.', icon: { shape: 'leaf', color: 0x4fd07a }, stat: () => ({}), apply: (p) => { p._perkSecondWind = true; } });
P({ id: 'criticalSurge3', name: 'Critical Surge', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: 'Crits have 40% chance to refund the shot; +0.8 crit mult.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critMult: 0.8 }), apply: (p) => { p._perkCritSurge = true; } });
P({ id: 'bloodlust3', name: 'Bloodlust', rarity: 'epic', weight: 4, tags: ['offense', 'sustain'], description: 'Kills heal 3% HP and grant +15% damage for 3s.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkBloodlust = true; } });
P({ id: 'armorer3', name: 'Armorer', rarity: 'rare', weight: 6, tags: ['defense'], description: '+8 armor and -12% damage taken.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ armor: 8, damageReduction: 0.12 }) });
P({ id: 'fleetFooted3', name: 'Fleet-Footed', rarity: 'rare', weight: 6, tags: ['mobility'], description: '+25% move speed; dash refunds 30% on kill.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.25 }) });
P({ id: 'siege3', name: 'Siege', rarity: 'legendary', weight: 2, tags: ['offense', 'aoe'], description: '+80% AoE and +50% explosive damage.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({ aoeMult: 1.8 }), apply: (p) => { p._perkDemo = true; } });
P({ id: 'gunsmith3', name: 'Gunsmith', rarity: 'epic', weight: 4, tags: ['offense'], description: '+30% magazine, -25% reload, +15% fire rate.', icon: { shape: 'wrench', color: 0x9fb3d6 }, stat: () => ({ magMult: 1.3, reloadMult: 0.75, fireRateMult: 1.15 }) });
P({ id: 'precisionist3', name: 'Precisionist', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+12% crit, +0.5 crit mult, -12% spread.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({ critChance: 0.12, critMult: 0.5, spreadMult: 0.88 }) });
P({ id: 'juggernaut4', name: 'Juggernaut', rarity: 'legendary', weight: 2, tags: ['defense'], description: '+120 max HP, +10 armor, -20% move; CC duration halved.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 120, armor: 10, moveMult: 0.8 }), apply: (p) => { p._perkJuggernaut = true; } });
P({ id: 'apex3', name: 'Apex', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: '+30% crit chance and +1.2 crit multiplier.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critChance: 0.3, critMult: 1.2 }) });
P({ id: 'gunslinger3', name: 'Gunslinger', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+20% crit chance and +0.6 crit mult with sidearms.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({ critChance: 0.2, critMult: 0.6 }) });
P({ id: 'demolitionist3', name: 'Demolitionist', rarity: 'epic', weight: 4, tags: ['offense', 'aoe'], description: '+50% AoE; explosives deal +35% damage.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({ aoeMult: 1.5 }), apply: (p) => { p._perkDemo = true; } });
P({ id: 'duelist3', name: 'Duelist', rarity: 'epic', weight: 4, tags: ['offense'], description: '+30% damage to nearest enemy; +15% move speed.', icon: { shape: 'sword', color: 0x29e7ff }, stat: () => ({ moveMult: 1.15 }) });
P({ id: 'ironWill4', name: 'Iron Will', rarity: 'legendary', weight: 2, tags: ['defense'], description: 'Below 25% HP, take 60% less damage and regen 5 HP/s.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({}), apply: (p) => { p._perkIronWill = true; } });
P({ id: 'pathfinder3', name: 'Pathfinder', rarity: 'epic', weight: 4, tags: ['mobility', 'economy'], description: '+20% move speed and +30% pickup magnet.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.2 }) });
P({ id: 'wildcard3', name: 'Wildcard', rarity: 'legendary', weight: 2, tags: ['offense', 'special'], description: '+40% damage, +40% fire rate, +40% spread. Live fast.', icon: { shape: 'star', color: 0xff3df0 }, stat: () => ({ damageMult: 1.4, fireRateMult: 1.4, spreadMult: 1.4 }) });
P({ id: 'oneShot3', name: 'One Shot', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: 'Headshots deal +150% damage and refund 8% ammo.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ headshotMult: 1.5 }), apply: (p) => { p._perkOneShot = true; } });
P({ id: 'bloodRite3', name: 'Blood Rite', rarity: 'legendary', weight: 2, tags: ['sustain', 'offense'], description: '+12% lifesteal and +30% damage; -20 max HP.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.12, damageMult: 1.3, maxHP: -20 }) });
P({ id: 'overGeared3', name: 'Overgeared', rarity: 'legendary', weight: 2, tags: ['defense'], description: '+100 max HP, +8 armor, +40 shield.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 100, armor: 8, shield: 40 }) });
P({ id: 'triggerHappy3', name: 'Trigger Happy', rarity: 'epic', weight: 4, tags: ['offense'], description: '+30% fire rate and +15% mag size.', icon: { shape: 'lightning', color: 0x29e7ff }, stat: () => ({ fireRateMult: 1.3, magMult: 1.15 }) });
P({ id: 'longShot3', name: 'Long Shot', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+35% range and reduced falloff.', icon: { shape: 'arrow', color: 0x9fe7ff }, stat: () => ({ rangeMult: 1.35 }) });
