// ============================================================================
// perks.js — Perk definitions. Stronger than upgrades, often with trade-offs
// or requirements. Acquired from special choices and the shop.
// ============================================================================

import { PerkRegistry } from '../PerkRegistry.js';

PerkRegistry.registerMany([
  { id: 'adrenalineJunkie', name: 'Adrenaline Junkie', rarity: 'rare', weight: 6, tags: ['mobility', 'offense'],
    description: '+20% fire rate and +15% move speed for 3s after dashing.',
    icon: { shape: 'bolt', color: 0x29e7ff }, stat: () => ({}), apply: (p) => { p._perkAdrenaline = true; } },
  { id: 'executioner', name: 'Executioner', rarity: 'epic', weight: 4, tags: ['offense'],
    description: 'Kills below 30% HP restore 5% ammo and grant +25% damage for 2s.',
    icon: { shape: 'skull', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkExecutioner = true; } },
  { id: 'vampire', name: 'Vampire', rarity: 'epic', weight: 4, tags: ['sustain', 'offense'],
    description: '+5% lifesteal and +10% damage, but -10 max HP.',
    icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.05, damageMult: 1.1, maxHP: -10 }) },
  { id: 'swiftReflexes', name: 'Swift Reflexes', rarity: 'rare', weight: 6, tags: ['mobility'],
    description: '-25% dash cooldown and +10% move speed.',
    icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({ dashCDMult: 0.75, moveMult: 1.1 }) },
  { id: 'heavyCaliber', name: 'Heavy Caliber', rarity: 'rare', weight: 6, tags: ['offense'],
    description: '+30% damage and +50% knockback, but +10% spread.',
    icon: { shape: 'shell', color: 0xffaa44 }, stat: () => ({ damageMult: 1.3, knockbackMult: 1.5, spreadMult: 1.1 }) },
  { id: 'elementalist', name: 'Elementalist', rarity: 'epic', weight: 4, tags: ['offense', 'status'],
    description: '+40% status power and +30% status chance.',
    icon: { shape: 'flame', color: 0xff6633 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.3 }) },
  { id: 'munitionsExpert', name: 'Munitions Expert', rarity: 'rare', weight: 6, tags: ['offense'],
    description: '+30% magazine size and -20% reload time.',
    icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({ magMult: 1.3, reloadMult: 0.8 }) },
  { id: 'shieldMastery', name: 'Shield Mastery', rarity: 'rare', weight: 6, tags: ['defense'],
    description: '+40 shield and shields regen 50% faster.',
    icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 40 }) },
  { id: 'berserkerPerk', name: 'Rage', rarity: 'epic', weight: 4, tags: ['offense'],
    description: '+50% damage while below 50% HP.',
    icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), apply: (p) => { p._perkRage = true; } },
  { id: 'scavenger', name: 'Scavenger', rarity: 'rare', weight: 6, tags: ['economy'],
    description: '+30% currency and +20% pickup magnet range.',
    icon: { shape: 'coin', color: 0xffb347 }, stat: () => ({ currencyMult: 1.3 }) },
  { id: 'scholar', name: 'Scholar', rarity: 'rare', weight: 6, tags: ['economy'],
    description: '+30% XP and level-ups grant an extra upgrade choice.',
    icon: { shape: 'book', color: 0x9fe7ff }, stat: () => ({ xpMult: 1.3 }), apply: (p) => { p._extraChoices = (p._extraChoices || 0) + 1; } },
  { id: 'thornmail', name: 'Thornmail', rarity: 'rare', weight: 6, tags: ['defense'],
    description: '+15 thorns and -10% damage taken.',
    icon: { shape: 'cactus', color: 0x4fd07a }, stat: () => ({ thorns: 15, damageReduction: 0.1 }) },
  { id: 'glassHeart', name: 'Glass Heart', rarity: 'legendary', weight: 2, tags: ['offense', 'curse'],
    description: '+80% damage, but maximum HP is set to 50.',
    icon: { shape: 'heart', color: 0xff3df0 }, stat: () => ({ damageMult: 1.8, maxHP: -50 }) },
  { id: 'titan', name: 'Titan', rarity: 'epic', weight: 4, tags: ['defense'],
    description: '+60 max HP, +4 armor, but -10% move speed.',
    icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 60, armor: 4, moveMult: 0.9 }) },
  { id: 'chainMaster', name: 'Chain Master', rarity: 'epic', weight: 4, tags: ['offense'],
    description: 'Hits chain to +1 nearby enemy and +15% damage.',
    icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ damageMult: 1.15 }), apply: (p) => { p._perkChain = (p._perkChain || 0) + 1; } },
  { id: 'fortress', name: 'Fortress', rarity: 'rare', weight: 6, tags: ['defense'],
    description: '+5 armor, +25 shield, and -15% damage taken while stationary.',
    icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ armor: 5, shield: 25 }) },
  { id: 'overdriver', name: 'Overdriver', rarity: 'epic', weight: 4, tags: ['offense'],
    description: '+35% fire rate, but +15% spread.',
    icon: { shape: 'chip', color: 0xff5544 }, stat: () => ({ fireRateMult: 1.35, spreadMult: 1.15 }) },
  { id: 'necromancer', name: 'Necromancer', rarity: 'legendary', weight: 2, tags: ['special'],
    description: 'Kills have a 15% chance to spawn a temporary allied drone.',
    icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), apply: (p) => { p._perkNecromancer = true; } },
]);
