// ============================================================================
// perks5.js — A large batch of additional perks for deep build variety.
// ============================================================================

import { PerkRegistry } from '../PerkRegistry.js';

const P = (def) => PerkRegistry.register(def);

P({ id: 'steadyHand', name: 'Steady Hand', rarity: 'rare', weight: 6, tags: ['offense'], description: '-20% spread and -10% recoil.', icon: { shape: 'target', color: 0x29e7ff }, stat: () => ({ spreadMult: 0.8 }) });
P({ id: 'rapidFire', name: 'Rapid Fire', rarity: 'rare', weight: 6, tags: ['offense'], description: '+15% fire rate.', icon: { shape: 'lightning', color: 0x29e7ff }, stat: () => ({ fireRateMult: 1.15 }) });
P({ id: 'heavyCaliber2', name: 'Heavy Caliber', rarity: 'rare', weight: 6, tags: ['offense'], description: '+25% damage and +30% knockback.', icon: { shape: 'shell', color: 0xffaa44 }, stat: () => ({ damageMult: 1.25, knockbackMult: 1.3 }) });
P({ id: 'shieldBearer', name: 'Shield Bearer', rarity: 'rare', weight: 6, tags: ['defense'], description: '+50 shield and shields regen 50% faster.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 50 }) });
P({ id: 'ironSkin', name: 'Iron Skin', rarity: 'rare', weight: 6, tags: ['defense'], description: '+5 armor and -10% damage taken.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ armor: 5, damageReduction: 0.1 }) });
P({ id: 'fleet', name: 'Fleet', rarity: 'rare', weight: 6, tags: ['mobility'], description: '+20% move speed.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.2 }) });
P({ id: 'vampiric2', name: 'Vampiric', rarity: 'epic', weight: 4, tags: ['sustain'], description: '+5% lifesteal.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.05 }) });
P({ id: 'giantkiller2', name: 'Giantkiller', rarity: 'epic', weight: 4, tags: ['offense'], description: '+50% damage vs elites and bosses.', icon: { shape: 'skull', color: 0xffb347 }, stat: () => ({}), apply: (p) => { p._giantkiller = (p._giantkiller || 0) + 1; } });
P({ id: 'berserker3', name: 'Frenzy', rarity: 'epic', weight: 4, tags: ['offense'], description: '+40% damage below 40% HP.', icon: { shape: 'fire', color: 0xff5544 }, stat: () => ({}), apply: (p) => { p._berserker = true; } });
P({ id: 'lastStand2', name: 'Last Stand', rarity: 'epic', weight: 4, tags: ['defense'], description: 'Survive a lethal hit at 1 HP once per wave.', icon: { shape: 'shield', color: 0xff7733 }, stat: () => ({}), apply: (p) => { p._lastStand = true; } });
P({ id: 'adrenalJunkie2', name: 'Adrenaline', rarity: 'rare', weight: 6, tags: ['mobility', 'offense'], description: '+20% fire rate and +15% move speed for 3s after dashing.', icon: { shape: 'bolt', color: 0x29e7ff }, stat: () => ({}), apply: (p) => { p._perkAdrenaline = true; } });
P({ id: 'executioner3', name: 'Executioner', rarity: 'epic', weight: 4, tags: ['offense'], description: 'Kills below 30% HP refund 5% ammo and grant +25% damage for 2s.', icon: { shape: 'skull', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkExecutioner = true; } });
P({ id: 'overclock2', name: 'Overclock', rarity: 'epic', weight: 4, tags: ['offense'], description: '+25% fire rate, but +10% spread.', icon: { shape: 'chip', color: 0xff5544 }, stat: () => ({ fireRateMult: 1.25, spreadMult: 1.1 }) });
P({ id: 'momentum2', name: 'Momentum', rarity: 'rare', weight: 6, tags: ['mobility', 'offense'], description: '+15% damage while moving; +10% move speed.', icon: { shape: 'wind', color: 0x9fe7ff }, stat: () => ({ moveMult: 1.1 }), apply: (p) => { p._perkMomentum = true; } });
P({ id: 'scavenger2', name: 'Scavenger', rarity: 'rare', weight: 6, tags: ['economy'], description: '+30% currency and +20% pickup magnet range.', icon: { shape: 'coin', color: 0xffb347 }, stat: () => ({ currencyMult: 1.3 }) });
P({ id: 'scholar2', name: 'Scholar', rarity: 'rare', weight: 6, tags: ['economy'], description: '+30% XP and level-ups grant an extra upgrade choice.', icon: { shape: 'book', color: 0x9fe7ff }, stat: () => ({ xpMult: 1.3 }), apply: (p) => { p._extraChoices = (p._extraChoices || 0) + 1; } });
P({ id: 'thornmail2', name: 'Thornmail', rarity: 'rare', weight: 6, tags: ['defense'], description: '+15 thorns and -10% damage taken.', icon: { shape: 'cactus', color: 0x4fd07a }, stat: () => ({ thorns: 15, damageReduction: 0.1 }) });
P({ id: 'elementalist3', name: 'Elementalist', rarity: 'epic', weight: 4, tags: ['offense', 'status'], description: '+40% status power and +30% status chance.', icon: { shape: 'flame', color: 0xff6633 }, stat: () => ({ statusPowerMult: 1.4, statusChanceMult: 1.3 }) });
P({ id: 'munitionsExpert3', name: 'Munitions Expert', rarity: 'rare', weight: 6, tags: ['offense'], description: '+30% magazine and -20% reload.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({ magMult: 1.3, reloadMult: 0.8 }) });
P({ id: 'glassHeart2', name: 'Glass Heart', rarity: 'legendary', weight: 2, tags: ['offense', 'curse'], description: '+80% damage, but max HP set to 50.', icon: { shape: 'heart', color: 0xff3df0 }, stat: () => ({ damageMult: 1.8, maxHP: -50 }) });
P({ id: 'titan2', name: 'Titan', rarity: 'epic', weight: 4, tags: ['defense'], description: '+60 max HP, +4 armor, -10% move speed.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 60, armor: 4, moveMult: 0.9 }) });
P({ id: 'chainMaster2', name: 'Chain Master', rarity: 'epic', weight: 4, tags: ['offense'], description: 'Hits chain to +1 nearby enemy and +15% damage.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ damageMult: 1.15 }), apply: (p) => { p._perkChain = (p._perkChain || 0) + 1; } });
P({ id: 'fortress2', name: 'Fortress', rarity: 'rare', weight: 6, tags: ['defense'], description: '+5 armor, +25 shield, -15% damage taken while stationary.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ armor: 5, shield: 25 }) });
P({ id: 'overdriver2', name: 'Overdriver', rarity: 'epic', weight: 4, tags: ['offense'], description: '+35% fire rate, but +15% spread.', icon: { shape: 'chip', color: 0xff5544 }, stat: () => ({ fireRateMult: 1.35, spreadMult: 1.15 }) });
P({ id: 'necromancer2', name: 'Necromancer', rarity: 'legendary', weight: 2, tags: ['special'], description: 'Kills have a 15% chance to spawn a temporary allied drone.', icon: { shape: 'skull', color: 0xb266ff }, stat: () => ({}), apply: (p) => { p._perkNecromancer = true; } });
P({ id: 'surgical2', name: 'Surgical', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+0.5 headshot mult and headshots refill 2% ammo.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ headshotMult: 0.5 }), apply: (p) => { p._perkSurgical = true; } });
P({ id: 'vanguard2', name: 'Vanguard', rarity: 'rare', weight: 6, tags: ['defense', 'mobility'], description: '+30 shield and dashing refunds 20% cooldown on kill.', icon: { shape: 'shield', color: 0x29e7ff }, stat: () => ({ shield: 30 }) });
P({ id: 'pyromancer3', name: 'Pyromancer', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits ignite; +50% burn power.', icon: { shape: 'flame', color: 0xff5522 }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), apply: (p) => { p._perkPyromancer = true; } });
P({ id: 'cryomancer3', name: 'Cryomancer', rarity: 'legendary', weight: 2, tags: ['offense', 'status', 'control'], description: 'All hits freeze; +50% freeze power.', icon: { shape: 'snow', color: 0x9fe7ff }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), apply: (p) => { p._perkCryomancer = true; } });
P({ id: 'stormcaller3', name: 'Stormcaller', rarity: 'legendary', weight: 2, tags: ['offense', 'status'], description: 'All hits shock; +50% shock power.', icon: { shape: 'bolt', color: 0xffe066 }, stat: () => ({ statusPowerMult: 1.5, statusChanceMult: 1.5 }), apply: (p) => { p._perkStormcaller = true; } });
P({ id: 'kineticist2', name: 'Kineticist', rarity: 'epic', weight: 4, tags: ['offense', 'control'], description: '+60% knockback; slammed enemies take +20% damage.', icon: { shape: 'fist', color: 0xffaa44 }, stat: () => ({ knockbackMult: 1.6 }), apply: (p) => { p._perkKineticist = true; } });
P({ id: 'ammoConservation2', name: 'Conservation', rarity: 'rare', weight: 6, tags: ['offense'], description: '15% chance not to consume ammo per shot.', icon: { shape: 'mag', color: 0xffaa44 }, stat: () => ({}), apply: (p) => { p._perkConserve = 0.15; } });
P({ id: 'overpenetrate2', name: 'Overpenetrate', rarity: 'epic', weight: 4, tags: ['offense'], description: '+2 pierce; pierced enemies take +10% damage.', icon: { shape: 'arrow', color: 0x4aa3ff }, stat: () => ({ pierce: 2 }), apply: (p) => { p._perkOverpen = true; } });
P({ id: 'secondWind2', name: 'Second Wind', rarity: 'epic', weight: 4, tags: ['defense', 'sustain'], description: 'Below 20% HP, regen 4 HP/s and +20% move speed.', icon: { shape: 'leaf', color: 0x4fd07a }, stat: () => ({}), apply: (p) => { p._perkSecondWind = true; } });
P({ id: 'criticalSurge2', name: 'Critical Surge', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: 'Crits have 30% chance to refund the shot; +0.5 crit mult.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critMult: 0.5 }), apply: (p) => { p._perkCritSurge = true; } });
P({ id: 'bloodlust2', name: 'Bloodlust', rarity: 'epic', weight: 4, tags: ['offense', 'sustain'], description: 'Kills heal 2% HP and grant +10% damage for 3s.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({}), apply: (p) => { p._perkBloodlust = true; } });
P({ id: 'armorer2', name: 'Armorer', rarity: 'rare', weight: 6, tags: ['defense'], description: '+6 armor and -10% damage taken.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ armor: 6, damageReduction: 0.1 }) });
P({ id: 'fleetFooted2', name: 'Fleet-Footed', rarity: 'rare', weight: 6, tags: ['mobility'], description: '+20% move speed; dash refunds 25% on kill.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.2 }) });
P({ id: 'siege2', name: 'Siege', rarity: 'epic', weight: 4, tags: ['offense', 'aoe'], description: '+50% AoE and +20% explosive damage.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({ aoeMult: 1.5 }), apply: (p) => { p._perkDemo = true; } });
P({ id: 'gunsmith2', name: 'Gunsmith', rarity: 'rare', weight: 6, tags: ['offense'], description: '+25% magazine, -20% reload, +10% fire rate.', icon: { shape: 'wrench', color: 0x9fb3d6 }, stat: () => ({ magMult: 1.25, reloadMult: 0.8, fireRateMult: 1.1 }) });
P({ id: 'precisionist2', name: 'Precisionist', rarity: 'epic', weight: 4, tags: ['offense', 'precision'], description: '+10% crit, +0.4 crit mult, -10% spread.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({ critChance: 0.1, critMult: 0.4, spreadMult: 0.9 }) });
P({ id: 'juggernaut3', name: 'Juggernaut', rarity: 'epic', weight: 4, tags: ['defense'], description: '+80 max HP, +6 armor, -15% move; CC duration halved.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({ maxHP: 80, armor: 6, moveMult: 0.85 }), apply: (p) => { p._perkJuggernaut = true; } });
P({ id: 'apex2', name: 'Apex', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: '+25% crit chance and +1.0 crit multiplier.', icon: { shape: 'star', color: 0xffb347 }, stat: () => ({ critChance: 0.25, critMult: 1.0 }) });
P({ id: 'gunslinger2', name: 'Gunslinger', rarity: 'rare', weight: 6, tags: ['offense', 'precision'], description: '+15% crit chance and +0.5 crit mult with sidearms.', icon: { shape: 'target', color: 0xffb347 }, stat: () => ({ critChance: 0.15, critMult: 0.5 }) });
P({ id: 'demolitionist2', name: 'Demolitionist', rarity: 'epic', weight: 4, tags: ['offense', 'aoe'], description: '+40% AoE; explosives deal +25% damage.', icon: { shape: 'blast', color: 0xff7733 }, stat: () => ({ aoeMult: 1.4 }), apply: (p) => { p._perkDemo = true; } });
P({ id: 'duelist2', name: 'Duelist', rarity: 'rare', weight: 6, tags: ['offense'], description: '+20% damage to nearest enemy; +10% move speed.', icon: { shape: 'sword', color: 0x29e7ff }, stat: () => ({ moveMult: 1.1 }) });
P({ id: 'ironWill3', name: 'Iron Will', rarity: 'epic', weight: 4, tags: ['defense'], description: 'Below 25% HP, take 50% less damage and regen 3 HP/s.', icon: { shape: 'shield', color: 0x4aa3ff }, stat: () => ({}), apply: (p) => { p._perkIronWill = true; } });
P({ id: 'pathfinder2', name: 'Pathfinder', rarity: 'rare', weight: 6, tags: ['mobility', 'economy'], description: '+15% move speed and +20% pickup magnet range.', icon: { shape: 'boot', color: 0x4fffd0 }, stat: () => ({ moveMult: 1.15 }) });
P({ id: 'wildcard2', name: 'Wildcard', rarity: 'legendary', weight: 2, tags: ['offense', 'special'], description: '+30% damage, +30% fire rate, +30% spread.', icon: { shape: 'star', color: 0xff3df0 }, stat: () => ({ damageMult: 1.3, fireRateMult: 1.3, spreadMult: 1.3 }) });
P({ id: 'oneShot2', name: 'One Shot', rarity: 'legendary', weight: 2, tags: ['offense', 'precision'], description: 'Headshots deal +100% damage and refund 5% ammo.', icon: { shape: 'target', color: 0xff3df0 }, stat: () => ({ headshotMult: 1.0 }), apply: (p) => { p._perkOneShot = true; } });
P({ id: 'bloodRite2', name: 'Blood Rite', rarity: 'epic', weight: 4, tags: ['sustain', 'offense'], description: '+8% lifesteal and +20% damage; -15 max HP.', icon: { shape: 'drop', color: 0xff3df0 }, stat: () => ({ lifesteal: 0.08, damageMult: 1.2, maxHP: -15 }) });
